// The forced password change (ADR 0019, migrations/0031).
//
// IT IS A GATE, NOT A PAGE. While `harus_ganti_sandi` is set, this is the only
// thing the mitra area renders: no tabs, no akad, no profile. The server holds
// the same line with `wajibSandiSendiri`, so a mitra who typed a URL past this
// screen would be refused there too. Two locks, and neither is decorative: the
// server's is the guarantee, and this one is the reason a person is not sent
// round a loop of 403s to find out what they are supposed to do.
//
// WHY IT EXISTS AT ALL: the first password was generated by the server and read
// out by an officer, so until it is replaced it is a secret TWO people know.
// The screen says exactly that, because "ganti kata sandi Anda" without a
// reason reads as bureaucracy and gets the shortest legal password somebody can
// think of.
//
// THE RULES ARE THE SERVER'S, STATED BEFORE THE ATTEMPT. Minimum twelve
// characters, not equal to the email address, not equal to the old password.
// They are checked here so a person is told which rule they missed, and checked
// again by the server, which is the one that decides.
import { useState } from "react";
import { Button, Field, Icon, PasswordInput } from "@krakatausteel/ui";
import { MitraTidakTerhubung } from "../api/mitra";
import { GagalMitra } from "./MitraApp";
import { useSesiMitra } from "./sesi";

/** apps/api/src/modules/mitra/contract.ts, `MIN_PANJANG_SANDI`. Restated with
 *  its source so a change there is a one line change here, and ../mitra.test.tsx
 *  imports the server's constant and pins the two together. */
const MIN_PANJANG = 12;

export function GantiSandiMitra() {
  const { profil, gantiSandi, keluar, error } = useSesiMitra();
  const [sandiLama, setSandiLama] = useState("");
  const [sandiBaru, setSandiBaru] = useState("");
  const [ulangi, setUlangi] = useState("");
  const [sentuh, setSentuh] = useState(false);
  const [mengirim, setMengirim] = useState(false);
  const [gagal, setGagal] = useState<string | null>(error);

  const email = profil?.email ?? "";
  const galat: Record<string, string> = {};
  if (sandiLama === "") galat.sandiLama = "Wajib diisi.";
  if (sandiBaru.length < MIN_PANJANG) {
    galat.sandiBaru = `Minimal ${MIN_PANJANG} karakter.`;
  } else if (email !== "" && sandiBaru.toLowerCase() === email.toLowerCase()) {
    galat.sandiBaru = "Kata sandi tidak boleh sama dengan email Anda.";
  } else if (sandiBaru === sandiLama) {
    galat.sandiBaru = "Kata sandi baru harus berbeda dari yang sekarang.";
  }
  if (ulangi !== sandiBaru) galat.ulangi = "Pengulangan belum sama dengan kata sandi baru.";
  const siap = Object.keys(galat).length === 0;

  async function kirim(event: { preventDefault: () => void }) {
    event.preventDefault();
    setSentuh(true);
    if (!siap || mengirim) return;
    setMengirim(true);
    setGagal(null);
    try {
      await gantiSandi(sandiLama, sandiBaru);
    } catch (penyebab) {
      setGagal(
        penyebab instanceof MitraTidakTerhubung
          ? penyebab.message
          : penyebab instanceof Error
            ? penyebab.message
            : "Kata sandi belum berhasil diganti. Coba lagi.",
      );
      setMengirim(false);
    }
  }

  return (
    <div className="mitra-masuk">
      <form className="mitra-masuk-kotak" onSubmit={kirim}>
        <div className="mitra-masuk-head">
          <span className="mitra-mark" aria-hidden="true">
            <Icon name="lock" size={20} />
          </span>
          <h1 className="mitra-masuk-judul">Ganti Kata Sandi Dulu</h1>
          <p className="mitra-masuk-sub">
            Kata sandi pertama Anda dibuat oleh sistem dan diserahkan oleh petugas, jadi untuk
            sementara ada dua pihak yang mengetahuinya. Ganti sekarang supaya hanya Anda yang tahu.
          </p>
        </div>

        {gagal ? <GagalMitra pesan={gagal} /> : null}

        <Field
          label="Kata sandi sekarang"
          required
          {...(sentuh && galat.sandiLama ? { error: galat.sandiLama } : {})}
        >
          <PasswordInput
            value={sandiLama}
            autoComplete="current-password"
            maxLength={200}
            invalid={sentuh && galat.sandiLama !== undefined}
            onChange={(event) => setSandiLama(event.currentTarget.value)}
          />
        </Field>

        <Field
          label="Kata sandi baru"
          required
          hint={`Minimal ${MIN_PANJANG} karakter, dan tidak boleh sama dengan email Anda.`}
          {...(sentuh && galat.sandiBaru ? { error: galat.sandiBaru } : {})}
        >
          <PasswordInput
            value={sandiBaru}
            autoComplete="new-password"
            maxLength={200}
            invalid={sentuh && galat.sandiBaru !== undefined}
            onChange={(event) => setSandiBaru(event.currentTarget.value)}
          />
        </Field>

        <Field
          label="Ulangi kata sandi baru"
          required
          {...(sentuh && galat.ulangi ? { error: galat.ulangi } : {})}
        >
          <PasswordInput
            value={ulangi}
            autoComplete="new-password"
            maxLength={200}
            invalid={sentuh && galat.ulangi !== undefined}
            onChange={(event) => setUlangi(event.currentTarget.value)}
          />
        </Field>

        <Button type="submit" variant="primary" loading={mengirim} block>
          Simpan kata sandi baru
        </Button>

        {/* The one other thing reachable in this state, and it has to be here:
            an account held at a screen with no way out is an account whose
            owner closes the tab and telephones the branch. */}
        <Button variant="ghost" block onClick={() => void keluar()}>
          Keluar
        </Button>
      </form>
    </div>
  );
}
