// apps/api/src/modules/closing/test-support.ts
//
// Reusable fixture builder for the closing engine tests (spec 8). NOT a
// *.test.ts file, so `bun test` never executes it on its own.
//
// WHY THESE TESTS HIT REAL POSTGRES
// Closing is the one engine whose correctness is almost entirely a claim about
// what the database already contains, and most of what it must respect lives
// inside Postgres:
//   - invariant 6, sequential close, and the reopen ordering + mandatory
//     reason, as `trg_periode_10_transisi` (migrations/0007);
//   - invariant 5, no posting into a CLOSED period (migrations/0010, 0018);
//   - invariant 13, one snapshot per akad per period, as
//     `kolektibilitas_snapshot_uq`, and one committed run per scope as
//     `closing_kolektibilitas_selesai_uq` (migrations/0011);
//   - the arithmetic of spec 8.2 step 3 and of the frozen trial balance, as
//     CHECK constraints (`penyisihan_periode_beban_ck`,
//     `saldo_akun_periode_identitas_ck`);
//   - `v_ledger_baris` and `v_rekonsiliasi_piutang`, which ARE the definition
//     of the two numbers closing freezes and the one it reconciles.
// A fake or in-memory repository proves nothing about any of that. So every
// fixture below writes to `tjsl_test`, which tools/test-env.ts guarantees is
// where DATABASE_URL points during `bun test`.
//
// WHY THE COLLABORATING ENGINES ARE REAL, WRAPPED, NEVER REPLACED
// modules/angsuran/test-support.ts records what the alternative cost: a pure
// double for the journal port hid two production-breaking defects behind
// sixteen green tests. THE RULE THAT CAME OUT OF IT, and that this file
// follows: a double may stand in for a collaborator's FAILURE, never for its
// VALIDATION. `porterJurnalUji` below is a RECORDING WRAPPER around the engine
// reached through `../jurnal/index` (the import the boundary checker allows and
// the wiring the composition root uses). It records calls and can be armed to
// fail; it never answers in the real engine's place. Every schedule is
// generated by the real instalment engine and every deposit is allocated by it,
// so the arrears this fixture manufactures are arrears the rest of the system
// agrees exist.
//
// WHY SO MUCH OF THIS RESEMBLES modules/pumk/test-support.ts
// `bun tools/check-boundaries.ts` forbids a deep import into a sibling
// module's internals, and that file is internal to modules/pumk. The money
// helpers, the unique-key helper, the DB port and the leak-detecting
// `tolakDengan` are therefore re-declared here with the SAME semantics. Two
// rules follow: the shapes must not drift (a sen-level difference between two
// modules' `keSen` would be a real bug in a real ledger), and when a shared
// test-support package appears, this file collapses into it.
//
// THE COA, THE EVENT MAPPINGS, THE PERMISSIONS AND THE PARAMETER CATALOGUE ARE
// THE SHIPPED ONES. `seedCoaDanEventMapping`, `seedKonfigurasiTambahan` and
// `seedRbac` from apps/api/src/seed are called directly rather than re-typed,
// and every context's permission list comes from `permissionsForRole`, which
// READS the grant matrix out of the database. A fixture that hardcodes
// `permissions: ["admin.closing.periode"]` asserts against its own opinion;
// that is how `jurnal.update` / `jurnal.delete` being grantable to nobody
// stayed invisible.
//
// NO TEST MAY DEPEND ON ANOTHER TEST'S DATA. `bun run db:reset` is run
// periodically by other agents and nothing here is cleaned up afterwards
// (physical DELETE is blocked on several of these tables by design), so every
// fixture key is uniquified per call via `kunci()` and every world gets its own
// bumn, branches, chart of accounts, periods, parameter rows, kolektibilitas
// ranges and allowance rates. TWO CONSECUTIVE RUNS WITHOUT A RESET THEREFORE
// PRODUCE IDENTICAL RESULTS, which is a property this suite is required to
// demonstrate rather than assume.
import { SQL } from "bun";
import { expect } from "bun:test";
import { createAngsuranModule, type AngsuranContext, type HasilAlokasi } from "../angsuran/index";
import { createJurnalModule, type Jurnal, type JurnalContext } from "../jurnal/index";
import { createDbAdapter } from "../../core/adapters/db";
import { createAuditService } from "../audit/index";
import { KATALOG, tipeDataUntuk } from "../konfigurasi/index";
import { seedCoaDanEventMapping } from "../../seed/event-jurnal";
import { seedKonfigurasiTambahan } from "../../seed/konfigurasi";
import { permissionsForRole, seedRbac } from "../../seed/rbac";
import {
  ClosingError,
  KODE_CLOSING,
  createClosingEngine,
  type ClosingContext,
  type ClosingDbPort,
  type ClosingEngine,
  type ClosingTx,
  type KelasKolektibilitas,
  type KodeClosing,
  type PencatatAuditClosing,
  type PorterJurnalClosing,
  type Rate,
  type Uang,
} from "./contract";

// ---------------------------------------------------------------------------
// Money helpers. BigInt minor units internally, decimal string at the edges,
// never a float (spec invariant 7).
// ---------------------------------------------------------------------------

/** Whole rupiah -> `Uang`. `rp(1_500_000)` === "1500000.00". */
export function rp(rupiahBulat: number): Uang {
  if (!Number.isInteger(rupiahBulat)) {
    throw new Error(`rp() hanya menerima rupiah bulat, dapat ${rupiahBulat}`);
  }
  return `${rupiahBulat}.00`;
}

/** Minor units (sen) -> `Uang`. Signed: closing works with signed figures. */
export function sen(minor: bigint): Uang {
  const negatif = minor < 0n;
  const abs = negatif ? -minor : minor;
  const utuh = abs / 100n;
  const pecahan = abs % 100n;
  return `${negatif ? "-" : ""}${utuh}.${String(pecahan).padStart(2, "0")}`;
}

/** `Uang` -> minor units. Rejects anything that is not exactly two decimals. */
export function keSen(nilai: Uang): bigint {
  const m = /^(-?)(\d+)\.(\d{2})$/.exec(nilai);
  if (!m) throw new Error(`bukan Uang yang valid: ${JSON.stringify(nilai)}`);
  const besar = BigInt(m[2]) * 100n + BigInt(m[3]);
  return m[1] === "-" ? -besar : besar;
}

export function jumlahUang(...nilai: Uang[]): Uang {
  return sen(nilai.reduce((acc, n) => acc + keSen(n), 0n));
}

export function kurangUang(a: Uang, b: Uang): Uang {
  return sen(keSen(a) - keSen(b));
}

export function negasiUang(a: Uang): Uang {
  return sen(-keSen(a));
}

/**
 * `outstanding * rate`, rounded HALF UP to the sen, which is what
 * `kolektibilitas_snapshot_nilai_ck` re-derives with Postgres `round()`. Done
 * in BigInt so a test's expectation and the database's CHECK cannot disagree
 * because of a float.
 */
export function kaliRate(nilai: Uang, rate: Rate): Uang {
  const m = /^(\d{1,3})\.(\d{6})$/.exec(rate);
  if (!m) throw new Error(`bukan Rate yang valid: ${JSON.stringify(rate)}`);
  const rateMikro = BigInt(m[1]) * 1_000_000n + BigInt(m[2]);
  const produk = keSen(nilai) * rateMikro; // scaled by 1e6
  const negatif = produk < 0n;
  const abs = negatif ? -produk : produk;
  const dibulatkan = (abs + 500_000n) / 1_000_000n;
  return sen(negatif ? -dibulatkan : dibulatkan);
}

// ---------------------------------------------------------------------------
// Unique keys and dates
// ---------------------------------------------------------------------------

const JEJAK = crypto.randomUUID().replace(/-/g, "").slice(0, 8);
let urut = 0;

/**
 * A key unique across worlds, runs and parallel files. Every business key this
 * fixture writes goes through here, because `bun run db:reset` is NOT run
 * between files and several of these tables refuse a physical DELETE. This is
 * the whole reason two consecutive `bun test` runs without a reset produce the
 * same results instead of colliding on the second.
 */
export function kunci(awalan: string): string {
  urut += 1;
  return `${awalan}-${JEJAK}-${String(urut).padStart(4, "0")}`;
}

/** Adds whole days to an ISO date. UTC throughout, no local-time drift. */
export function tambahHari(iso: string, hari: number): string {
  const [t, b, h] = iso.split("-").map((x) => Number.parseInt(x, 10));
  const d = new Date(Date.UTC(t, b - 1, h));
  d.setUTCDate(d.getUTCDate() + hari);
  return d.toISOString().slice(0, 10);
}

/**
 * Adds whole months to an ISO date, clamping to the end of the target month.
 * Same rule as the schedule engine's `tanggalJatuhTempo`, so a fixture's
 * expected due dates cannot disagree with the engine's for an incidental
 * reason.
 */
export function tambahBulan(iso: string, bulan: number): string {
  const [t, b, h] = iso.split("-").map((x) => Number.parseInt(x, 10));
  const totalBulan = b - 1 + bulan;
  const tahunBaru = t + Math.floor(totalBulan / 12);
  const bulanBaru = ((totalBulan % 12) + 12) % 12;
  const hariTerakhir = new Date(Date.UTC(tahunBaru, bulanBaru + 1, 0)).getUTCDate();
  const hariBaru = Math.min(h, hariTerakhir);
  return `${tahunBaru}-${String(bulanBaru + 1).padStart(2, "0")}-${String(hariBaru).padStart(2, "0")}`;
}

/** Whole days between two ISO dates, `sampai - dari`. */
export function selisihHari(dari: string, sampai: string): number {
  const a = Date.parse(`${dari}T00:00:00.000Z`);
  const b = Date.parse(`${sampai}T00:00:00.000Z`);
  return Math.round((b - a) / 86_400_000);
}

// ---------------------------------------------------------------------------
// The DB port
// ---------------------------------------------------------------------------

function urlDb(): string {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error(
      "DATABASE_URL tidak ada. Test closing butuh Postgres nyata (tjsl_test). " +
        "Jalankan `bun run db:reset` dan `bun test` dari root repo (lihat docs/DEV.md).",
    );
  }
  if (!url.split("?")[0].endsWith("_test")) {
    throw new Error(`Menolak menjalankan fixture closing di database non-test: ${url}`);
  }
  return url;
}

interface PortUji extends ClosingDbPort {
  tutup(): Promise<void>;
}

function buatPortDb(): PortUji {
  const sql = new SQL({ url: urlDb(), max: 6 });
  const bungkus = (jalankan: (t: string, p: unknown[]) => Promise<unknown>): ClosingTx => ({
    async query<T = unknown>(text: string, params: unknown[] = []): Promise<T[]> {
      const hasil = await jalankan(text, params);
      return hasil as unknown as T[];
    },
  });
  return {
    query: bungkus((t, p) => sql.unsafe(t, p as never[])).query,
    async transaction<T>(jalankan: (tx: ClosingTx) => Promise<T>): Promise<T> {
      const hasil = await sql.begin(async (tx) =>
        jalankan(bungkus((t, p) => tx.unsafe(t, p as never[]))),
      );
      return hasil as T;
    },
    async tutup(): Promise<void> {
      await sql.close();
    },
  };
}

// ---------------------------------------------------------------------------
// Accounts, by the friendly name the tests use
// ---------------------------------------------------------------------------

/**
 * Codes from apps/api/src/seed/coa-inti.ts, which is also what seeds them.
 * Deliberately a lookup onto the SHIPPED codes rather than a second chart of
 * accounts: a fixture COA that drifts from the seeded one is not a failing
 * test, it is a journal posting to the wrong account in production.
 */
const KODE_AKUN = {
  kas: "1.1.01",
  bank: "1.1.02",
  piutangPokok: "1.1.03",
  piutangJasa: "1.1.04",
  penyisihan: "1.1.05",
  kelebihanAngsuran: "2.1.01",
  pendapatanAlokasi: "4.1.01",
  pendapatanJasaAdm: "4.1.02",
  bebanPenyisihan: "5.1.01",
  bebanOperasional: "5.1.04",
} as const;

export type KunciAkun = keyof typeof KODE_AKUN;

export interface AkunFixture {
  id: string;
  kode: string;
}

// ---------------------------------------------------------------------------
// Configuration rows, scoped to the world's bumn
// ---------------------------------------------------------------------------

/**
 * Seeded per world with `bumn_id` set, so a world's values are its own and no
 * test can be perturbed by another agent editing the global (bumn_id NULL) rows
 * that migrations/0004 ships. Every engine in this repo resolves bumn-scoped
 * over global, which is what makes this work.
 *
 * EVERY VALUE HERE IS A FIXTURE VALUE, NOT A POLICY CLAIM. docs/REGULASI.md
 * finding 3 and docs/BUILD-PLAN.md "Dampak temuan regulasi" record that the
 * spec's rate table is not what the regulation in force says, and that the
 * decision belongs to the client's accounting team. No test in this folder
 * asserts that any of these numbers is correct; they assert that changing the
 * row changes the behaviour.
 */
const KONFIGURASI_AWAL: ReadonlyArray<[string, string, string]> = [
  // angsuran / jasa, needed because the REAL instalment engine builds the
  // schedules whose arrears this fixture manufactures.
  ["angsuran", "pembulatan_angsuran", "0"],
  ["angsuran", "urutan_alokasi_setoran_preset", "DEFAULT"],
  ["angsuran", "hari_jatuh_tempo_tetap", "0"],
  ["jasa_adm", "jasa_adm_rate_default", "0.030000"],
  ["jasa_adm", "jasa_adm_metode_default", "FLAT"],
  ["jasa_adm", "jasa_adm_basis_hari", "360"],
  ["jasa_adm", "turunkan_flat_dari_efektif", "false"],
  ["jasa_adm", "rate_efektif_acuan", "0.030000"],
  ["batasan", "plafon_min_pumk", "1000000.00"],
  ["batasan", "plafon_max_pumk", "250000000.00"],
  ["batasan", "tenor_min_bulan", "6"],
  ["batasan", "tenor_max_bulan", "36"],
  ["batasan", "grace_period_max_bulan", "6"],
  ["batasan", "wajib_jaminan_di_atas_plafon", "50000000.00"],
  ["batasan", "maks_pinjaman_aktif_per_mitra", "1"],
  ["batasan", "skor_survey_minimum_lolos", "70"],
  // spec 5.6 akuntansi, the keys THIS module reads.
  ["akuntansi", "metode_pengakuan_jasa_adm", "ACCRUAL"],
  ["akuntansi", "akrual_hanya_untuk_kolektibilitas", '["LANCAR"]'],
  ["akuntansi", "jasa_grace_period", "TIDAK_DIHITUNG"],
  ["akuntansi", "tahun_buku_mulai_bulan", "1"],
  ["akuntansi", "izinkan_reopen_periode", "true"],
  ["akuntansi", "dasar_perhitungan_penyisihan", "OUTSTANDING_POKOK"],
  ["akuntansi", "mode_penyisihan", "RATE_TABLE"],
  ["akuntansi", "penyisihan_min_bulan_histori", "24"],
  ["akuntansi", "kekurangan_penyisihan_hapus_buku", "BEBAN_PERIODE"],
  ["kolektibilitas", "tandai_mitra_bermasalah_saat_macet", "true"],
  ["kas", "izinkan_saldo_kas_negatif", "false"],
];

/**
 * spec 5.1 day bands, seeded PER WORLD so a test can edit one without touching
 * the global rows every other world reads. Values equal the spec defaults
 * because the spec's own tests (8.5 items 1..4) are written in terms of them;
 * that makes them fixture values chosen for legibility, not a claim that these
 * bands are the ones in force.
 */
const RANGE_AWAL: ReadonlyArray<[KelasKolektibilitas, number, number | null]> = [
  ["LANCAR", 0, 30],
  ["KURANG_LANCAR", 31, 180],
  ["DIRAGUKAN", 181, 270],
  ["MACET", 271, null],
];

/**
 * spec 5.2 rates, seeded PER WORLD. DELIBERATELY NOT THE SPEC'S NUMBERS.
 *
 * docs/REGULASI.md finding 3: 0/25/75/100 is not in any regulation currently in
 * force, and audited PUMK statements use collective impairment instead. If this
 * fixture seeded 0.25 and 1.00, an implementation with those two numbers
 * HARDCODED would pass every test in this folder, and the "rates come from
 * config" requirement would be untested precisely where it matters. Distinctive
 * values make that impossible: no plausible hardcoded table contains 0.37 or
 * 0.62, and the MACET rate below 1.00 is also what creates the short-allowance
 * case spec 8.2 never contemplates.
 *
 * Tests read the rate back out of `penyisihan_rate` rather than restating these
 * literals, so changing this table breaks nothing.
 */
const RATE_AWAL: ReadonlyArray<[KelasKolektibilitas, Rate]> = [
  ["LANCAR", "0.000000"],
  ["KURANG_LANCAR", "0.370000"],
  ["DIRAGUKAN", "0.620000"],
  ["MACET", "0.850000"],
];

// ---------------------------------------------------------------------------
// The default akad shape, chosen so no assertion needs a calculator:
// 12.000.000 over 12 months, FLAT 3 percent per year, rounding 0.
// Pokok 1.000.000,00 per row; total jasa 360.000,00, i.e. 30.000,00 per row.
// Every test that needs an exact figure still READS the stored schedule.
// ---------------------------------------------------------------------------

export const POKOK_BAKU: Uang = rp(12_000_000);
export const TENOR_BAKU = 12;
export const RATE_JASA_BAKU = "0.030000";

/**
 * The world's period range: two calendar years, 2026-01 .. 2027-12.
 *
 * Wide enough for the longest history these tests need (a 300-day arrears
 * measured at a 2027 period end still has its first instalment inside 2026),
 * and DELIBERATELY NO WIDER. Every world is a fresh bumn with its own periods,
 * and `bun run db:reset` is not run between files, so a period range is paid
 * for once per world and kept forever. A third year cost 12 more rows per world
 * and bought nothing.
 */
export const TAHUN_AWAL = 2026;
export const TAHUN_AKHIR = 2027;

// ---------------------------------------------------------------------------
// Fixture shapes
// ---------------------------------------------------------------------------

export interface PeriodeFixture {
  id: string;
  tahun: number;
  bulan: number;
  tanggalMulai: string;
  tanggalAkhir: string;
}

export interface OpsiAkad {
  cabangId?: string;
  /**
   * Arrears in whole days at `padaTanggal`. `null` means NO instalment has
   * fallen due yet at that date, i.e. spec 8.5 item 1's "akad tanpa
   * tunggakan"; a number `n` puts the FIRST instalment's due date exactly `n`
   * days before `padaTanggal`, so the oldest unpaid overdue row is row 1 and
   * `hari_tunggakan` is exactly `n`.
   */
  hariTunggakan: number | null;
  /** The period-end date the arrears are measured against. */
  padaTanggal: string;
  pokok?: Uang;
  tenor?: number;
  rate?: Rate;
  /** Date of the PENCAIRAN_PUMK journal. Must be inside an OPEN period. */
  tanggalPencairan?: string;
  /** Leave the akad BELUM_CAIR: no journal, no outstanding, and therefore
   *  OUTSIDE spec 8.1 step 1's population. `cairkan()` activates it later. */
  janganCairkan?: boolean;
}

export interface AkadFixture {
  akadId: string;
  noAkad: string;
  proposalId: string;
  mitraId: string;
  cabangId: string;
  pokok: Uang;
  tenor: number;
  tanggalAkad: string;
  tanggalMulaiAngsuran: string;
  /** null while BELUM_CAIR. */
  jurnalPencairanId: string | null;
}

export interface BarisJadwalDb {
  angsuran_ke: number;
  tanggal_jatuh_tempo: string;
  pokok: string;
  jasa_adm: string;
  total: string;
  status: string;
  pokok_terbayar: string;
  jasa_terbayar: string;
}

export interface SnapshotDb {
  akad_id: string;
  mitra_id: string;
  cabang_id: string;
  periode_id: string;
  tanggal_jatuh_tempo_tertunggak_tertua: string | null;
  hari_tunggakan: number;
  kolektibilitas: KelasKolektibilitas;
  kolektibilitas_periode_lalu: KelasKolektibilitas | null;
  outstanding_pokok: string;
  outstanding_jasa: string;
  tunggakan_pokok: string;
  tunggakan_jasa: string;
  rate_penyisihan: string;
  dasar_perhitungan: string;
  sumber_rate: string;
  nilai_penyisihan: string;
}

export interface PenyisihanDb {
  id: string;
  periode_id: string;
  cabang_id: string;
  saldo_penyisihan_awal: string;
  penyisihan_dibutuhkan: string;
  beban_penyisihan_periode: string;
  jurnal_id: string | null;
  tanggal: string;
}

export interface AkrualDb {
  akad_id: string;
  cabang_id: string;
  kolektibilitas: string;
  jasa_jatuh_tempo_periode: string;
  jasa_diterima_periode: string;
  jasa_diakrual: string;
  jurnal_id: string | null;
}

export interface SaldoAkunDb {
  akun_id: string;
  akun_kode: string;
  cabang_id: string;
  saldo_awal: string;
  mutasi_debit: string;
  mutasi_kredit: string;
  saldo_akhir: string;
}

export interface PanggilanJurnal {
  metode: "postingEvent";
  eventCode: string;
  argumen: unknown;
}

export interface PorterJurnalUji extends PorterJurnalClosing {
  panggilan: PanggilanJurnal[];
  /** Arms the NEXT `postingEvent` for `eventCode` to fail. A double may arm a
   *  collaborator's FAILURE; it never answers in its place. */
  gagalkan(eventCode: string, pesan?: string): void;
  reset(): void;
}

export interface PanggilanAudit {
  aksi: string;
  entitas: string;
  entitasId: string | null;
  hasil: "SUKSES" | "DITOLAK";
  keterangan: string | null;
}

export interface PencatatAuditUji extends PencatatAuditClosing {
  panggilan: PanggilanAudit[];
  reset(): void;
}

export interface DuniaClosing {
  db: PortUji;
  bumnId: string;
  cabangId: string;
  cabangLainId: string;
  sektorId: string;
  akun: Record<KunciAkun, AkunFixture>;

  /** The engine under test, wired the way the composition root wires it. */
  engine: ClosingEngine;
  /** The recording wrapper the engine posts through. */
  jurnal: PorterJurnalUji;
  /** The recording wrapper around the REAL audit service. */
  audit: PencatatAuditUji;
  /** Builds a SECOND engine, e.g. one whose ledger is armed to fail. */
  buatEngine(opsi?: { jurnal?: PorterJurnalClosing; audit?: PencatatAuditClosing }): ClosingEngine;

  jam(): Date;
  /** Moves the injected clock. Every engine in this world reads it live, so a
   *  reversal lands in whichever period this points at. */
  setelJam(iso: string): void;

  userId: {
    maker: string;
    checker: string;
    approver: string;
    auditor: string;
    adminPusat: string;
    adminCabang: string;
    approverLain: string;
  };
  /** Contexts whose `permissions` came from `permissionsForRole`, never a literal. */
  ctx: Record<keyof DuniaClosing["userId"], ClosingContext>;

  // --- periods ------------------------------------------------------------
  periode(tahun: number, bulan: number): PeriodeFixture;
  bacaPeriode(periodeId: string): Promise<{
    id: string;
    status: string;
    closed_by: string | null;
    closed_at: string | null;
    reopened_by: string | null;
    alasan_reopen: string | null;
  }>;
  /**
   * Closes a period with raw SQL, in order, up to but NOT including `sebelum`.
   * These are PRECONDITIONS, not behaviour under test: invariant 6 means the
   * engine cannot close 2026-03 until 2026-01 and 2026-02 are CLOSED, and
   * driving nineteen unrelated periods through the full checklist to reach the
   * one under test would turn a single failure into a cascade and hide which
   * step actually broke. The period under test is always closed by the ENGINE.
   */
  tutupPeriodeSampai(sebelum: PeriodeFixture): Promise<void>;
  /** Closes exactly one period with raw SQL, same reasoning. */
  tutupPeriodeLangsung(periode: PeriodeFixture): Promise<void>;
  /**
   * Runs the three steps spec 8.4 checks 4, 5 and 6 demand, THROUGH THE ENGINE
   * UNDER TEST: kolektibilitas, penyisihan, akrual.
   *
   * Deliberately not raw SQL. These are not preconditions in the sense
   * `tutupPeriodeSampai` is: they are the engine's own outputs, and check 4
   * asks whether the engine ran, not whether a row exists. Writing the rows by
   * hand would let `tutupPeriode` pass a checklist nothing had actually
   * satisfied. The cost is that this helper fails while the engine is
   * unimplemented, which is the correct failure and names the step.
   */
  siapkanTutup(periode: PeriodeFixture, ctx?: ClosingContext): Promise<void>;

  // --- akad, schedule, payments (all through the REAL engines) -------------
  buatAkad(opsi: OpsiAkad): Promise<AkadFixture>;
  /** Posts PENCAIRAN_PUMK through the REAL ledger engine and flips the akad
   *  AKTIF with the outstanding a disbursement leaves. */
  cairkan(akadId: string, tanggalPencairan: string): Promise<string>;
  /** Allocates a deposit through the REAL instalment engine. */
  bayarSetoran(akadId: string, tanggal: string, jumlah: Uang): Promise<HasilAlokasi>;
  /**
   * Writes an akad off through the REAL ledger path, `postingHapusBukuPiutang`.
   *
   * DELIBERATELY NOT `postingEvent("HAPUS_BUKU_PIUTANG", ...)`. That is the
   * spec's own journal and it is defective whenever the allowance is short of
   * the outstanding: it debits the contra-asset for the full amount and drives
   * it into a DEBIT balance, which presents as receivables overstated by
   * exactly the sum that was supposed to leave the balance sheet
   * (docs/REGULASI.md finding 4). The real method consumes
   * `min(allowance, outstanding)` and routes the remainder to
   * `HAPUS_BUKU_KEKURANGAN_PENYISIHAN`.
   *
   * The closing engine never calls this. It exists here so a test can put the
   * ledger into the state a write-off leaves and then ask what the NEXT
   * period's allowance requirement makes of it.
   */
  hapusBukuLewatEngine(
    akadId: string,
    tanggal: string,
  ): Promise<{ dariPenyisihan: Uang; kekurangan: Uang; penyisihanTersedia: Uang; jurnalId: string }>;
  /** Exact total of schedule rows 1..k, read from what was actually stored. */
  totalJadwalSampai(akadId: string, angsuranKe: number): Promise<Uang>;
  /**
   * Exactly what it takes to clear EVERY instalment already due at
   * `padaTanggal`, unpaid parts only.
   *
   * Not the same number as `totalJadwalSampai(k)`, and the difference matters:
   * the allocation order is TUNGGAKAN_JASA, TUNGGAKAN_POKOK, JASA_BERJALAN,
   * POKOK_BERJALAN (spec 5.4), so a deposit worth three instalments first pays
   * the jasa of ALL overdue rows and only then their pokok, leaving the third
   * row SEBAGIAN. Paying this figure is what actually makes `hari_tunggakan`
   * fall to zero, which is what spec 8.5 item 7 needs.
   */
  totalTertunggak(akadId: string, padaTanggal: string): Promise<Uang>;
  bacaJadwal(akadId: string): Promise<BarisJadwalDb[]>;
  bacaAkad(akadId: string): Promise<{
    id: string;
    status: string;
    outstanding_pokok: string;
    outstanding_jasa: string;
  }>;

  // --- journals -----------------------------------------------------------
  /** A DRAFT journal dated inside `tanggal`'s period, for spec 8.4 check 2. */
  buatJurnalDraft(tanggal: string, nilai: Uang): Promise<Jurnal>;
  postingJurnalDraft(jurnalId: string): Promise<Jurnal>;
  /** Posts BEBAN_OPERASIONAL: debit an expense, credit cash. */
  postingBebanOperasional(tanggal: string, nilai: Uang): Promise<Jurnal>;
  /** Posts ALOKASI_DANA_BUMN_PEMBINA: debit cash, credit income. */
  postingAlokasiDana(tanggal: string, nilai: Uang): Promise<Jurnal>;
  /**
   * Forms an allowance through the REAL ledger path, so a test can put a
   * balance on the contra-asset WITHOUT the closing engine.
   *
   * Used to set up the write-off cases: the shortfall only exists when an
   * allowance exists and is smaller than the outstanding, and the closing
   * engine is the thing under test rather than a way of arranging the world.
   */
  postingBebanPenyisihan(tanggal: string, nilai: Uang): Promise<Jurnal>;
  reversalJurnal(jurnalId: string, alasan: string): Promise<Jurnal>;
  jumlahJurnalPeriode(periodeId: string): Promise<number>;
  jurnalPeriode(periodeId: string): Promise<
    Array<{ id: string; no_jurnal: string; jenis: string; status: string; keterangan: string | null }>
  >;

  // --- the two ledger readings that must not be confused ------------------
  /**
   * THE CORRECT ONE. Debit-positive balance of an account up to and including
   * `sampaiTanggal`, read from the SHIPPED view `v_ledger_baris`
   * (`status IN ('POSTED','REVERSED')`). This is what a frozen
   * `saldo_akun_periode` must agree with.
   */
  saldoLedger(akunId: string, sampaiTanggal: string, cabangId?: string): Promise<Uang>;
  /**
   * THE WRONG ONE, on purpose. The same sum with `status = 'POSTED'` alone.
   * Exists so a test can assert the two DIFFER before asserting which one the
   * engine froze; without that, a test that only checked the correct value
   * could pass vacuously on data where both readings agree. See ADR 0010.
   */
  saldoLedgerNaifPostedSaja(akunId: string, sampaiTanggal: string, cabangId?: string): Promise<Uang>;
  /** Whole-ledger `SUM(debit) - SUM(kredit)` for this world, spec 8.4 check 7. */
  selisihLedger(): Promise<Uang>;

  // --- closing outputs, read straight from the tables ---------------------
  bacaSnapshot(periodeId: string): Promise<SnapshotDb[]>;
  jumlahSnapshot(periodeId: string): Promise<number>;
  bacaRunKolektibilitas(periodeId: string): Promise<
    Array<{ id: string; status: string; total_akad_diproses: number; ringkasan_json: unknown }>
  >;
  bacaPenyisihan(periodeId: string): Promise<PenyisihanDb[]>;
  bacaAkrual(periodeId: string): Promise<AkrualDb[]>;
  bacaSaldoAkunPeriode(periodeId: string): Promise<SaldoAkunDb[]>;

  // --- configuration knobs -------------------------------------------------
  setelKonfigurasi(grup: string, kunciKonfig: string, nilai: string): Promise<void>;
  hapusKonfigurasi(grup: string, kunciKonfig: string): Promise<void>;
  bacaKonfigurasi(grup: string, kunciKonfig: string): Promise<string | null>;
  setelRange(kelas: KelasKolektibilitas, hariMin: number, hariMax: number | null): Promise<void>;
  hapusRange(kelas: KelasKolektibilitas): Promise<void>;
  bacaRate(kelas: KelasKolektibilitas): Promise<Rate>;
  setelRate(kelas: KelasKolektibilitas, rate: Rate): Promise<void>;
  hapusRate(kelas: KelasKolektibilitas): Promise<void>;

  // --- reconciliation and sabotage ----------------------------------------
  rekonsiliasi(akadId: string): Promise<{ saldoSubLedger: Uang; saldoBukuBesar: Uang; selisih: Uang }>;
  akadTidakRekonsiliasi(): Promise<Array<{ akad_id: string; selisih: string }>>;
  /**
   * Moves `pumk_akad.outstanding_pokok` WITHOUT a journal, which is the only
   * way to make spec 8.4 check 10 fail. `pumk_akad` is not a ledger table, so
   * this does not defeat invariant 11; it manufactures exactly the divergence
   * between sub-ledger and general ledger the check exists to catch.
   */
  rusakSubLedger(akadId: string, outstandingBaru: Uang): Promise<void>;

  /** Does `tabel.kolom` exist? Used to pin a schema gap as a finding. */
  kolomAda(tabel: string, kolom: string): Promise<boolean>;

  tutup(): Promise<void>;
}

async function satu<T>(db: ClosingTx, sql: string, params: unknown[] = []): Promise<T> {
  const baris = await db.query<T>(sql, params);
  if (baris.length === 0) throw new Error(`fixture: query tidak mengembalikan baris: ${sql}`);
  return baris[0];
}

// ---------------------------------------------------------------------------
// The recording wrappers
// ---------------------------------------------------------------------------

export const PESAN_JURNAL_GAGAL =
  "ledger tidak tersedia (fixture: kegagalan yang di-arm, bukan kegagalan nyata)";

/**
 * A RECORDING WRAPPER around the REAL ledger engine, not a substitute for it.
 * Every successful call is delegated; only a call explicitly armed with
 * `gagalkan` throws, and it throws BEFORE reaching the engine so nothing is
 * half-written. That is the only shape of double this repo allows: arming a
 * collaborator's failure is how a rollback becomes testable, answering in its
 * place is how two production defects once hid behind sixteen green tests.
 */
export function porterJurnalUji(db: ClosingDbPort, jam: () => Date): PorterJurnalUji {
  const { engine } = createJurnalModule({ db, jam });
  const panggilan: PanggilanJurnal[] = [];
  const armed = new Map<string, string>();

  return {
    panggilan,
    gagalkan(eventCode, pesan = PESAN_JURNAL_GAGAL) {
      armed.set(eventCode, pesan);
    },
    reset() {
      panggilan.length = 0;
      armed.clear();
    },
    async postingEvent(eventCode, payload, ctx, tx) {
      panggilan.push({ metode: "postingEvent", eventCode, argumen: payload });
      const pesan = armed.get(eventCode);
      if (pesan) {
        armed.delete(eventCode);
        throw new Error(pesan);
      }
      void tx;
      return engine.postingEvent(eventCode, payload, ctx as JurnalContext);
    },
  };
}

/** A RECORDING WRAPPER around the REAL audit service, same rule. */
export function pencatatAuditUji(db: ClosingDbPort): PencatatAuditUji {
  const service = createAuditService({ db });
  const panggilan: PanggilanAudit[] = [];
  return {
    panggilan,
    reset() {
      panggilan.length = 0;
    },
    async record(entry, runner) {
      panggilan.push({
        aksi: entry.aksi,
        entitas: entry.entitas,
        entitasId: entry.entitasId ?? null,
        hasil: entry.hasil,
        keterangan: entry.keterangan ?? null,
      });
      return service.record(entry, runner);
    },
  };
}

// ---------------------------------------------------------------------------
// The world
// ---------------------------------------------------------------------------

/**
 * Builds a minimal but complete world: one bumn, two branches, monthly OPEN
 * periods for 2026-01 .. 2028-12, the SHIPPED chart of accounts and every
 * SHIPPED event mapping, the SHIPPED RBAC matrix with one user per role, this
 * module's parameter rows scoped to the world's bumn, its own kolektibilitas
 * day bands and allowance rates, and one sektor.
 */
export async function buatDunia(): Promise<DuniaClosing> {
  const db = buatPortDb();

  let sekarang = new Date(`${TAHUN_AWAL}-01-15T04:00:00.000Z`);
  const jam = () => sekarang;

  const bumn = await satu<{ id: string }>(
    db,
    `insert into bumn (kode, nama, tahun_buku_mulai_bulan) values ($1, $2, 1) returning id::text as id`,
    [kunci("BUMN"), "PT Krakatau Steel (fixture closing)"],
  );
  const cabang = await satu<{ id: string }>(
    db,
    `insert into cabang (bumn_id, kode, nama, is_pusat) values ($1, $2, $3, true) returning id::text as id`,
    [bumn.id, kunci("CBG"), "Kantor Pusat (fixture closing)"],
  );
  const cabangLain = await satu<{ id: string }>(
    db,
    `insert into cabang (bumn_id, kode, nama) values ($1, $2, $3) returning id::text as id`,
    [bumn.id, kunci("CBG"), "Cabang B (fixture closing)"],
  );

  async function buatUser(nama: string, cabangId: string): Promise<string> {
    const u = await satu<{ id: string }>(
      db,
      `insert into app_user (cabang_id, nama, email, username, password_hash)
       values ($1, $2, $3, $4, 'x-not-a-real-hash') returning id::text as id`,
      [cabangId, nama, `${kunci("mail")}@example.test`, kunci("user")],
    );
    return u.id;
  }

  const userId = {
    maker: await buatUser("Maker (fixture closing)", cabang.id),
    checker: await buatUser("Checker (fixture closing)", cabang.id),
    approver: await buatUser("Approver (fixture closing)", cabang.id),
    auditor: await buatUser("Auditor (fixture closing)", cabang.id),
    adminPusat: await buatUser("Admin Pusat (fixture closing)", cabang.id),
    adminCabang: await buatUser("Admin Cabang (fixture closing)", cabang.id),
    approverLain: await buatUser("Approver B (fixture closing)", cabangLain.id),
  };

  // The SHIPPED permission catalogue, the six SHIPPED system roles and the
  // SHIPPED grant matrix.
  //
  // THROUGH THE node-postgres ADAPTER ON PURPOSE, not through this world's
  // `bun:sql` port. `seedRbac` reconciles each role's grants with
  // `kode = ANY($2::text[])`, i.e. it binds a JS ARRAY, and driver fact 3 in
  // modules/jurnal/repo.ts applies: `bun:sql` serialises a JS array as a bare
  // comma-joined string, which `text[]` rejects with 22P02 "malformed array
  // literal". node-postgres serialises it correctly. `createDbAdapter` opens no
  // socket on import and shares one lazily-built pool across the whole test
  // process, so this costs no extra connection per world.
  const dbRbac = createDbAdapter();
  await seedRbac(dbRbac);

  const ROLE_UNTUK: Record<keyof typeof userId, string> = {
    maker: "MAKER",
    checker: "CHECKER",
    approver: "APPROVER",
    auditor: "AUDITOR",
    adminPusat: "ADMIN_PUSAT",
    adminCabang: "ADMIN_CABANG",
    approverLain: "APPROVER",
  };
  const izinRole = new Map<string, string[]>();
  for (const kodeRole of new Set(Object.values(ROLE_UNTUK))) {
    izinRole.set(kodeRole, await permissionsForRole(dbRbac, kodeRole));
  }
  for (const [nama, kodeRole] of Object.entries(ROLE_UNTUK)) {
    await db.query(
      `insert into user_role (user_id, role_id)
       select $1, r.id from app_role r where r.kode = $2 and r.deleted_at is null
       on conflict (user_id, role_id) do nothing`,
      [userId[nama as keyof typeof userId], kodeRole],
    );
  }

  // Monthly OPEN periods. 2026-01 is the EARLIEST period of this bumn, which
  // is what makes closing it legal at all: invariant 6 has nothing earlier to
  // complain about.
  // ONE statement, not twenty-four round trips. `generate_series` builds the
  // month windows in Postgres, which is also the only place that agrees with
  // `periode_window_ck` about what the last day of a month is without a second
  // implementation of the calendar in TypeScript.
  const periodeIndeks = new Map<string, PeriodeFixture>();
  const barisPeriode = await db.query<{
    id: string;
    tahun: number;
    bulan: number;
    mulai: string;
    akhir: string;
  }>(
    `insert into periode (bumn_id, tahun, bulan, tanggal_mulai, tanggal_akhir, status)
     select $1,
            extract(year from m)::smallint,
            extract(month from m)::smallint,
            m::date,
            (m + interval '1 month' - interval '1 day')::date,
            'OPEN'
       from generate_series(
              make_date($2::int, 1, 1),
              make_date($3::int, 12, 1),
              interval '1 month') as m
     returning id::text as id, tahun, bulan,
               tanggal_mulai::text as mulai, tanggal_akhir::text as akhir`,
    [bumn.id, TAHUN_AWAL, TAHUN_AKHIR],
  );
  for (const row of barisPeriode) {
    periodeIndeks.set(`${row.tahun}-${row.bulan}`, {
      id: row.id,
      tahun: row.tahun,
      bulan: row.bulan,
      tanggalMulai: row.mulai,
      tanggalAkhir: row.akhir,
    });
  }

  // The SHIPPED COA and every SHIPPED event mapping, by the same code path
  // `bun run db:seed` uses.
  const { akun: akunIdByKode } = await seedCoaDanEventMapping(db, bumn.id, userId.adminPusat);
  const akun = {} as Record<KunciAkun, AkunFixture>;
  for (const [nama, kode] of Object.entries(KODE_AKUN) as Array<[KunciAkun, string]>) {
    const id = akunIdByKode.get(kode);
    if (!id) {
      throw new Error(
        `fixture: akun ${kode} tidak ada setelah seedCoaInti; periksa apps/api/src/seed/coa-inti.ts`,
      );
    }
    akun[nama] = { id, kode };
  }

  // `tipe_data` and `pilihan_json` come from the SHIPPED catalogue, not from a
  // second table typed out here. Two reasons, and the second one is a bug this
  // fixture already caused once:
  //
  //   - a fixture row whose shape disagrees with the catalogue is a fixture
  //     testing its own opinion, and a key absent from the catalogue is a
  //     fixture inventing a parameter, so `entri` throwing is the right answer;
  //   - `konfigurasi.pilihan_json` is queried ELSEWHERE WITHOUT A bumn FILTER
  //     (modules/audit's jsonb-shape test does exactly that, with LIMIT 1 and
  //     no ORDER BY). A bumn-scoped row with a NULL `pilihan_json` therefore
  //     turned somebody else's passing test into a coin flip. Fixture rows are
  //     not invisible to global-scope queries, and this is the fix.
  //
  // `$6::text::jsonb`, NOT `$6::jsonb`: driver fact 1 in modules/jurnal/repo.ts,
  // a jsonb parameter bound from a JS string is stored as a JSON string SCALAR,
  // so `jsonb_typeof` would answer 'string' and `jsonb_array_length` would fail.
  for (const [grup, kunciKonfig, nilai] of KONFIGURASI_AWAL) {
    const entri = KATALOG[`${grup}.${kunciKonfig}`];
    if (!entri) {
      throw new Error(
        `fixture closing: ${grup}.${kunciKonfig} tidak ada di katalog konfigurasi terkirim; ` +
          "fixture tidak boleh mengarang parameter",
      );
    }
    await db.query(
      `insert into konfigurasi
         (bumn_id, grup, kunci, nilai, tipe_data, pilihan_json, deskripsi, perlu_konfirmasi)
       values ($1, $2, $3, $4, $5, $6::text::jsonb, 'fixture closing (spec 5)', true)`,
      [
        bumn.id,
        grup,
        kunciKonfig,
        nilai,
        tipeDataUntuk(entri.bentuk),
        entri.pilihan ? JSON.stringify(entri.pilihan) : null,
      ],
    );
  }
  // The global (bumn_id NULL) capability defaults, from the REAL seed. ON
  // CONFLICT DO NOTHING on a NULLS NOT DISTINCT index, so worlds cannot fight
  // over them.
  await seedKonfigurasiTambahan(db);

  for (const [kelas, hariMin, hariMax] of RANGE_AWAL) {
    await db.query(
      `insert into kolektibilitas_range (bumn_id, kelas_kode, hari_min, hari_max) values ($1, $2, $3, $4)`,
      [bumn.id, kelas, hariMin, hariMax],
    );
  }
  for (const [kelas, rate] of RATE_AWAL) {
    await db.query(
      `insert into penyisihan_rate (bumn_id, kelas_kode, rate, dasar_perhitungan)
       values ($1, $2, $3, 'OUTSTANDING_POKOK')`,
      [bumn.id, kelas, rate],
    );
  }

  const sektor = await satu<{ id: string }>(
    db,
    `insert into sektor_pumk (bumn_id, kode, nama) values ($1, $2, 'Perdagangan (fixture)') returning id::text as id`,
    [bumn.id, kunci("SEK")],
  );

  // The two engines this module drives, wired the way the composition root
  // wires them, and used by the fixture for the preconditions that must be
  // REAL (a generated schedule, a posted disbursement, an allocated deposit).
  const { engine: jurnalEngine } = createJurnalModule({ db, jam });
  const { engine: angsuranEngine } = createAngsuranModule({ db, jurnal: jurnalEngine, jam });

  const porterJurnal = porterJurnalUji(db, jam);
  const porterAudit = pencatatAuditUji(db);

  function ctxUntuk(nama: keyof typeof userId): ClosingContext {
    const kodeRole = ROLE_UNTUK[nama];
    const izin = izinRole.get(kodeRole) ?? [];
    const lintasCabang = kodeRole === "ADMIN_PUSAT" || kodeRole === "AUDITOR";
    const rumah = nama === "approverLain" ? cabangLain.id : cabang.id;
    return {
      userId: userId[nama],
      cabangId: rumah,
      bumnId: bumn.id,
      permissions: izin,
      cabangDalamScope: lintasCabang ? [cabang.id, cabangLain.id] : [rumah],
    };
  }

  const ctx = {
    maker: ctxUntuk("maker"),
    checker: ctxUntuk("checker"),
    approver: ctxUntuk("approver"),
    auditor: ctxUntuk("auditor"),
    adminPusat: ctxUntuk("adminPusat"),
    adminCabang: ctxUntuk("adminCabang"),
    approverLain: ctxUntuk("approverLain"),
  } satisfies Record<keyof typeof userId, ClosingContext>;

  const engine = createClosingEngine({ db, jurnal: porterJurnal, jam, audit: porterAudit });

  // --- helpers -------------------------------------------------------------

  function periode(tahun: number, bulan: number): PeriodeFixture {
    const p = periodeIndeks.get(`${tahun}-${bulan}`);
    if (!p) {
      throw new Error(
        `fixture: periode ${tahun}-${bulan} di luar rentang dunia (${TAHUN_AWAL}-01 .. ${TAHUN_AKHIR}-12)`,
      );
    }
    return p;
  }

  async function tutupPeriodeLangsung(p: PeriodeFixture): Promise<void> {
    await db.query(
      `update periode set status = 'CLOSED', closed_by = $2, closed_at = now() where id = $1`,
      [p.id, userId.approver],
    );
  }

  async function tutupPeriodeSampai(sebelum: PeriodeFixture): Promise<void> {
    const urutan = [...periodeIndeks.values()].sort(
      (a, b) => a.tahun * 12 + a.bulan - (b.tahun * 12 + b.bulan),
    );
    for (const p of urutan) {
      if (p.tahun * 12 + p.bulan >= sebelum.tahun * 12 + sebelum.bulan) break;
      await tutupPeriodeLangsung(p);
    }
  }

  async function cairkan(akadId: string, tanggalPencairan: string): Promise<string> {
    const a = await satu<{
      mitra_id: string;
      cabang_id: string;
      no_akad: string;
      pokok_pinjaman: string;
    }>(
      db,
      `select mitra_id::text as mitra_id, cabang_id::text as cabang_id, no_akad,
              pokok_pinjaman::text as pokok_pinjaman
         from pumk_akad where id = $1`,
      [akadId],
    );
    const jasa = await db.query<{ jasa: string }>(
      `select coalesce(sum(jasa_adm), 0)::numeric(20,2)::text as jasa
         from pumk_jadwal_angsuran
        where akad_id = $1 and is_active_version and deleted_at is null`,
      [akadId],
    );
    // DRIVEN WITH A CONTEXT WHOSE BRANCH MATCHES THE ROW. Admin Pusat is scoped
    // to both branches, so a cross-branch fixture akad does not die in setup
    // with the ledger's own CABANG_DILUAR_SCOPE wearing the costume of the
    // defect under test.
    const jurnal = await jurnalEngine.postingEvent(
      "PENCAIRAN_PUMK",
      {
        cabangId: a.cabang_id,
        tanggalTransaksi: tanggalPencairan,
        nilai: a.pokok_pinjaman,
        keterangan: `Pencairan (fixture) akad ${a.no_akad}`,
        akunKasId: akun.kas.id,
        mitraId: a.mitra_id,
        akadId,
        referensiTipe: null,
        referensiId: null,
      },
      ctx.adminPusat as JurnalContext,
    );
    await db.query(
      `update pumk_akad
          set status = 'AKTIF', outstanding_pokok = $2, outstanding_jasa = $3, updated_by = $4
        where id = $1`,
      [akadId, a.pokok_pinjaman, jasa[0]?.jasa ?? "0.00", userId.maker],
    );
    await db.query(`update mitra set status = 'AKTIF', updated_by = $2 where id = $1`, [
      a.mitra_id,
      userId.maker,
    ]);
    return jurnal.id;
  }

  async function buatAkad(opsi: OpsiAkad): Promise<AkadFixture> {
    const cabangId = opsi.cabangId ?? cabang.id;
    const pokok = opsi.pokok ?? POKOK_BAKU;
    const tenor = opsi.tenor ?? TENOR_BAKU;
    const rate = opsi.rate ?? RATE_JASA_BAKU;

    // The arrears arithmetic, stated once. Row 1's due date IS
    // `tanggal_mulai_angsuran` (modules/angsuran `tanggalJatuhTempo` with
    // grace 0), so putting that date `n` days before the period end makes the
    // oldest unpaid overdue row exactly `n` days late.
    const mulaiAngsuran =
      opsi.hariTunggakan === null
        ? tambahHari(opsi.padaTanggal, 45)
        : tambahHari(opsi.padaTanggal, -opsi.hariTunggakan);
    const tanggalAkad = tambahHari(mulaiAngsuran, -30);
    const jatuhTempoAkhir = tambahBulan(mulaiAngsuran, tenor - 1);

    const kodeMitra = kunci("MTR");
    const mitra = await satu<{ id: string }>(
      db,
      `insert into mitra (cabang_id, kode_mitra, nama_lengkap, nik, sektor_id, status, nama_usaha)
       values ($1, $2, $3, $4, $5, 'CALON', $6) returning id::text as id`,
      [
        cabangId,
        kodeMitra,
        `Mitra ${kodeMitra}`,
        kunci("NIK").replace(/\D/g, "").padEnd(16, "0").slice(0, 16),
        sektor.id,
        `Usaha ${kodeMitra}`,
      ],
    );
    const proposal = await satu<{ id: string }>(
      db,
      `insert into pumk_proposal
         (cabang_id, no_proposal, tanggal_proposal, tanggal_daftar, mitra_id, sektor_id,
          jumlah_diajukan, tenor_diajukan, tujuan_penggunaan, sumber_pengajuan, status,
          created_by, updated_by)
       values ($1, $2, $3, $3, $4, $5, $6, $7, 'Modal kerja (fixture closing)', 'INTERNAL',
               'DICAIRKAN', $8, $8)
       returning id::text as id`,
      [cabangId, kunci("PRP"), tanggalAkad, mitra.id, sektor.id, pokok, tenor, userId.maker],
    );
    const noAkad = kunci("AKD");
    const akad = await satu<{ id: string }>(
      db,
      `insert into pumk_akad
         (proposal_id, mitra_id, cabang_id, no_akad, tanggal_akad, pokok_pinjaman, jasa_adm_rate,
          metode_perhitungan, tenor_bulan, grace_period_bulan, tanggal_mulai_angsuran,
          tanggal_jatuh_tempo_akhir, status, created_by, updated_by)
       values ($1, $2, $3, $4, $5, $6, $7, 'FLAT', $8, 0, $9, $10, 'BELUM_CAIR', $11, $11)
       returning id::text as id`,
      [
        proposal.id,
        mitra.id,
        cabangId,
        noAkad,
        tanggalAkad,
        pokok,
        rate,
        tenor,
        mulaiAngsuran,
        jatuhTempoAkhir,
        userId.maker,
      ],
    );

    // Version 1 through the REAL instalment engine, so the schedule satisfies
    // the DEFERRED total-pokok trigger and the one-active-version index.
    await angsuranEngine.generateJadwal({ akadId: akad.id }, ctx.adminPusat as AngsuranContext);

    let jurnalPencairanId: string | null = null;
    if (!opsi.janganCairkan) {
      const tanggalPencairan = opsi.tanggalPencairan ?? periode(TAHUN_AWAL, 1).tanggalMulai;
      jurnalPencairanId = await cairkan(akad.id, tanggalPencairan);
    }

    return {
      akadId: akad.id,
      noAkad,
      proposalId: proposal.id,
      mitraId: mitra.id,
      cabangId,
      pokok,
      tenor,
      tanggalAkad,
      tanggalMulaiAngsuran: mulaiAngsuran,
      jurnalPencairanId,
    };
  }

  async function saldoDenganPredikat(
    predikat: "LEDGER" | "POSTED_SAJA",
    akunId: string,
    sampaiTanggal: string,
    cabangId?: string,
  ): Promise<Uang> {
    // `coalesce(sum(...), 0)` returns '0', not '0.00'. Cast to numeric(20,2)
    // BEFORE ::text or the value fails POLA_UANG and every equality assertion.
    const sumber =
      predikat === "LEDGER"
        ? `from v_ledger_baris l where l.akun_id = $1 and l.tanggal_transaksi <= $2 and l.bumn_id = $3`
        : `from jurnal_baris b join jurnal j on j.id = b.jurnal_id
            where b.akun_id = $1 and j.tanggal_transaksi <= $2 and j.bumn_id = $3
              and j.status = 'POSTED' and j.deleted_at is null and b.deleted_at is null`;
    const kolom = predikat === "LEDGER" ? "l.debit - l.kredit" : "b.debit - b.kredit";
    const filterCabang =
      cabangId === undefined ? "" : predikat === "LEDGER" ? " and l.cabang_id = $4" : " and j.cabang_id = $4";
    const params: unknown[] = [akunId, sampaiTanggal, bumn.id];
    if (cabangId !== undefined) params.push(cabangId);
    const baris = await satu<{ saldo: string }>(
      db,
      `select coalesce(sum(${kolom}), 0)::numeric(20,2)::text as saldo ${sumber}${filterCabang}`,
      params,
    );
    return baris.saldo;
  }

  return {
    db,
    bumnId: bumn.id,
    cabangId: cabang.id,
    cabangLainId: cabangLain.id,
    sektorId: sektor.id,
    akun,
    engine,
    jurnal: porterJurnal,
    audit: porterAudit,
    buatEngine(opsi = {}) {
      return createClosingEngine({
        db,
        jurnal: opsi.jurnal ?? porterJurnal,
        jam,
        audit: opsi.audit ?? porterAudit,
      });
    },
    jam,
    setelJam(iso) {
      sekarang = new Date(iso.length === 10 ? `${iso}T04:00:00.000Z` : iso);
    },
    userId,
    ctx,

    periode,
    bacaPeriode(periodeId) {
      return satu(
        db,
        `select id::text as id, status, closed_by::text as closed_by, closed_at::text as closed_at,
                reopened_by::text as reopened_by, alasan_reopen
           from periode where id = $1`,
        [periodeId],
      );
    },
    tutupPeriodeSampai,
    tutupPeriodeLangsung,
    async siapkanTutup(p, ctxDipakai = ctx.approver) {
      await engine.jalankanKolektibilitas({ periodeId: p.id }, ctxDipakai);
      await engine.jalankanPenyisihan({ periodeId: p.id }, ctxDipakai);
      await engine.jalankanAkrualJasaAdm({ periodeId: p.id }, ctxDipakai);
    },

    buatAkad,
    cairkan,
    async bayarSetoran(akadId, tanggal, jumlah) {
      return angsuranEngine.alokasikanSetoran(
        {
          akadId,
          tanggal,
          jumlah,
          akunKasId: akun.kas.id,
          noBukti: kunci("BKT"),
        },
        ctx.adminPusat as AngsuranContext,
      );
    },
    async totalJadwalSampai(akadId, angsuranKe) {
      const baris = await satu<{ total: string }>(
        db,
        `select coalesce(sum(total - pokok_terbayar - jasa_terbayar), 0)::numeric(20,2)::text as total
           from pumk_jadwal_angsuran
          where akad_id = $1 and is_active_version and deleted_at is null and angsuran_ke <= $2`,
        [akadId, angsuranKe],
      );
      return baris.total;
    },
    async hapusBukuLewatEngine(akadId, tanggal) {
      const a = await satu<{
        mitra_id: string;
        cabang_id: string;
        no_akad: string;
        outstanding_pokok: string;
      }>(
        db,
        `select mitra_id::text as mitra_id, cabang_id::text as cabang_id, no_akad,
                outstanding_pokok::text as outstanding_pokok
           from pumk_akad where id = $1`,
        [akadId],
      );
      return db.transaction(async (tx) => {
        const hasil = await jurnalEngine.postingHapusBukuPiutang(
          {
            cabangId: a.cabang_id,
            tanggalTransaksi: tanggal,
            outstanding: a.outstanding_pokok,
            mitraId: a.mitra_id,
            akadId,
            keterangan: `Hapus buku (fixture) akad ${a.no_akad}`,
          },
          tx,
          ctx.adminPusat as JurnalContext,
        );
        // The sub-ledger follows the ledger in the same transaction, which is
        // what keeps spec 8.4 check 10 at zero across a write-off.
        await tx.query(
          `update pumk_akad set status = 'HAPUS_BUKU', outstanding_pokok = 0, updated_by = $2
            where id = $1`,
          [akadId, userId.adminPusat],
        );
        return {
          dariPenyisihan: hasil.dariPenyisihan,
          kekurangan: hasil.kekurangan,
          penyisihanTersedia: hasil.penyisihanTersedia,
          jurnalId: hasil.id,
        };
      });
    },
    async totalTertunggak(akadId, padaTanggal) {
      const baris = await satu<{ total: string }>(
        db,
        `select coalesce(sum((pokok - pokok_terbayar) + (jasa_adm - jasa_terbayar)), 0)::numeric(20,2)::text as total
           from pumk_jadwal_angsuran
          where akad_id = $1 and is_active_version and deleted_at is null
            and tanggal_jatuh_tempo <= $2 and status <> 'LUNAS'`,
        [akadId, padaTanggal],
      );
      return baris.total;
    },
    bacaJadwal(akadId) {
      return db.query<BarisJadwalDb>(
        `select angsuran_ke, tanggal_jatuh_tempo::text as tanggal_jatuh_tempo,
                pokok::text as pokok, jasa_adm::text as jasa_adm, total::text as total,
                status, pokok_terbayar::text as pokok_terbayar, jasa_terbayar::text as jasa_terbayar
           from pumk_jadwal_angsuran
          where akad_id = $1 and is_active_version and deleted_at is null
          order by angsuran_ke`,
        [akadId],
      );
    },
    bacaAkad(akadId) {
      return satu(
        db,
        `select id::text as id, status, outstanding_pokok::text as outstanding_pokok,
                outstanding_jasa::text as outstanding_jasa
           from pumk_akad where id = $1`,
        [akadId],
      );
    },

    async buatJurnalDraft(tanggal, nilai) {
      return jurnalEngine.buatJurnal(
        {
          cabangId: cabang.id,
          jenis: "UMUM",
          tanggalTransaksi: tanggal,
          keterangan: "Jurnal umum DRAFT (fixture closing, spec 8.4 butir 2)",
          baris: [
            { akunId: akun.bebanOperasional.id, debit: nilai },
            { akunId: akun.kas.id, kredit: nilai },
          ],
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    async postingJurnalDraft(jurnalId) {
      return jurnalEngine.postingJurnal(jurnalId, ctx.adminPusat as JurnalContext);
    },
    async postingBebanOperasional(tanggal, nilai) {
      return jurnalEngine.postingEvent(
        "BEBAN_OPERASIONAL",
        {
          cabangId: cabang.id,
          tanggalTransaksi: tanggal,
          nilai,
          keterangan: "Beban operasional (fixture closing)",
          akunDebitId: akun.bebanOperasional.id,
          akunKasId: akun.kas.id,
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    async postingAlokasiDana(tanggal, nilai) {
      return jurnalEngine.postingEvent(
        "ALOKASI_DANA_BUMN_PEMBINA",
        {
          cabangId: cabang.id,
          tanggalTransaksi: tanggal,
          nilai,
          keterangan: "Alokasi dana BUMN Pembina (fixture closing)",
          akunKasId: akun.kas.id,
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    async postingBebanPenyisihan(tanggal, nilai) {
      return jurnalEngine.postingEvent(
        "BEBAN_PENYISIHAN",
        {
          cabangId: cabang.id,
          tanggalTransaksi: tanggal,
          nilai,
          keterangan: "Pembentukan penyisihan (fixture closing)",
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    async reversalJurnal(jurnalId, alasan) {
      return jurnalEngine.reversalJurnal(jurnalId, alasan, ctx.adminPusat as JurnalContext);
    },
    async jumlahJurnalPeriode(periodeId) {
      const baris = await satu<{ n: string }>(
        db,
        `select count(*)::text as n from jurnal where periode_id = $1 and deleted_at is null`,
        [periodeId],
      );
      return Number.parseInt(baris.n, 10);
    },
    jurnalPeriode(periodeId) {
      return db.query(
        `select id::text as id, no_jurnal, jenis, status, keterangan
           from jurnal where periode_id = $1 and deleted_at is null order by no_jurnal`,
        [periodeId],
      );
    },

    saldoLedger: (akunId, sampaiTanggal, cabangId) =>
      saldoDenganPredikat("LEDGER", akunId, sampaiTanggal, cabangId),
    saldoLedgerNaifPostedSaja: (akunId, sampaiTanggal, cabangId) =>
      saldoDenganPredikat("POSTED_SAJA", akunId, sampaiTanggal, cabangId),
    async selisihLedger() {
      const baris = await satu<{ selisih: string }>(
        db,
        `select coalesce(sum(l.debit) - sum(l.kredit), 0)::numeric(20,2)::text as selisih
           from v_ledger_baris l where l.bumn_id = $1`,
        [bumn.id],
      );
      return baris.selisih;
    },

    bacaSnapshot(periodeId) {
      return db.query<SnapshotDb>(
        `select akad_id::text as akad_id, mitra_id::text as mitra_id, cabang_id::text as cabang_id,
                periode_id::text as periode_id,
                tanggal_jatuh_tempo_tertunggak_tertua::text as tanggal_jatuh_tempo_tertunggak_tertua,
                hari_tunggakan, kolektibilitas, kolektibilitas_periode_lalu,
                outstanding_pokok::text as outstanding_pokok,
                outstanding_jasa::text as outstanding_jasa,
                tunggakan_pokok::text as tunggakan_pokok,
                tunggakan_jasa::text as tunggakan_jasa,
                rate_penyisihan::text as rate_penyisihan, dasar_perhitungan, sumber_rate,
                nilai_penyisihan::text as nilai_penyisihan
           from kolektibilitas_snapshot
          where periode_id = $1 and deleted_at is null
          order by akad_id`,
        [periodeId],
      );
    },
    async jumlahSnapshot(periodeId) {
      const baris = await satu<{ n: string }>(
        db,
        `select count(*)::text as n from kolektibilitas_snapshot
          where periode_id = $1 and deleted_at is null`,
        [periodeId],
      );
      return Number.parseInt(baris.n, 10);
    },
    bacaRunKolektibilitas(periodeId) {
      return db.query(
        `select id::text as id, status, total_akad_diproses, ringkasan_json
           from closing_kolektibilitas
          where periode_id = $1 and deleted_at is null
          order by tanggal_jalan`,
        [periodeId],
      );
    },
    bacaPenyisihan(periodeId) {
      return db.query<PenyisihanDb>(
        `select id::text as id, periode_id::text as periode_id, cabang_id::text as cabang_id,
                saldo_penyisihan_awal::text as saldo_penyisihan_awal,
                penyisihan_dibutuhkan::text as penyisihan_dibutuhkan,
                beban_penyisihan_periode::text as beban_penyisihan_periode,
                jurnal_id::text as jurnal_id, tanggal::text as tanggal
           from penyisihan_periode
          where periode_id = $1 and deleted_at is null
          order by cabang_id`,
        [periodeId],
      );
    },
    bacaAkrual(periodeId) {
      return db.query<AkrualDb>(
        `select akad_id::text as akad_id, cabang_id::text as cabang_id, kolektibilitas,
                jasa_jatuh_tempo_periode::text as jasa_jatuh_tempo_periode,
                jasa_diterima_periode::text as jasa_diterima_periode,
                jasa_diakrual::text as jasa_diakrual, jurnal_id::text as jurnal_id
           from akrual_jasa_snapshot
          where periode_id = $1 and deleted_at is null
          order by akad_id`,
        [periodeId],
      );
    },
    bacaSaldoAkunPeriode(periodeId) {
      return db.query<SaldoAkunDb>(
        `select s.akun_id::text as akun_id, a.kode as akun_kode, s.cabang_id::text as cabang_id,
                s.saldo_awal::text as saldo_awal, s.mutasi_debit::text as mutasi_debit,
                s.mutasi_kredit::text as mutasi_kredit, s.saldo_akhir::text as saldo_akhir
           from saldo_akun_periode s join akun a on a.id = s.akun_id
          where s.periode_id = $1 and s.deleted_at is null
          order by a.kode, s.cabang_id`,
        [periodeId],
      );
    },

    async setelKonfigurasi(grup, kunciKonfig, nilai) {
      const hasil = await db.query<{ id: string }>(
        `update konfigurasi set nilai = $4, diubah_at = now()
          where bumn_id = $1 and grup = $2 and kunci = $3 and deleted_at is null
          returning id::text as id`,
        [bumn.id, grup, kunciKonfig, nilai],
      );
      if (hasil.length === 0) {
        throw new Error(
          `fixture: konfigurasi ${grup}.${kunciKonfig} tidak ada untuk bumn ini; ` +
            "tambahkan ke KONFIGURASI_AWAL di test-support.ts",
        );
      }
    },
    async hapusKonfigurasi(grup, kunciKonfig) {
      // Soft delete, matching how the Konfigurasi screen removes an override.
      // The bumn-scoped row disappears; the GLOBAL row shipped by
      // migrations/0004 stays, which is exactly the situation an engine must
      // handle without inventing a fallback.
      await db.query(
        `update konfigurasi set deleted_at = now(), deleted_by = $4
          where bumn_id = $1 and grup = $2 and kunci = $3 and deleted_at is null`,
        [bumn.id, grup, kunciKonfig, userId.adminPusat],
      );
    },
    async bacaKonfigurasi(grup, kunciKonfig) {
      const baris = await db.query<{ nilai: string | null }>(
        `select nilai from konfigurasi
          where bumn_id = $1 and grup = $2 and kunci = $3 and deleted_at is null`,
        [bumn.id, grup, kunciKonfig],
      );
      return baris[0]?.nilai ?? null;
    },
    async setelRange(kelas, hariMin, hariMax) {
      await db.query(
        `update kolektibilitas_range set hari_min = $3, hari_max = $4, updated_at = now()
          where bumn_id = $1 and kelas_kode = $2 and deleted_at is null`,
        [bumn.id, kelas, hariMin, hariMax],
      );
    },
    async hapusRange(kelas) {
      await db.query(
        `update kolektibilitas_range set deleted_at = now(), deleted_by = $3
          where bumn_id = $1 and kelas_kode = $2 and deleted_at is null`,
        [bumn.id, kelas, userId.adminPusat],
      );
    },
    async bacaRate(kelas) {
      const baris = await satu<{ rate: string }>(
        db,
        `select rate::text as rate from penyisihan_rate
          where bumn_id = $1 and kelas_kode = $2 and deleted_at is null and aktif`,
        [bumn.id, kelas],
      );
      return baris.rate;
    },
    async setelRate(kelas, rate) {
      await db.query(
        `update penyisihan_rate set rate = $3, updated_at = now()
          where bumn_id = $1 and kelas_kode = $2 and deleted_at is null`,
        [bumn.id, kelas, rate],
      );
    },
    async hapusRate(kelas) {
      await db.query(
        `update penyisihan_rate set deleted_at = now(), deleted_by = $3
          where bumn_id = $1 and kelas_kode = $2 and deleted_at is null`,
        [bumn.id, kelas, userId.adminPusat],
      );
    },

    async rekonsiliasi(akadId) {
      // From the SHIPPED view, not recomputed here, so a test cannot agree
      // with a wrong query it wrote itself.
      const baris = await satu<{
        saldo_sub_ledger: string;
        saldo_buku_besar: string;
        selisih: string;
      }>(
        db,
        `select saldo_sub_ledger::text as saldo_sub_ledger,
                saldo_buku_besar::text as saldo_buku_besar, selisih::text as selisih
           from v_rekonsiliasi_piutang where akad_id = $1`,
        [akadId],
      );
      return {
        saldoSubLedger: baris.saldo_sub_ledger,
        saldoBukuBesar: baris.saldo_buku_besar,
        selisih: baris.selisih,
      };
    },
    akadTidakRekonsiliasi() {
      return db.query(
        `select r.akad_id::text as akad_id, r.selisih::text as selisih
           from v_rekonsiliasi_piutang r
           join cabang c on c.id = r.cabang_id
          where c.bumn_id = $1 and r.selisih <> 0`,
        [bumn.id],
      );
    },
    async rusakSubLedger(akadId, outstandingBaru) {
      await db.query(
        `update pumk_akad set outstanding_pokok = $2, updated_by = $3 where id = $1`,
        [akadId, outstandingBaru, userId.adminPusat],
      );
    },

    async kolomAda(tabel, kolom) {
      const baris = await db.query<{ n: string }>(
        `select count(*)::text as n from information_schema.columns
          where table_schema = 'public' and table_name = $1 and column_name = $2`,
        [tabel, kolom],
      );
      return Number.parseInt(baris[0]?.n ?? "0", 10) > 0;
    },

    tutup: () => db.tutup(),
  };
}

// ---------------------------------------------------------------------------
// Assertions shared by the test files
// ---------------------------------------------------------------------------

/**
 * Fragments that mean a raw driver or trigger string has leaked into a
 * user-facing message. The module must wrap DB failures in `ClosingError` with
 * a clean Indonesian message and keep the raw text in `penyebabDb`.
 */
const POLA_KEBOCORAN_DB =
  /TJSL-[A-Z]{3}-\d{3}|PL\/pgSQL|plpgsql|SQLSTATE|violates|duplicate key|null value in column|relation "|_ck\b|_uq\b|ERROR:|syntax error at/i;

/**
 * Asserts a rejection is the expected DOMAIN error, and that its message is
 * free of DB internals. DELIBERATELY STRICT ABOUT THE TYPE AND THE CODE: the
 * stub in ./service.ts throws a plain `Error`, so this cannot be satisfied by
 * an unimplemented engine, which is the one failure mode a tests-first suite
 * exists to prevent.
 *
 * TAKES A PROMISE OR A THUNK. Prefer the thunk. A method that rejects from a
 * guard clause placed before its first `await`, in a function not declared
 * `async`, throws SYNCHRONOUSLY: the argument expression blows up at the call
 * site and this assertion never runs, so the test fails with a raw stack
 * instead of "expected KODE_X, got KODE_Y". That is exactly how today's stub
 * behaves, and it is a shape a real implementation can reach by accident.
 */
export async function tolakDengan(
  janji: Promise<unknown> | (() => Promise<unknown> | unknown),
  kode: KodeClosing,
): Promise<ClosingError> {
  let ditangkap: unknown;
  try {
    await (typeof janji === "function" ? janji() : janji);
  } catch (e) {
    ditangkap = e;
  }
  if (ditangkap === undefined) {
    throw new Error(`diharapkan ditolak dengan ${kode}, tapi operasi berhasil`);
  }
  expect(ditangkap).toBeInstanceOf(ClosingError);
  const err = ditangkap as ClosingError;
  expect(err.kode).toBe(kode);
  expect(err.message.length).toBeGreaterThan(0);
  expect(err.message).not.toMatch(POLA_KEBOCORAN_DB);
  return err;
}

/** Sanity: every code a test names exists in the contract's catalogue. */
export function kodeAda(kode: KodeClosing): KodeClosing {
  expect(Object.values(KODE_CLOSING)).toContain(kode);
  return kode;
}

/**
 * A prerequisite reason has to be readable by an accountant: spec 16
 * scenario 12 asks for "alasan yang jelas". So it must be non-trivially long,
 * free of driver internals, and free of the raw identifiers a developer would
 * leave behind.
 */
export function alasanTerbaca(alasan: string): void {
  expect(alasan.length).toBeGreaterThan(15);
  expect(alasan).not.toMatch(POLA_KEBOCORAN_DB);
  expect(alasan).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}/i);
  expect(alasan).not.toMatch(/undefined|null|\[object/i);
}
