// Read models for the journal HTTP surface (spec 9.4), and nothing else.
//
// WHY THIS FILE EXISTS SEPARATELY FROM ./service.ts
// `JurnalEngine` is the WRITE surface of spec 6: it creates, edits, verifies,
// posts, cancels and reverses, and every one of its reads is a read INSIDE a
// transaction it is about to write in. The seven screens of spec 9.4 need
// something the engine has no business carrying: the document list an operator
// filters, the DRAFT queue a Checker works through, the POSTED list an Approver
// reverses from, and one document with its lines and their account names. Those
// are projections, not behaviour, so they live here rather than widening an
// engine whose nine test files pin its current shape.
//
// IT FOLLOWS modules/closing/baca.ts AND modules/pumk/baca.ts, and obeys the
// same three rules:
//
// 1. BRANCH SCOPE COMES FROM THE SESSION, NEVER FROM THE REQUEST. Every query
//    below is filtered by the branches the SESSION resolved. The by-id read
//    checks the branch the ROW reports and answers `JURNAL_TIDAK_DITEMUKAN`
//    rather than a scope refusal, for the reason modules/mitra gives about an
//    akad: a 403 there would confirm that the id names a real document in
//    another branch, which is the enumeration branch scope exists to prevent.
//
// 2. IT WRITES NOTHING. Every function here is a SELECT, gated by
//    `jurnal.view`, which every operational role holds and which grants no
//    power to create, verify, post or reverse anything. That is what lets an
//    Auditor open the journal screens (spec 16 scenario 23) with no code that
//    can change a line.
//
// 3. NO SECOND OPINION ABOUT THE LEDGER. Totals are read from the stored
//    `jurnal.total_debit` / `total_kredit`, which migrations/0010's trigger
//    maintains from the lines themselves; nothing here re-sums a journal and
//    nothing here decides whether a line counts. A BALANCE read is
//    `v_ledger_baris`'s job (ADR 0010) and is not this file's business: these
//    are DOCUMENTS, listed by status, including the DRAFTs that are not in the
//    ledger at all.
//
// DRIVER FACTS, the same three ./repo.ts is built around, because this file
// runs on both drivers too: DATE and TIMESTAMPTZ come back as `Date` so every
// one is selected `::text`; `dimensi_json` is read `::text` and parsed here; a
// JS array binds as a comma-joined string, so branch lists are expanded into a
// placeholder list rather than passed to `= any($n::uuid[])`.
import { canonicalPermission } from "../auth/index";
import {
  JurnalError,
  PERMISSION_JURNAL,
  type BarisJurnal,
  type DimensiBaris,
  type JenisJurnal,
  type JurnalContext,
  type JurnalDbPort,
  type StatusJurnal,
  type Uang,
} from "./contract";

export interface JurnalBacaDeps {
  db: JurnalDbPort;
}

// ---------------------------------------------------------------------------
// View shapes
// ---------------------------------------------------------------------------

/**
 * One row of the document list (spec 9.4 "Daftar Jurnal").
 *
 * NAMES, NOT ONLY IDS, for the three people a journal records: who filed it,
 * who verified it and who posted it. "Who posted this" answered with a uuid is
 * answered only for somebody with database access, and that question is the
 * whole reason the list exists.
 *
 * `jalurPosting` is the provenance column ADR 0012 stamps on every row:
 * `ENGINE`, `SEED`, `IMPORT_SALDO_AWAL` or `LEGACY`. A screen that could not
 * see it would present an opening-balance import and an operator's entry as
 * the same kind of document.
 */
export interface RingkasanJurnal {
  id: string;
  noJurnal: string;
  jenis: JenisJurnal;
  tanggalTransaksi: string;
  periodeId: string;
  periodeLabel: string;
  cabangId: string;
  cabangKode: string;
  cabangNama: string;
  keterangan: string | null;
  referensiTipe: string | null;
  referensiId: string | null;
  totalDebit: Uang;
  totalKredit: Uang;
  status: StatusJurnal;
  isAutoGenerated: boolean;
  jalurPosting: string | null;
  reversalOfJurnalId: string | null;
  reversedByJurnalId: string | null;
  dibuatOleh: string | null;
  diverifikasiOleh: string | null;
  verifiedAt: string | null;
  dipostingOleh: string | null;
  postedAt: string | null;
  jumlahBaris: number;
  version: number;
}

/** One line of a journal, with the account it hits named rather than pointed at. */
export interface BarisJurnalTampil extends BarisJurnal {
  akunKode: string;
  akunNama: string;
  mitraNama: string | null;
  akadNo: string | null;
}

/**
 * One document, opened.
 *
 * `pembalik` and `dibalikOleh` are the two ends of ADR 0010's correction pair,
 * resolved to their document numbers: a REVERSED journal must be readable as
 * "still in the ledger, offset by THAT one", and a REVERSAL must name what it
 * offsets. Printing only the uuids would leave the most important fact on the
 * page unreadable.
 */
export interface JurnalTampil extends RingkasanJurnal {
  baris: BarisJurnalTampil[];
  /** The original this journal reverses, when `jenis` is REVERSAL. */
  pembalik: { id: string; noJurnal: string } | null;
  /** The reversing journal that offsets this one, when `status` is REVERSED. */
  dibalikOleh: { id: string; noJurnal: string } | null;
}

export interface FilterJurnal {
  periodeId: string | null;
  cabangId: string | null;
  jenis: JenisJurnal | null;
  status: StatusJurnal | null;
  /** `no_jurnal` or `keterangan`, case-insensitive substring. */
  cari: string | null;
  dariTanggal: string | null;
  sampaiTanggal: string | null;
  /** Manual entries only (`false`), event-generated only (`true`), or both. */
  otomatis: boolean | null;
}

export interface JurnalBaca {
  /** The document list, newest transaction first. Never more than `BATAS_DAFTAR`. */
  daftar(filter: FilterJurnal, ctx: JurnalContext): Promise<RingkasanJurnal[]>;
  /** One document with its lines, or `JURNAL_TIDAK_DITEMUKAN`. */
  detail(id: string, ctx: JurnalContext): Promise<JurnalTampil>;
}

/**
 * The list ceiling, the same 500 modules/pumk's read models use. A journal list
 * is unbounded by nature (a year of a busy branch is tens of thousands of
 * documents) and an endpoint that will serialise all of them on request is a
 * way to make one GET hold a connection and a heap. The filters above are how
 * an operator narrows it; the screen shows the ceiling when it is hit.
 */
export const BATAS_DAFTAR = 500;

// ---------------------------------------------------------------------------
// Guards, mirrored from the engine
// ---------------------------------------------------------------------------

/**
 * Fails closed on an unregistered code, exactly as ./service.ts's `wajibPunya`
 * does and for the same reason: a code the shipped catalogue does not know is a
 * configuration fault, and reporting it as TIDAK_BERWENANG would dress it up as
 * a policy decision and hide it forever.
 *
 * The router already ran `requirePermission`, so this is the second line. It
 * stays because a read model reachable from a later batch job or a fixture must
 * refuse on its own evidence rather than on its caller's good manners.
 */
function wajibIzin(ctx: JurnalContext, kode: string): void {
  const kanonik = canonicalPermission(kode);
  if (!kanonik) {
    throw new JurnalError(
      "TIDAK_BERWENANG",
      `Kewenangan "${kode}" belum terdaftar di katalog izin, jadi tindakan ini ditolak sampai kewenangannya ditambahkan.`,
      { permission: kode },
    );
  }
  if (!ctx.permissions.includes(kanonik)) {
    throw new JurnalError(
      "TIDAK_BERWENANG",
      "Pengguna ini tidak punya wewenang untuk melihat jurnal.",
      { permission: kanonik },
    );
  }
}

function cabangTerlihat(ctx: JurnalContext): string[] {
  return [...new Set<string>([ctx.cabangId, ...(ctx.cabangDalamScope ?? [])])];
}

/** `$3::uuid, $4::uuid, ...`. See the driver note in this file's header. */
function daftarPlaceholder(mulai: number, jumlah: number): string {
  return Array.from({ length: jumlah }, (_, i) => `$${mulai + i}::uuid`).join(", ");
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

interface BarisRingkasan {
  id: string;
  noJurnal: string;
  jenis: JenisJurnal;
  tanggalTransaksi: string;
  periodeId: string;
  tahun: number;
  bulan: number;
  cabangId: string;
  cabangKode: string;
  cabangNama: string;
  keterangan: string | null;
  referensiTipe: string | null;
  referensiId: string | null;
  totalDebit: string;
  totalKredit: string;
  status: StatusJurnal;
  isAutoGenerated: boolean;
  jalurPosting: string | null;
  reversalOfJurnalId: string | null;
  reversedByJurnalId: string | null;
  dibuatOleh: string | null;
  diverifikasiOleh: string | null;
  verifiedAt: string | null;
  dipostingOleh: string | null;
  postedAt: string | null;
  jumlahBaris: string;
  version: number;
}

const KOLOM_RINGKASAN = `
  j.id::text as id, j.no_jurnal as "noJurnal", j.jenis,
  j.tanggal_transaksi::text as "tanggalTransaksi",
  j.periode_id::text as "periodeId", p.tahun::int as tahun, p.bulan::int as bulan,
  j.cabang_id::text as "cabangId", c.kode as "cabangKode", c.nama as "cabangNama",
  j.keterangan,
  j.referensi_tipe as "referensiTipe", j.referensi_id::text as "referensiId",
  j.total_debit::text as "totalDebit", j.total_kredit::text as "totalKredit",
  j.status, j.is_auto_generated as "isAutoGenerated",
  j.jalur_posting::text as "jalurPosting",
  j.reversal_of_jurnal_id::text as "reversalOfJurnalId",
  j.reversed_by_jurnal_id::text as "reversedByJurnalId",
  ub.nama as "dibuatOleh", uv.nama as "diverifikasiOleh",
  j.verified_at::text as "verifiedAt",
  up.nama as "dipostingOleh", j.posted_at::text as "postedAt",
  (select count(*) from jurnal_baris b
    where b.jurnal_id = j.id and b.deleted_at is null)::text as "jumlahBaris",
  j.version::int as version`;

const SUMBER_RINGKASAN = `
  from jurnal j
  join cabang c on c.id = j.cabang_id
  join periode p on p.id = j.periode_id
  left join app_user ub on ub.id = j.created_by
  left join app_user uv on uv.id = j.verified_by
  left join app_user up on up.id = j.posted_by`;

const NAMA_BULAN = [
  "Januari", "Februari", "Maret", "April", "Mei", "Juni",
  "Juli", "Agustus", "September", "Oktober", "November", "Desember",
];

function keRingkasan(row: BarisRingkasan): RingkasanJurnal {
  const { tahun, bulan, jumlahBaris, totalDebit, totalKredit, ...sisa } = row;
  return {
    ...sisa,
    periodeLabel: `${NAMA_BULAN[bulan - 1] ?? bulan} ${tahun}`,
    totalDebit: totalDebit as Uang,
    totalKredit: totalKredit as Uang,
    jumlahBaris: Number(jumlahBaris),
  };
}

export function buatJurnalBaca({ db }: JurnalBacaDeps): JurnalBaca {
  async function daftar(filter: FilterJurnal, ctx: JurnalContext): Promise<RingkasanJurnal[]> {
    wajibIzin(ctx, PERMISSION_JURNAL.LIHAT);
    const cabang = cabangTerlihat(ctx);
    if (cabang.length === 0) return [];

    // A branch NAMED in the filter is a NARROWING, never authority: it is
    // intersected with the session's scope, so asking for another branch's
    // journals returns that branch's rows only when the session already had
    // them.
    const dipilih = filter.cabangId
      ? cabang.filter((id) => id === filter.cabangId)
      : cabang;
    if (dipilih.length === 0) return [];

    const params: unknown[] = [ctx.bumnId];
    const kondisi: string[] = [
      "j.bumn_id = $1::uuid",
      "j.deleted_at is null",
      `j.cabang_id in (${daftarPlaceholder(params.length + 1, dipilih.length)})`,
    ];
    params.push(...dipilih);

    const tambah = (sql: string, nilai: unknown): void => {
      params.push(nilai);
      kondisi.push(sql.replace("$n", `$${params.length}`));
    };
    if (filter.periodeId) tambah("j.periode_id = $n::uuid", filter.periodeId);
    if (filter.jenis) tambah("j.jenis = $n::text", filter.jenis);
    if (filter.status) tambah("j.status = $n::text", filter.status);
    if (filter.dariTanggal) tambah("j.tanggal_transaksi >= $n::date", filter.dariTanggal);
    if (filter.sampaiTanggal) tambah("j.tanggal_transaksi <= $n::date", filter.sampaiTanggal);
    if (filter.otomatis !== null) tambah("j.is_auto_generated = $n::boolean", filter.otomatis);
    if (filter.cari) {
      params.push(filter.cari);
      kondisi.push(
        `(j.no_jurnal ilike '%' || $${params.length} || '%'` +
          ` or j.keterangan ilike '%' || $${params.length} || '%')`,
      );
    }

    const rows = await db.query<BarisRingkasan>(
      `select ${KOLOM_RINGKASAN} ${SUMBER_RINGKASAN}
        where ${kondisi.join(" and ")}
        order by j.tanggal_transaksi desc, j.no_jurnal desc
        limit ${BATAS_DAFTAR}`,
      params,
    );
    return rows.map(keRingkasan);
  }

  async function detail(id: string, ctx: JurnalContext): Promise<JurnalTampil> {
    wajibIzin(ctx, PERMISSION_JURNAL.LIHAT);
    const cabang = cabangTerlihat(ctx);
    // THE ONE ANSWER FOR "NOT YOURS" AND "NOT THERE". The branch filter is part
    // of the SELECT rather than a check after it, so a document in another
    // branch is indistinguishable from a document that does not exist. A 403
    // here would confirm that the id names a real journal somewhere, which is
    // the oracle spec 2 rule 3 exists to close.
    const rows =
      cabang.length === 0
        ? []
        : await db.query<BarisRingkasan>(
            `select ${KOLOM_RINGKASAN} ${SUMBER_RINGKASAN}
              where j.id = $1::uuid and j.bumn_id = $2::uuid and j.deleted_at is null
                and j.cabang_id in (${daftarPlaceholder(3, cabang.length)})`,
            [id, ctx.bumnId, ...cabang],
          );
    const kepala = rows[0];
    if (!kepala) throw new JurnalError("JURNAL_TIDAK_DITEMUKAN", "Jurnal tidak ditemukan.", { id });

    const baris = await db.query<{
      id: string;
      urutan: number;
      akunId: string;
      akunKode: string;
      akunNama: string;
      debit: string;
      kredit: string;
      keterangan: string | null;
      mitraId: string | null;
      mitraNama: string | null;
      akadId: string | null;
      akadNo: string | null;
      dimensi: string | null;
    }>(
      `select b.id::text as id, b.urutan::int as urutan,
              b.akun_id::text as "akunId", a.kode as "akunKode", a.nama as "akunNama",
              b.debit::text as debit, b.kredit::text as kredit, b.keterangan,
              b.mitra_id::text as "mitraId", m.nama_lengkap as "mitraNama",
              b.akad_id::text as "akadId", ak.no_akad as "akadNo",
              b.dimensi_json::text as dimensi
         from jurnal_baris b
         join akun a on a.id = b.akun_id
         left join mitra m on m.id = b.mitra_id
         left join pumk_akad ak on ak.id = b.akad_id
        where b.jurnal_id = $1::uuid and b.deleted_at is null
        order by b.urutan asc`,
      [id],
    );

    const pasangan = await db.query<{ id: string; noJurnal: string; peran: string }>(
      `select j.id::text as id, j.no_jurnal as "noJurnal", 'ASLI' as peran
         from jurnal j where j.id = $1::uuid
       union all
       select j.id::text, j.no_jurnal, 'PEMBALIK'
         from jurnal j where j.id = $2::uuid`,
      [kepala.reversalOfJurnalId, kepala.reversedByJurnalId],
    );

    const asli = pasangan.find((p) => p.peran === "ASLI") ?? null;
    const balik = pasangan.find((p) => p.peran === "PEMBALIK") ?? null;

    return {
      ...keRingkasan(kepala),
      baris: baris.map((b) => ({
        id: b.id,
        urutan: b.urutan,
        akunId: b.akunId,
        akunKode: b.akunKode,
        akunNama: b.akunNama,
        debit: b.debit as Uang,
        kredit: b.kredit as Uang,
        keterangan: b.keterangan,
        mitraId: b.mitraId,
        mitraNama: b.mitraNama,
        akadId: b.akadId,
        akadNo: b.akadNo,
        dimensi: bacaDimensi(b.dimensi),
      })),
      pembalik: asli ? { id: asli.id, noJurnal: asli.noJurnal } : null,
      dibalikOleh: balik ? { id: balik.id, noJurnal: balik.noJurnal } : null,
    };
  }

  return { daftar, detail };
}

/**
 * `dimensi_json` arrives as text (driver fact 1 in ./repo.ts) and is parsed
 * here. A malformed value becomes `{}` rather than a 500: the dimensions are
 * analytic labels, and a screen that cannot open a journal because one line's
 * label is unreadable is worse than a screen that shows the journal without it.
 */
function bacaDimensi(teks: string | null): DimensiBaris {
  if (!teks) return {};
  try {
    const nilai: unknown = JSON.parse(teks);
    return typeof nilai === "object" && nilai !== null && !Array.isArray(nilai)
      ? (nilai as DimensiBaris)
      : {};
  } catch {
    return {};
  }
}
