// The journal HTTP surface, end to end: the document a Maker files, the
// Checker verifies, the Approver posts, and the reversal that is what "Hapus
// Jurnal Transaksi" actually does.
//
// EVERYTHING HERE GOES THROUGH THE SHIPPED APP. A real login, a real session
// cookie, the real guard chain and the app `core/app.ts` assembles for the
// server. The engine's own nine test files already prove the accounting; what
// this file proves is that a PERSON can reach it, that each refusal arrives
// with the code an operator has to act on, and that nothing was written when
// one did.
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import {
  buatDuniaRuteJurnal,
  rp,
  tutupSemuaFixture,
  type DuniaRuteJurnal,
  type JurnalHttp,
} from "./rute-test-support";

let d: DuniaRuteJurnal;
/** Every journal below is dated in this month unless it says otherwise. */
let bulan: { id: string; tanggal: string };

beforeAll(async () => {
  d = await buatDuniaRuteJurnal();
  const p = d.periode.get(3)!;
  bulan = { id: p.id, tanggal: "2026-03-10" };
});

afterAll(async () => {
  await tutupSemuaFixture();
});

describe("POST /jurnal, spec 6.2 dan 9.4", () => {
  test("Maker membuat jurnal umum: 201, lahir DRAFT, bernomor, dan barisnya tersimpan", async () => {
    const res = await d.panggil("MAKER", "/jurnal", {
      body: d.bodyUmum(bulan.tanggal, rp(250_000), "Koreksi biaya rapat Maret"),
    });
    expect(res.status).toBe(201);
    const j = (await res.json()) as JurnalHttp;

    expect(j.status).toBe("DRAFT");
    expect(j.jenis).toBe("UMUM");
    expect(j.periodeId).toBe(bulan.id);
    expect(j.totalDebit).toBe(rp(250_000));
    expect(j.totalKredit).toBe(rp(250_000));
    expect(j.baris).toHaveLength(2);
    // `<JENIS>/<YYYYMM>/<5 digit>`, allocated atomically per (jenis, periode).
    expect(j.noJurnal).toMatch(/^UMUM\/202603\/\d{5}$/);
    // A DRAFT is not in the ledger, and the route cannot put it there.
    expect(await d.statusJurnal(j.id)).toBe("DRAFT");
  });

  test("tidak balance ditolak 400 TIDAK_BALANCE dan tidak ada dokumen yang lahir", async () => {
    const body = d.bodyUmum(bulan.tanggal, rp(100_000));
    (body.baris as Array<Record<string, unknown>>)[1]!.kredit = rp(99_000);
    const ditolak = await d.tolak("MAKER", "/jurnal", { body });
    expect(ditolak.status).toBe(400);
    expect(ditolak.kodeDomain).toBe("TIDAK_BALANCE");
  });

  test("satu baris saja ditolak MINIMAL_DUA_BARIS, aturan mesin bukan aturan rute", async () => {
    const body = d.bodyUmum(bulan.tanggal, rp(100_000));
    (body.baris as unknown[]).pop();
    expect((await d.tolak("MAKER", "/jurnal", { body })).kodeDomain).toBe("MINIMAL_DUA_BARIS");
  });

  test("tanggal di periode CLOSED ditolak 409 PERIODE_TIDAK_OPEN", async () => {
    const januari = d.periode.get(1)!;
    await d.tutupPeriodeLangsung(januari.id);
    const ditolak = await d.tolak("MAKER", "/jurnal", {
      body: d.bodyUmum("2026-01-15", rp(50_000)),
    });
    expect(ditolak.status).toBe(409);
    expect(ditolak.kodeDomain).toBe("PERIODE_TIDAK_OPEN");
    // The sentence an operator acts on, not a trigger code.
    expect(ditolak.error).toContain("periode");
    expect(ditolak.error).not.toContain("TJSL-");
  });

  test("VALIDASI di batas: setiap field yang salah dilaporkan sekaligus, bukan yang pertama saja", async () => {
    const ditolak = await d.tolak("MAKER", "/jurnal", {
      body: {
        cabangId: "bukan-uuid",
        jenis: "UMUM",
        tanggalTransaksi: "2026-02-30",
        baris: [{ akunId: d.akunBebanId, debit: 250000 }],
      },
    });
    expect(ditolak.status).toBe(400);
    expect(ditolak.kodeDomain).toBe("VALIDASI");
    const detail = ditolak.detail as Record<string, string[]>;
    expect(Object.keys(detail).sort()).toEqual([
      "baris.0.debit",
      "cabangId",
      "tanggalTransaksi",
    ]);
    // 2026-02-30 matches the pattern and is not a day. Letting it through would
    // produce a period lookup that finds nothing and blame the period.
    expect(detail.tanggalTransaksi![0]).toContain("YYYY-MM-DD");
    // A JSON number is refused rather than stringified: an IEEE-754 double is
    // exactly what invariant 7 keeps out of the ledger.
    expect(detail["baris.0.debit"]![0]).toContain("angka JSON");
  });

  test("jenis yang hanya mesin yang boleh menerbitkan ditolak di pintu", async () => {
    for (const jenis of ["REVERSAL", "CLOSING", "PENYISIHAN", "SALDO_AWAL", "OTOMATIS"]) {
      const body = { ...d.bodyUmum(bulan.tanggal, rp(10_000)), jenis };
      const ditolak = await d.tolak("MAKER", "/jurnal", { body });
      expect([jenis, ditolak.status, ditolak.kodeDomain]).toEqual([jenis, 400, "VALIDASI"]);
    }
  });

  test("referensiTipe, kunciIdempotensi dan isAutoGenerated DITOLAK, bukan diabaikan diam diam", async () => {
    for (const field of ["referensiTipe", "kunciIdempotensi", "isAutoGenerated"]) {
      const body = { ...d.bodyUmum(bulan.tanggal, rp(10_000)), [field]: "pumk_angsuran" };
      const ditolak = await d.tolak("MAKER", "/jurnal", { body });
      const detail = ditolak.detail as Record<string, string[]>;
      // Silently dropping it would hide the fact that a hand-typed journal was
      // about to claim a business document it has nothing to do with.
      expect([field, Object.keys(detail)]).toEqual([field, [field]]);
    }
  });
});

describe("PUT /jurnal/:id dan POST /jurnal/:id/batal", () => {
  test("edit DRAFT: version naik, baris diganti seluruhnya, nomor dan jenis tidak berubah", async () => {
    const dibuat = await d.ok<JurnalHttp>("MAKER", "/jurnal", {
      body: d.bodyUmum(bulan.tanggal, rp(300_000), "Sebelum koreksi"),
    });
    const diubah = await d.ok<JurnalHttp>("MAKER", `/jurnal/${dibuat.id}`, {
      method: "PUT",
      body: d.bodyUmum(bulan.tanggal, rp(310_000), "Sesudah koreksi"),
    });
    expect(diubah.version).toBeGreaterThan(dibuat.version);
    expect(diubah.totalDebit).toBe(rp(310_000));
    expect(diubah.keterangan).toBe("Sesudah koreksi");
    // Immutable across an edit: `no_jurnal` is allocated per (jenis, periode),
    // so a type change would leave the number lying about the document.
    expect(diubah.noJurnal).toBe(dibuat.noJurnal);
    expect(diubah.jenis).toBe("UMUM");
    // Replaced, not appended: two lines before, two lines after.
    expect(await d.jumlahBaris(dibuat.id)).toBe(2);
  });

  test("batal DRAFT adalah soft delete, dan sesudahnya dokumennya tidak bisa dibuka lagi", async () => {
    const dibuat = await d.ok<JurnalHttp>("MAKER", "/jurnal", {
      body: d.bodyUmum(bulan.tanggal, rp(120_000), "Salah input, dibatalkan"),
    });
    const dibatalkan = await d.ok<{ id: string; dibatalkan: boolean }>(
      "MAKER",
      `/jurnal/${dibuat.id}/batal`,
      { body: {} },
    );
    expect(dibatalkan.dibatalkan).toBe(true);
    // The row stays, so the attempt is still in the database and in the audit
    // log; it is simply out of every read.
    expect(await d.statusJurnal(dibuat.id)).toBe("DRAFT+DELETED");
    expect((await d.tolak("MAKER", `/jurnal/${dibuat.id}`)).status).toBe(404);
  });
});

describe("verifikasi, posting, dan yang tidak boleh terjadi sesudah posting", () => {
  test("Checker memverifikasi, Approver memposting, dan jurnalnya masuk ledger", async () => {
    const dibuat = await d.ok<JurnalHttp>("MAKER", "/jurnal", {
      body: d.bodyUmum(bulan.tanggal, rp(400_000), "Jurnal umum yang akan diposting"),
    });

    // Spec 2 rule 1, refused rather than hidden: the author cannot verify.
    const sendiri = await d.tolak("MAKER", `/jurnal/${dibuat.id}/verifikasi`, { body: {} });
    expect(sendiri.status).toBe(403);

    const diverifikasi = await d.ok<JurnalHttp>("CHECKER", `/jurnal/${dibuat.id}/verifikasi`, {
      body: {},
    });
    expect(diverifikasi.status).toBe("DRAFT");
    expect(await d.statusJurnal(dibuat.id)).toBe("DRAFT");

    const diposting = await d.ok<JurnalHttp>("APPROVER", `/jurnal/${dibuat.id}/posting`, {
      body: {},
    });
    expect(diposting.status).toBe("POSTED");
    expect(await d.statusJurnal(dibuat.id)).toBe("POSTED");
  });

  test("jurnal POSTED tidak bisa diedit, tidak bisa dibatalkan, dan tidak bisa diposting dua kali", async () => {
    const j = await postedBaru("Jurnal POSTED yang dijaga");

    const diedit = await d.tolak("MAKER", `/jurnal/${j.id}`, {
      method: "PUT",
      body: d.bodyUmum(bulan.tanggal, rp(999_000)),
    });
    expect([diedit.status, diedit.kodeDomain]).toEqual([409, "JURNAL_TIDAK_DRAFT"]);

    const dibatalkan = await d.tolak("MAKER", `/jurnal/${j.id}/batal`, { body: {} });
    expect([dibatalkan.status, dibatalkan.kodeDomain]).toEqual([409, "JURNAL_TIDAK_DRAFT"]);

    const diposting = await d.tolak("APPROVER", `/jurnal/${j.id}/posting`, { body: {} });
    expect(diposting.kodeDomain).toBe("JURNAL_TIDAK_DRAFT");

    // And after all three refusals the document is untouched.
    expect(await d.statusJurnal(j.id)).toBe("POSTED");
    const dibaca = await d.ok<JurnalHttp>("AUDITOR", `/jurnal/${j.id}`);
    expect(dibaca.totalDebit).toBe(j.totalDebit);
    expect(dibaca.version).toBe(j.version);
  });

  test("posting batch gagal seluruhnya kalau satu anggotanya tidak sah", async () => {
    const a = await d.ok<JurnalHttp>("MAKER", "/jurnal", {
      body: d.bodyUmum(bulan.tanggal, rp(55_000), "Batch anggota sah"),
    });
    const b = await postedBaru("Batch anggota yang sudah POSTED");

    const ditolak = await d.tolak("APPROVER", "/jurnal/posting-batch", {
      body: { ids: [a.id, b.id] },
    });
    expect([ditolak.status, ditolak.kodeDomain]).toEqual([409, "BATCH_GAGAL"]);
    // "Semua atau tidak ada": the valid member is still a DRAFT.
    expect(await d.statusJurnal(a.id)).toBe("DRAFT");
  });
});

describe("POST /jurnal/:id/pembalik: spec 9.4 'Hapus Jurnal Transaksi', spec 16 skenario 10", () => {
  test("yang terjadi adalah jurnal PEMBALIK, bukan penghapusan, dan aslinya tetap di ledger", async () => {
    const asli = await postedBaru("Jurnal yang akan dibalik");

    const res = await d.panggil("APPROVER", `/jurnal/${asli.id}/pembalik`, {
      body: { alasan: "Salah akun beban, dikoreksi lewat pembalik" },
    });
    // 201: a document EXISTS afterwards that did not before. A 200 would read
    // as "the delete succeeded", which is the misunderstanding the whole design
    // exists to prevent.
    expect(res.status).toBe(201);
    const pembalik = (await res.json()) as JurnalHttp;

    expect(pembalik.jenis).toBe("REVERSAL");
    expect(pembalik.status).toBe("POSTED");
    expect(pembalik.reversalOfJurnalId).toBe(asli.id);
    expect(pembalik.keterangan).toContain(asli.noJurnal);
    // Sides swapped line for line, same amounts to the sen.
    expect(pembalik.totalDebit).toBe(asli.totalDebit);
    expect(pembalik.totalKredit).toBe(asli.totalKredit);
    const beban = pembalik.baris.find((b) => b.akunId === d.akunBebanId)!;
    expect([beban.debit, beban.kredit]).toEqual([rp(0), asli.totalDebit]);

    // ADR 0010: the original STAYS, marked REVERSED. Two rows added, none
    // removed, and `v_ledger_baris` counts both.
    expect(await d.statusJurnal(asli.id)).toBe("REVERSED");
    const dibaca = await d.ok<JurnalHttp & { dibalikOleh: { noJurnal: string } | null }>(
      "AUDITOR",
      `/jurnal/${asli.id}`,
    );
    expect(dibaca.status).toBe("REVERSED");
    expect(dibaca.dibalikOleh?.noJurnal).toBe(pembalik.noJurnal);
  });

  test("membalik dua kali ditolak 409 JURNAL_SUDAH_REVERSED", async () => {
    const asli = await postedBaru("Jurnal yang hanya boleh dibalik sekali");
    await d.ok("APPROVER", `/jurnal/${asli.id}/pembalik`, {
      body: { alasan: "Pembalikan pertama, yang sah" },
    });
    const kedua = await d.tolak("APPROVER", `/jurnal/${asli.id}/pembalik`, {
      body: { alasan: "Pembalikan kedua, yang harus ditolak" },
    });
    expect([kedua.status, kedua.kodeDomain]).toEqual([409, "JURNAL_SUDAH_REVERSED"]);
  });

  test("DRAFT tidak dibalik, DRAFT dibatalkan: JURNAL_BELUM_POSTED", async () => {
    const draft = await d.ok<JurnalHttp>("MAKER", "/jurnal", {
      body: d.bodyUmum(bulan.tanggal, rp(75_000), "Masih DRAFT"),
    });
    const ditolak = await d.tolak("APPROVER", `/jurnal/${draft.id}/pembalik`, {
      body: { alasan: "Percobaan membalik dokumen yang belum diposting" },
    });
    expect([ditolak.status, ditolak.kodeDomain]).toEqual([409, "JURNAL_BELUM_POSTED"]);
  });

  test("alasan kosong atau sekadar satu huruf ditolak di batas, bukan diterima sebagai alasan", async () => {
    const asli = await postedBaru("Jurnal untuk uji alasan");
    for (const alasan of [undefined, "", "   ", "x"]) {
      const ditolak = await d.tolak("APPROVER", `/jurnal/${asli.id}/pembalik`, {
        body: alasan === undefined ? {} : { alasan },
      });
      expect([String(alasan), ditolak.status, ditolak.kodeDomain]).toEqual([
        String(alasan),
        400,
        "VALIDASI",
      ]);
    }
    // Nothing was reversed by any of the four attempts.
    expect(await d.statusJurnal(asli.id)).toBe("POSTED");
  });
});

describe("GET /jurnal: daftar dan detail", () => {
  test("daftar menyaring per status, per jenis dan per nomor dokumen", async () => {
    const draft = await d.ok<JurnalHttp>("MAKER", "/jurnal", {
      body: d.bodyUmum(bulan.tanggal, rp(11_000), "Draft yang harus muncul di antrean"),
    });

    const semua = await d.ok<{ data: Array<{ id: string; status: string }> }>(
      "AUDITOR",
      "/jurnal?status=DRAFT",
    );
    expect(semua.data.every((j) => j.status === "DRAFT")).toBe(true);
    expect(semua.data.map((j) => j.id)).toContain(draft.id);

    const posted = await d.ok<{ data: Array<{ id: string; status: string }> }>(
      "AUDITOR",
      "/jurnal?status=POSTED",
    );
    expect(posted.data.every((j) => j.status === "POSTED")).toBe(true);
    expect(posted.data.map((j) => j.id)).not.toContain(draft.id);

    const perNomor = await d.ok<{ data: Array<{ noJurnal: string }> }>(
      "AUDITOR",
      `/jurnal?cari=${encodeURIComponent(draft.noJurnal)}`,
    );
    expect(perNomor.data.map((j) => j.noJurnal)).toEqual([draft.noJurnal]);

    const perJenis = await d.ok<{ data: Array<{ jenis: string }> }>(
      "AUDITOR",
      "/jurnal?jenis=REVERSAL",
    );
    expect(perJenis.data.every((j) => j.jenis === "REVERSAL")).toBe(true);
  });

  test("detail menyebut nama akun, nama pembuatnya, dan pasangan pembaliknya", async () => {
    const asli = await postedBaru("Jurnal yang detailnya dibaca");
    const detail = await d.ok<{
      noJurnal: string;
      dibuatOleh: string | null;
      dipostingOleh: string | null;
      jumlahBaris: number;
      periodeLabel: string;
      baris: Array<{ akunKode: string; akunNama: string }>;
    }>("AUDITOR", `/jurnal/${asli.id}`);

    expect(detail.noJurnal).toBe(asli.noJurnal);
    // Names, not uuids: "who posted this" answered with a uuid is answered only
    // for somebody with database access.
    expect(detail.dibuatOleh).toContain("MAKER");
    expect(detail.dipostingOleh).toContain("APPROVER");
    expect(detail.jumlahBaris).toBe(2);
    expect(detail.periodeLabel).toBe("Maret 2026");
    expect(detail.baris.map((b) => b.akunKode).sort()).toEqual(["1.1.01", "5.1.04"]);
    expect(detail.baris.every((b) => b.akunNama.length > 0)).toBe(true);
  });

  test("id yang bukan UUID adalah 400 di batas, id yang tidak ada adalah 404", async () => {
    expect((await d.tolak("AUDITOR", "/jurnal/umum")).status).toBe(400);
    expect((await d.tolak("AUDITOR", `/jurnal/${crypto.randomUUID()}`)).status).toBe(404);
    // The router's own 404 envelope, not Hono's plain text.
    const hilang = await d.tolak("AUDITOR", "/jurnal/tidak/ada/di/sini");
    expect([hilang.status, hilang.kodeDomain]).toEqual([404, "TIDAK_DITEMUKAN"]);
  });
});

/** A POSTED journal through the three real routes, as three real roles. */
async function postedBaru(keterangan: string): Promise<JurnalHttp> {
  const dibuat = await d.ok<JurnalHttp>("MAKER", "/jurnal", {
    body: d.bodyUmum(bulan.tanggal, rp(200_000), keterangan),
  });
  await d.ok("CHECKER", `/jurnal/${dibuat.id}/verifikasi`, { body: {} });
  return d.ok<JurnalHttp>("APPROVER", `/jurnal/${dibuat.id}/posting`, { body: {} });
}
