// Combined event posting (spec 7.2 step 8), the audit trail, and the DRIVER
// the server actually runs on.
//
// WHY THIS FILE EXISTS SEPARATELY FROM THE OTHER SEVEN
// The engine tests written first all construct the engine from `bun:sql`,
// because that is what test-support.ts builds the port from. That left the
// production path, node-postgres through core/adapters/db.ts, with no coverage
// at all, and the two drivers do not agree on where they put a SQLSTATE
// (`errno` vs `code`). A whole branch of ./kesalahan.ts was therefore dead in
// production while every test stayed green. The last describe block closes
// that: it drives the SAME engine through `createDbAdapter()`, and one test
// pins the SQLSTATE reader against both driver error shapes directly.
//
// WHAT IS DELIBERATELY NOT ASSERTED HERE
// A component contributes a debit AND a credit of its own value, so an
// assembled combined journal cannot be unbalanced by any input a caller can
// express. The balance gate is asserted anyway (the engine runs the same spec
// 6.2 check over the merged lines), and what IS tested below is the thing that
// would actually break: that a balance refusal ARRIVING ON THIS PATH becomes a
// clean domain error inside the call, rather than raw trigger text at a COMMIT
// this module does not own. Writing a fake "unbalanced components" case would
// be asserting against a shape the API cannot produce.
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { createAuditService } from "../audit";
import { canonicalPermission, ROLE_CODES } from "../auth";
import { createDbAdapter } from "../../core/adapters/db";
import { permissionsForRole, seedRbac } from "../../seed/rbac";
import {
  createJurnalEngine,
  JurnalError,
  KODE_JURNAL,
  PERMISSION_JURNAL,
  POLA_NO_JURNAL,
  type JurnalDbPort,
  type JurnalEngine,
  type JurnalTx,
  type KomponenEvent,
} from "./contract";
import { terjemahkanKesalahanDb } from "./kesalahan";
import {
  bacaBarisDb,
  bacaJurnalDb,
  buatDunia,
  kunci,
  rp,
  selisihLedger,
  tolakDengan,
  type DuniaJurnal,
} from "./test-support";

let d: DuniaJurnal;
let engine: JurnalEngine;

beforeAll(async () => {
  d = await buatDunia();
  engine = createJurnalEngine({ db: d.db, jam: d.jam });
});

afterAll(async () => {
  if (d) await d.tutup();
});

/** The three components of a deposit allocation, spec 7.2's own example. */
function komponenSetoran(
  pokok: string,
  jasa: string,
  kelebihan?: string,
): KomponenEvent[] {
  const daftar: KomponenEvent[] = [
    { eventCode: "ANGSURAN_POKOK", nilai: pokok, mitraId: d.mitraId, akadId: d.akadId },
    { eventCode: "ANGSURAN_JASA_ADM", nilai: jasa },
  ];
  if (kelebihan) daftar.push({ eventCode: "TERIMA_KELEBIHAN_ANGSURAN", nilai: kelebihan });
  return daftar;
}

describe("spec 7.2 step 8 postingEventGabungan: beberapa event, satu jurnal", () => {
  test("tiga komponen menjadi SATU jurnal dengan empat baris, bukan tiga jurnal", async () => {
    const sebelum = await d.db.query<{ n: number }>(
      `select count(*)::int as n from jurnal where bumn_id = $1`,
      [d.bumnId],
    );

    const hasil = await d.db.transaction((tx) =>
      engine.postingEventGabungan(
        {
          cabangId: d.cabangId,
          tanggalTransaksi: d.tanggalKini,
          komponen: komponenSetoran(rp(1_000_000), rp(100_000), rp(50_000)),
          keterangan: "alokasi setoran 1.150.000",
          referensiTipe: "pumk_angsuran",
          referensiId: d.akadId,
        },
        tx,
        d.ctx.maker,
      ),
    );

    // Exactly one journal, for three components.
    const sesudah = await d.db.query<{ n: number }>(
      `select count(*)::int as n from jurnal where bumn_id = $1`,
      [d.bumnId],
    );
    expect(sesudah[0].n - sebelum[0].n).toBe(1);

    expect(hasil.status).toBe("POSTED");
    expect(hasil.isAutoGenerated).toBe(true);
    expect(hasil.noJurnal).toMatch(POLA_NO_JURNAL);
    // The convenience fields the business modules read must never disagree
    // with the journal they came from.
    expect(hasil.jurnalId).toBe(hasil.id);
    expect(hasil.jumlahBaris).toBe(hasil.baris.length);

    // One deposit is one cash movement: the three cash legs merge, so the
    // journal is N + 1 lines, not 2N.
    expect(hasil.jumlahBaris).toBe(4);
    const baris = await bacaBarisDb(d.db, hasil.id);
    expect(baris).toHaveLength(4);

    const kas = baris.filter((b) => b.akun_id === d.akun.kas.id);
    expect(kas).toHaveLength(1);
    expect(kas[0].debit).toBe(rp(1_150_000));

    const kredit = new Map(
      baris.filter((b) => b.kredit !== rp(0)).map((b) => [b.akun_id, b.kredit]),
    );
    expect(kredit.get(d.akun.piutangPokok.id)).toBe(rp(1_000_000));
    expect(kredit.get(d.akun.pendapatanJasaAdm.id)).toBe(rp(100_000));
    expect(kredit.get(d.akun.kelebihanAngsuran.id)).toBe(rp(50_000));

    expect(hasil.totalDebit).toBe(rp(1_150_000));
    expect(hasil.totalKredit).toBe(rp(1_150_000));
    expect(await selisihLedger(d.db)).toBe("0.00");
  });

  test("dimensi sub ledger hanya di kaki piutang, tidak di kaki kas", async () => {
    // The rule the whole piutang reconciliation rests on. On the cash leg as
    // well, v_rekonsiliasi_piutang would net every component to zero per akad
    // and report a permanent false balance.
    const hasil = await d.db.transaction((tx) =>
      engine.postingEventGabungan(
        {
          cabangId: d.cabangId,
          tanggalTransaksi: d.tanggalKini,
          komponen: komponenSetoran(rp(700_000), rp(70_000)),
        },
        tx,
        d.ctx.maker,
      ),
    );

    const baris = await bacaBarisDb(d.db, hasil.id);
    const piutang = baris.find((b) => b.akun_id === d.akun.piutangPokok.id);
    expect(piutang?.akad_id).toBe(d.akadId);
    expect(piutang?.mitra_id).toBe(d.mitraId);
    for (const b of baris.filter((x) => x.akun_id !== d.akun.piutangPokok.id)) {
      expect(b.akad_id).toBeNull();
      expect(b.mitra_id).toBeNull();
    }
  });

  test("satu komponen tetap satu jurnal, dua baris", async () => {
    const hasil = await d.db.transaction((tx) =>
      engine.postingEventGabungan(
        {
          cabangId: d.cabangId,
          tanggalTransaksi: d.tanggalKini,
          komponen: [
            { eventCode: "ANGSURAN_POKOK", nilai: rp(250_000), mitraId: d.mitraId, akadId: d.akadId },
          ],
        },
        tx,
        d.ctx.maker,
      ),
    );
    expect(hasil.jumlahBaris).toBe(2);
    expect(hasil.status).toBe("POSTED");
  });

  test("akun kas dari form menimpa kaki kas SETIAP komponen, kaki non kas tetap dari mapping", async () => {
    const hasil = await d.db.transaction((tx) =>
      engine.postingEventGabungan(
        {
          cabangId: d.cabangId,
          tanggalTransaksi: d.tanggalKini,
          komponen: komponenSetoran(rp(300_000), rp(30_000)),
          akunKasId: d.akun.kasKedua.id,
        },
        tx,
        d.ctx.maker,
      ),
    );
    const baris = await bacaBarisDb(d.db, hasil.id);
    // Still ONE cash line: the override applies to every component, so the
    // legs still agree and still merge.
    const kas = baris.filter((b) => b.akun_id === d.akun.kasKedua.id);
    expect(kas).toHaveLength(1);
    expect(kas[0].debit).toBe(rp(330_000));
    expect(baris.some((b) => b.akun_id === d.akun.kas.id)).toBe(false);
    expect(baris.some((b) => b.akun_id === d.akun.piutangPokok.id)).toBe(true);
  });

  test("akun setiap komponen dibaca dari event_jurnal_mapping, ikut perubahan barisnya tanpa redeploy", async () => {
    await d.gantiAkunMapping("ANGSURAN_POKOK", "akun_kredit_id", d.akun.piutangAlternatif.id);
    try {
      const hasil = await d.db.transaction((tx) =>
        engine.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: d.tanggalKini,
            // No sub-ledger dimension: the receivable account for the piutang
            // dimension is defined by PENCAIRAN_PUMK, and this test repoints
            // ANGSURAN_POKOK only, so tagging would (correctly) be refused.
            komponen: [
              { eventCode: "ANGSURAN_POKOK", nilai: rp(400_000) },
              { eventCode: "ANGSURAN_JASA_ADM", nilai: rp(40_000) },
            ],
          },
          tx,
          d.ctx.maker,
        ),
      );
      const baris = await bacaBarisDb(d.db, hasil.id);
      expect(baris.some((b) => b.akun_id === d.akun.piutangAlternatif.id)).toBe(true);
      expect(baris.some((b) => b.akun_id === d.akun.piutangPokok.id)).toBe(false);
    } finally {
      await d.gantiAkunMapping("ANGSURAN_POKOK", "akun_kredit_id", d.akun.piutangPokok.id);
    }
  });

  test("event tanpa baris mapping aktif menolak seluruh gabungan", async () => {
    await tolakDengan(
      d.db.transaction((tx) =>
        engine.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: d.tanggalKini,
            komponen: [
              { eventCode: "ANGSURAN_POKOK", nilai: rp(100_000) },
              { eventCode: "EVENT_YANG_TIDAK_PERNAH_ADA", nilai: rp(100_000) },
            ],
          },
          tx,
          d.ctx.maker,
        ),
      ),
      KODE_JURNAL.EVENT_MAPPING_TIDAK_DITEMUKAN,
    );
  });

  test("komponen yang hanya bisa menyuplai satu kaki ditolak, karena tidak bisa jadi jurnal balance", async () => {
    // PENYALURAN_NON_PUMK resolves its debit leg at runtime. Without that
    // account the component has one leg, and a one-legged component cannot be
    // part of a balanced journal, so the whole combined posting is refused
    // before anything is assembled.
    await tolakDengan(
      d.db.transaction((tx) =>
        engine.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: d.tanggalKini,
            komponen: [{ eventCode: "PENYALURAN_NON_PUMK", nilai: rp(100_000) }],
          },
          tx,
          d.ctx.maker,
        ),
      ),
      KODE_JURNAL.EVENT_PAYLOAD_TIDAK_LENGKAP,
    );
  });

  test("gabungan tanpa komponen ditolak sebagai jurnal kurang dari dua baris", async () => {
    await tolakDengan(
      d.db.transaction((tx) =>
        engine.postingEventGabungan(
          { cabangId: d.cabangId, tanggalTransaksi: d.tanggalKini, komponen: [] },
          tx,
          d.ctx.maker,
        ),
      ),
      KODE_JURNAL.MINIMAL_DUA_BARIS,
    );
  });

  test("validasi spec 6.2 tetap berlaku: periode tertutup, nilai negatif, cabang di luar scope", async () => {
    await tolakDengan(
      d.db.transaction((tx) =>
        engine.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: "2031-07-09",
            komponen: komponenSetoran(rp(100_000), rp(10_000)),
          },
          tx,
          d.ctx.maker,
        ),
      ),
      KODE_JURNAL.PERIODE_TIDAK_OPEN,
    );

    await tolakDengan(
      d.db.transaction((tx) =>
        engine.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: d.tanggalKini,
            komponen: [
              { eventCode: "ANGSURAN_POKOK", nilai: "-100000.00" },
              { eventCode: "ANGSURAN_JASA_ADM", nilai: rp(100_000) },
            ],
          },
          tx,
          d.ctx.maker,
        ),
      ),
      KODE_JURNAL.NILAI_NEGATIF,
    );

    await tolakDengan(
      d.db.transaction((tx) =>
        engine.postingEventGabungan(
          {
            cabangId: d.cabangLainId,
            tanggalTransaksi: d.tanggalKini,
            komponen: komponenSetoran(rp(100_000), rp(10_000)),
          },
          tx,
          d.ctx.maker,
        ),
      ),
      KODE_JURNAL.CABANG_DILUAR_SCOPE,
    );
  });

  test("tidak menuntut jurnal.post: maker boleh menyelesaikan penerimaan angsuran", async () => {
    // Spec 2 gives Maker "input penerimaan angsuran" and gives `jurnal.post`
    // only to Approver. If the automatic journal demanded `jurnal.post`, no
    // single role could complete a deposit: the business action authorised and
    // its ledger consequence refused.
    expect(d.ctx.maker.permissions).not.toContain("jurnal.post");
    const hasil = await d.db.transaction((tx) =>
      engine.postingEventGabungan(
        {
          cabangId: d.cabangId,
          tanggalTransaksi: d.tanggalKini,
          komponen: komponenSetoran(rp(120_000), rp(12_000)),
        },
        tx,
        d.ctx.maker,
      ),
    );
    expect(hasil.status).toBe("POSTED");
    // Manual posting is where segregation of duties lives, and it still bites.
    const draft = await engine.buatJurnal(
      {
        cabangId: d.cabangId,
        jenis: "UMUM",
        tanggalTransaksi: d.tanggalKini,
        keterangan: "manual tetap butuh jurnal.post",
        baris: [
          { akunId: d.akun.kas.id, debit: rp(1_000) },
          { akunId: d.akun.pendapatanAlokasi.id, kredit: rp(1_000) },
        ],
      },
      d.ctx.maker,
    );
    await tolakDengan(engine.postingJurnal(draft.id, d.ctx.maker), KODE_JURNAL.TIDAK_BERWENANG);
  });
});

describe("otorisasi: izin yang dijaga engine harus izin yang bisa diberikan", () => {
  // THE BUG CLASS THIS CLOSES. The engine used to check `jurnal.update` and
  // `jurnal.delete` while the auth catalogue carried neither, and to check
  // `jurnal.post` for reversal while `jurnal.reversal` existed and granted
  // nothing. Both stayed green for the same reason: the fixture wrote its own
  // permission arrays, so every test asserted against its own opinion instead
  // of against the grant matrix. Resolving from the database is what makes
  // "the engine demands a permission nobody can be granted" a failing test.
  test("setiap izin yang dijaga engine ada di katalog auth", async () => {
    for (const kode of Object.values(PERMISSION_JURNAL)) {
      // A typo here is a permanent 403 that reads like a policy decision.
      expect(canonicalPermission(kode)).toBe(kode);
    }
  });

  test("setiap izin yang dijaga engine benar benar dipegang minimal satu role di database", async () => {
    // Through the pg adapter on purpose: seedRbac binds a text[] parameter,
    // and node-postgres serialises a JS array correctly where a bare
    // comma-joined string would be rejected.
    const dbPg = createDbAdapter();
    await seedRbac(dbPg);

    const diberikan = new Set<string>();
    for (const role of ROLE_CODES) {
      for (const kode of await permissionsForRole(dbPg, role)) diberikan.add(kode);
    }

    for (const kode of Object.values(PERMISSION_JURNAL)) {
      // If this fails, the engine is guarding a door with a key that does not
      // exist: the operation is unreachable for every role in the system.
      expect(diberikan.has(kode)).toBe(true);
    }

    // And the two the engine treats as distinct really are distinct rights in
    // the matrix, held by the role that reverses rather than by everyone who
    // can post.
    const approver = await permissionsForRole(dbPg, "APPROVER");
    expect(approver).toContain(PERMISSION_JURNAL.POSTING);
    expect(approver).toContain(PERMISSION_JURNAL.REVERSAL);
    const maker = await permissionsForRole(dbPg, "MAKER");
    expect(maker).toContain(PERMISSION_JURNAL.BUAT);
    expect(maker).not.toContain(PERMISSION_JURNAL.POSTING);
    expect(maker).not.toContain(PERMISSION_JURNAL.REVERSAL);
  }, 30_000);
});

describe("otorisasi: reversal adalah hak tersendiri", () => {
  test("pemegang jurnal.post tanpa jurnal.reversal tidak boleh membalik jurnal", async () => {
    // `jurnal.reversal` exists in the auth catalogue and drives its own nav
    // item. If the engine checked `jurnal.post` instead, that permission would
    // grant nothing and every user who can post would silently also be able to
    // reverse a posted journal. In the shipped APPROVER role the two travel
    // together, so this changes nobody's access today; it makes them
    // separable, which is the only reason to have two codes.
    const draft = await engine.buatJurnal(
      {
        cabangId: d.cabangId,
        jenis: "UMUM",
        tanggalTransaksi: d.tanggalKini,
        keterangan: "uji hak reversal",
        baris: [
          { akunId: d.akun.kas.id, debit: rp(88_000) },
          { akunId: d.akun.pendapatanAlokasi.id, kredit: rp(88_000) },
        ],
      },
      d.ctx.approver,
    );
    const posted = await engine.postingJurnal(draft.id, d.ctx.approver);

    const hanyaPosting = {
      ...d.ctx.approver,
      permissions: d.ctx.approver.permissions.filter((p) => p !== "jurnal.reversal"),
    };
    expect(hanyaPosting.permissions).toContain("jurnal.post");
    await tolakDengan(
      engine.reversalJurnal(posted.id, "tanpa hak reversal", hanyaPosting),
      KODE_JURNAL.TIDAK_BERWENANG,
    );
    // Untouched: a refused reversal must not half-apply.
    const db = await bacaJurnalDb(d.db, posted.id);
    expect(db?.status).toBe("POSTED");
    expect(db?.reversed_by_jurnal_id).toBeNull();

    // The same user WITH the right succeeds, which is what proves the refusal
    // was about the permission and not about the journal.
    const rev = await engine.reversalJurnal(posted.id, "dengan hak reversal", d.ctx.approver);
    expect(rev.jenis).toBe("REVERSAL");
  });
});

describe("spec 7.2 atomicity: jurnal gabungan hidup di transaksi pemanggil", () => {
  test("kalau langkah pemanggil setelah jurnal gagal, jurnal gabungan ikut hilang", async () => {
    // This is the requirement in spec 7.2's own words: "Seluruh langkah 1
    // sampai 8 dalam satu transaksi database. Kalau jurnal gagal, alokasi
    // harus rollback." The reverse must hold too, or a failed allocation
    // leaves a real posted journal behind.
    let idJurnal = "";
    const sebelum = await selisihLedger(d.db);

    let gagal = false;
    try {
      await d.db.transaction(async (tx) => {
        const hasil = await engine.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: d.tanggalKini,
            komponen: komponenSetoran(rp(900_000), rp(90_000)),
          },
          tx,
          d.ctx.maker,
        );
        idJurnal = hasil.jurnalId;
        // Stand-in for a later allocation step refusing (an outstanding that
        // would go negative, a schedule row already settled).
        throw new Error("langkah alokasi berikutnya menolak");
      });
    } catch (e) {
      gagal = true;
      expect((e as Error).message).toContain("langkah alokasi berikutnya menolak");
    }

    expect(gagal).toBe(true);
    expect(idJurnal).not.toBe("");
    // The journal it had already written is gone, not merely unposted.
    expect(await bacaJurnalDb(d.db, idJurnal)).toBeNull();
    expect(await selisihLedger(d.db)).toBe(sebelum);
  });

  test("penolakan balance yang datang di transaksi pemanggil tetap jadi domain error bersih", async () => {
    // The balance guard is a DEFERRED trigger: on this path it would otherwise
    // only speak when the CALLER commits, far outside any `try` this module
    // owns, and the caller would receive raw trigger text it cannot translate.
    // The engine forces the guard to fire before it returns, so the refusal
    // arrives here as a JurnalError. The unbalanced journal below is written by
    // hand, blessed as 'seed' so the bypass is visible in the data, and stands
    // for the real case: something else in the caller's transaction left a
    // POSTED journal that does not balance.
    let ditangkap: unknown;
    try {
      await d.db.transaction(async (tx) => {
        await tx.query(`select set_config('tjsl.jalur_posting', 'seed:' || txid_current(), true)`);
        // DRAFT first, lines, then the POSTED flip. Any other order makes the
        // totals trigger UPDATE a POSTED row, which the immutability guard
        // refuses (TJSL-JRN-011) before the balance guard ever gets a turn.
        const rusak = await tx.query<{ id: string }>(
          `insert into jurnal (bumn_id, cabang_id, no_jurnal, jenis, tanggal_transaksi, periode_id, status)
           values ($1, $2, $3, 'UMUM', $4, $5, 'DRAFT') returning id`,
          [d.bumnId, d.cabangId, kunci("RAW-POSTED"), d.tanggalKini, d.periodeKini.id],
        );
        await tx.query(
          `insert into jurnal_baris (jurnal_id, urutan, akun_id, debit) values ($1, 1, $2, $3)`,
          [rusak[0].id, d.akun.kas.id, rp(5_000_000)],
        );
        await tx.query(
          `insert into jurnal_baris (jurnal_id, urutan, akun_id, kredit) values ($1, 2, $2, $3)`,
          [rusak[0].id, d.akun.pendapatanAlokasi.id, rp(4_999_999)],
        );
        await tx.query(
          `update jurnal set status = 'POSTED', posted_by = $2, posted_at = now() where id = $1`,
          [rusak[0].id, d.ctx.maker.userId],
        );

        await engine.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: d.tanggalKini,
            komponen: komponenSetoran(rp(10_000), rp(1_000)),
          },
          tx,
          d.ctx.maker,
        );
      });
    } catch (e) {
      ditangkap = e;
    }

    expect(ditangkap).toBeInstanceOf(JurnalError);
    const err = ditangkap as JurnalError;
    expect(err.kode).toBe(KODE_JURNAL.TIDAK_BALANCE);
    // The raw trigger text is kept for the log and kept OUT of the message.
    expect(err.penyebabDb ?? "").toContain("TJSL-JRN-031");
    expect(err.message).not.toContain("TJSL-JRN-031");
    expect(err.message).not.toMatch(/PL\/pgSQL|SQLSTATE|violates/i);
    expect(await selisihLedger(d.db)).toBe("0.00");
  });
});

describe("audit trail jurnal", () => {
  test("posting, reversal dan pembatalan draft menulis satu baris audit masing masing", async () => {
    const audit = createAuditService({ db: d.db });
    const mesin = createJurnalEngine({ db: d.db, jam: d.jam, audit, pembalikStateBisnis: [] });

    async function barisAudit(entitasId: string): Promise<Array<{ aksi: string; hasil: string }>> {
      return d.db.query<{ aksi: string; hasil: string }>(
        `select aksi, hasil from audit_log where entitas = 'jurnal' and entitas_id = $1 order by id`,
        [entitasId],
      );
    }

    const draft = await mesin.buatJurnal(
      {
        cabangId: d.cabangId,
        jenis: "UMUM",
        tanggalTransaksi: d.tanggalKini,
        keterangan: "jurnal untuk jejak audit",
        baris: [
          { akunId: d.akun.kas.id, debit: rp(640_000) },
          { akunId: d.akun.pendapatanAlokasi.id, kredit: rp(640_000) },
        ],
      },
      d.ctx.approver,
    );
    const posted = await mesin.postingJurnal(draft.id, d.ctx.approver);
    const rev = await mesin.reversalJurnal(posted.id, "uji jejak audit", d.ctx.approver);

    expect((await barisAudit(draft.id)).map((r) => r.aksi)).toEqual([
      "jurnal.create",
      "jurnal.post",
    ]);
    expect((await barisAudit(rev.id)).map((r) => r.aksi)).toEqual(["jurnal.reversal"]);

    const dibatalkan = await mesin.buatJurnal(
      {
        cabangId: d.cabangId,
        jenis: "UMUM",
        tanggalTransaksi: d.tanggalKini,
        keterangan: "draft yang dibatalkan",
        baris: [
          { akunId: d.akun.kas.id, debit: rp(11_000) },
          { akunId: d.akun.pendapatanAlokasi.id, kredit: rp(11_000) },
        ],
      },
      d.ctx.approver,
    );
    await mesin.batalkanJurnalDraft(dibatalkan.id, d.ctx.approver);
    expect((await barisAudit(dibatalkan.id)).map((r) => r.aksi)).toEqual([
      "jurnal.create",
      "jurnal.cancel",
    ]);

    // Every row names the acting user and records a success; a refusal has no
    // transaction left to write into and is the HTTP layer's to record.
    const semua = await d.db.query<{ n: number }>(
      `select count(*)::int as n from audit_log
        where entitas = 'jurnal' and entitas_id = $1 and hasil = 'SUKSES' and user_id = $2`,
      [draft.id, d.ctx.approver.userId],
    );
    expect(semua[0].n).toBe(2);
  });

  test("audit ikut rollback: jurnal yang gagal tidak meninggalkan jejak yang mengklaim berhasil", async () => {
    const audit = createAuditService({ db: d.db });
    const mesin = createJurnalEngine({ db: d.db, jam: d.jam, audit });

    let idJurnal = "";
    try {
      await d.db.transaction(async (tx) => {
        const hasil = await mesin.postingEventGabungan(
          {
            cabangId: d.cabangId,
            tanggalTransaksi: d.tanggalKini,
            komponen: komponenSetoran(rp(77_000), rp(7_000)),
          },
          tx,
          d.ctx.maker,
        );
        idJurnal = hasil.jurnalId;
        throw new Error("pemanggil membatalkan");
      });
    } catch {
      // expected
    }
    const jejak = await d.db.query<{ n: number }>(
      `select count(*)::int as n from audit_log where entitas = 'jurnal' and entitas_id = $1`,
      [idJurnal],
    );
    expect(jejak[0].n).toBe(0);
  });

  test("tanpa pencatat audit yang dipasang, engine tetap memposting", async () => {
    // A ledger write must never be lost because an audit sink was not wired.
    const tanpaAudit = createJurnalEngine({ db: d.db, jam: d.jam });
    const hasil = await d.db.transaction((tx) =>
      tanpaAudit.postingEventGabungan(
        {
          cabangId: d.cabangId,
          tanggalTransaksi: d.tanggalKini,
          komponen: komponenSetoran(rp(33_000), rp(3_000)),
        },
        tx,
        d.ctx.maker,
      ),
    );
    expect(hasil.status).toBe("POSTED");
  });
});

describe("driver produksi: engine di atas core/adapters/db (node-postgres)", () => {
  test("SQLSTATE dibaca dari kedua bentuk error driver, bukan hanya milik bun:sql", async () => {
    // The bug this pins: reading only `errno` left the concurrency branch dead
    // in production, because node-postgres puts the SQLSTATE on `code` while
    // `code` on a bun:sql error is "ERR_POSTGRES_SERVER_ERROR" and not a
    // SQLSTATE at all.
    const bentukBun = { message: "deadlock detected", errno: "40P01", code: "ERR_POSTGRES_SERVER_ERROR" };
    const bentukPg = { message: "deadlock detected", code: "40P01" };
    for (const bentuk of [bentukBun, bentukPg]) {
      const err = terjemahkanKesalahanDb(bentuk);
      expect(err).toBeInstanceOf(JurnalError);
      expect(err?.kode).toBe(KODE_JURNAL.POSTING_BENTROK);
      expect(err?.message).not.toMatch(/deadlock/i);
      expect(err?.penyebabDb).toContain("deadlock detected");
    }
    // A driver error with no SQLSTATE anywhere stays unexplained rather than
    // being dressed up as a business rule.
    expect(terjemahkanKesalahanDb({ message: "socket hang up" })).toBeNull();
  });

  test("engine yang dibangun dari createDbAdapter memposting, membalik, dan menolak dengan bersih", async () => {
    // The SAME engine, on the port the server really uses. Without this the
    // production path had no coverage at all: every other test in this folder
    // builds its port from bun:sql.
    const dbPg: JurnalDbPort = createDbAdapter();
    const mesin = createJurnalEngine({ db: dbPg, jam: d.jam, pembalikStateBisnis: [] });

    const draft = await mesin.buatJurnal(
      {
        cabangId: d.cabangId,
        jenis: "UMUM",
        tanggalTransaksi: d.tanggalKini,
        keterangan: "lewat adapter produksi",
        baris: [
          { akunId: d.akun.kas.id, debit: rp(2_222_000) },
          { akunId: d.akun.pendapatanAlokasi.id, kredit: rp(2_222_000) },
        ],
      },
      d.ctx.approver,
    );
    expect(draft.noJurnal).toMatch(POLA_NO_JURNAL);

    const posted = await mesin.postingJurnal(draft.id, d.ctx.approver);
    expect(posted.status).toBe("POSTED");
    expect(posted.totalDebit).toBe(rp(2_222_000));

    const rev = await mesin.reversalJurnal(posted.id, "uji adapter produksi", d.ctx.approver);
    expect(rev.jenis).toBe("REVERSAL");
    expect((await bacaJurnalDb(d.db, posted.id))?.status).toBe("REVERSED");

    // A refusal on the production driver is still a clean domain error.
    await tolakDengan(
      mesin.reversalJurnal(posted.id, "reversal kedua", d.ctx.approver),
      KODE_JURNAL.JURNAL_SUDAH_REVERSED,
    );
    await tolakDengan(
      mesin.postingJurnal(draft.id, d.ctx.approver),
      KODE_JURNAL.JURNAL_TIDAK_DRAFT,
    );

    // And the combined path works there too, inside a transaction the caller
    // owns on that same adapter.
    const gabungan = await dbPg.transaction((tx: JurnalTx) =>
      mesin.postingEventGabungan(
        {
          cabangId: d.cabangId,
          tanggalTransaksi: d.tanggalKini,
          komponen: komponenSetoran(rp(500_000), rp(50_000), rp(5_000)),
        },
        tx,
        d.ctx.maker,
      ),
    );
    expect(gabungan.jumlahBaris).toBe(4);
    expect(await selisihLedger(d.db)).toBe("0.00");
  });
});
