// Every statement the journal engine issues, in one file. No business rules
// live here; the engine decides, the repo reads and writes.
//
// THIS FILE RUNS ON TWO DRIVERS. The tests build their port on `bun:sql`
// (the engine needed a transaction while core/ was mid-flight); the server
// builds it on node-postgres through core/adapters/db.ts. Every cast below is
// correct on both, but the reasons were originally written from `bun:sql`
// observations only, so read them as "why the cast is here", not as "how the
// driver behaves". Where the two differ at all (the SQLSTATE field), the
// difference is handled in ./kesalahan.ts, in one place.
//
// THREE DRIVER FACTS THIS FILE IS BUILT AROUND (verified against `bun:sql`
// 1.3.x before a line of the engine was written; each cast is also the correct
// and portable form for node-postgres, which is why nothing here changes when
// the port is swapped):
//
//  1. A `jsonb` parameter bound from a JS STRING is stored as a JSON string
//     SCALAR, not as an object: `insert ... values ($1::jsonb)` with
//     '{"a":1}' produces jsonb_typeof = 'string' and `j->>'a'` = NULL. The
//     dimensions on a journal line would silently stop being queryable. Every
//     jsonb parameter below therefore goes through `$n::text::jsonb`, and
//     every read casts `dimensi_json::text` and parses it here, so the shape
//     the engine sees never depends on driver decoding.
//  2. DATE and TIMESTAMPTZ come back as JS `Date`. Money is NUMERIC and comes
//     back as a string. So every date and timestamp is selected `::text`,
//     which keeps `tanggal_transaksi` a plain 'YYYY-MM-DD' end to end and
//     keeps amounts as the decimal strings `Uang` promises.
//  3. A JS array is serialised as a bare comma-joined string, which `uuid[]`
//     rejects. Hence `IN ($2, $3, ...)` built from a placeholder list rather
//     than `= any($2::uuid[])`.
//
// STATUS IS NEVER WRITTEN AT INSERT TIME. A journal is always INSERTed as
// DRAFT and moved to POSTED by a separate UPDATE, even when the caller wants a
// posted journal in one call (postingEvent, reversal). Inserting a row already
// POSTED and then adding its lines makes the totals trigger UPDATE a POSTED
// row, which the immutability guard of migrations/0010 rejects outright
// (TJSL-JRN-011). DRAFT first is not a style preference, it is the only order
// the schema allows.
import type { DimensiBaris, JenisJurnal, JurnalTx, StatusJurnal, Uang } from "./contract";

export interface PeriodeBaris {
  id: string;
  tahun: number;
  bulan: number;
  status: string;
  tanggal_mulai: string;
  tanggal_akhir: string;
}

export interface CabangBaris {
  id: string;
  bumn_id: string;
  kode: string;
}

export interface AkunBaris {
  id: string;
  kode: string;
  aktif: boolean;
  is_postable: boolean;
  is_kas: boolean;
}

export interface MappingBaris {
  id: string;
  event_code: string;
  akun_debit_id: string | null;
  akun_kredit_id: string | null;
  debit_dari_payload: boolean;
  kredit_dari_payload: boolean;
  jenis_jurnal: JenisJurnal;
}

export interface JurnalBaris {
  id: string;
  bumn_id: string;
  cabang_id: string;
  no_jurnal: string;
  jenis: JenisJurnal;
  tanggal_transaksi: string;
  periode_id: string;
  keterangan: string | null;
  referensi_tipe: string | null;
  referensi_id: string | null;
  total_debit: Uang;
  total_kredit: Uang;
  status: StatusJurnal;
  is_auto_generated: boolean;
  reversal_of_jurnal_id: string | null;
  reversed_by_jurnal_id: string | null;
  kunci_idempotensi: string | null;
  verified_by: string | null;
  verified_at: string | null;
  posted_by: string | null;
  posted_at: string | null;
  created_by: string | null;
  deleted_at: string | null;
  version: number;
}

export interface BarisJurnalBaris {
  id: string;
  urutan: number;
  akun_id: string;
  debit: Uang;
  kredit: Uang;
  keterangan: string | null;
  mitra_id: string | null;
  akad_id: string | null;
  dimensi: DimensiBaris;
}

export interface HeaderBaru {
  bumnId: string;
  cabangId: string;
  noJurnal: string;
  jenis: JenisJurnal;
  tanggalTransaksi: string;
  periodeId: string;
  keterangan: string | null;
  referensiTipe: string | null;
  referensiId: string | null;
  isAutoGenerated: boolean;
  reversalOfJurnalId: string | null;
  kunciIdempotensi: string | null;
  userId: string;
}

export interface BarisBaru {
  urutan: number;
  akunId: string;
  debit: Uang;
  kredit: Uang;
  keterangan: string | null;
  mitraId: string | null;
  akadId: string | null;
  dimensi: DimensiBaris;
}

const KOLOM_JURNAL = `
  id, bumn_id, cabang_id, no_jurnal, jenis,
  tanggal_transaksi::text as tanggal_transaksi, periode_id, keterangan,
  referensi_tipe, referensi_id,
  total_debit::text as total_debit, total_kredit::text as total_kredit,
  status, is_auto_generated, reversal_of_jurnal_id, reversed_by_jurnal_id,
  kunci_idempotensi, verified_by, verified_at::text as verified_at,
  posted_by, posted_at::text as posted_at, created_by,
  deleted_at::text as deleted_at, version`;

function daftarPlaceholder(mulai: number, jumlah: number): string {
  return Array.from({ length: jumlah }, (_, i) => `$${mulai + i}::uuid`).join(", ");
}

export interface JurnalRepo {
  periodeUntukTanggal(tx: JurnalTx, bumnId: string, tanggal: string): Promise<PeriodeBaris | null>;
  periodeOpenMemuat(tx: JurnalTx, bumnId: string, tanggal: string): Promise<PeriodeBaris | null>;
  periodeOpenTerakhir(tx: JurnalTx, bumnId: string): Promise<PeriodeBaris | null>;
  cabang(tx: JurnalTx, cabangId: string): Promise<CabangBaris | null>;
  akun(tx: JurnalTx, bumnId: string, ids: readonly string[]): Promise<AkunBaris[]>;
  mappingEvent(tx: JurnalTx, bumnId: string, eventCode: string): Promise<MappingBaris | null>;
  konfigurasi(tx: JurnalTx, bumnId: string, grup: string, kunci: string): Promise<string | null>;
  jurnal(tx: JurnalTx, id: string): Promise<JurnalBaris | null>;
  jurnalTerkunci(tx: JurnalTx, id: string): Promise<JurnalBaris | null>;
  baris(tx: JurnalTx, jurnalId: string): Promise<BarisJurnalBaris[]>;
  ringkasanBaris(tx: JurnalTx, jurnalId: string): Promise<{ jumlah: number; debit: Uang; kredit: Uang }>;
  sisipkanHeader(tx: JurnalTx, header: HeaderBaru): Promise<string>;
  sisipkanBaris(tx: JurnalTx, jurnalId: string, baris: BarisBaru, userId: string): Promise<void>;
  hapusBarisDraft(tx: JurnalTx, jurnalId: string): Promise<void>;
  ubahHeaderDraft(
    tx: JurnalTx,
    id: string,
    ubah: {
      cabangId: string;
      tanggalTransaksi: string;
      periodeId: string;
      keterangan: string | null;
      referensiTipe: string | null;
      referensiId: string | null;
      userId: string;
    },
  ): Promise<void>;
  tandaiPosted(tx: JurnalTx, id: string, userId: string, waktu: string): Promise<boolean>;
  tandaiVerified(tx: JurnalTx, id: string, userId: string, waktu: string): Promise<boolean>;
  tandaiReversed(tx: JurnalTx, id: string, reversalId: string, userId: string): Promise<boolean>;
  softDeleteDraft(tx: JurnalTx, id: string, userId: string, waktu: string): Promise<boolean>;
  paksaCekBalance(tx: JurnalTx): Promise<void>;
}

export function createJurnalRepo(): JurnalRepo {
  // One `SET LOCAL` per transaction, keyed on the transaction handle itself.
  // Both adapters hand out exactly one runner object per transaction, so the
  // WeakSet is a faithful "have I already marked this transaction" and the
  // entry disappears with the handle.
  const sudahDitandai = new WeakSet<JurnalTx>();

  /**
   * INVARIANT 11'S STRUCTURAL HALF. `tools/check-boundaries.ts` reads import
   * specifiers, so it cannot see an `insert into jurnal_baris` in a module that
   * imports nothing. This marks the transaction as coming through the engine so
   * the database can refuse ledger writes that did not, which is the only
   * enforcement that survives a Fase 4 agent copying raw SQL from the nearest
   * test file.
   *
   * The setting is transaction-scoped: it cannot leak to the next request on a
   * pooled connection (verified: it reads back NULL after COMMIT), and it
   * carries this transaction's id so that even a session-scoped slip cannot
   * bless a later one. The matching trigger is
   * `trg_jurnal_05_jalur_posting` / `trg_jurnal_baris_05_jalur_posting`
   * (migrations/0020), which also stamps `jurnal.jalur_posting = 'ENGINE'`.
   */
  async function tandaiJalurEngine(tx: JurnalTx): Promise<void> {
    if (sudahDitandai.has(tx)) return;
    // The NONCE form, not a bare 'engine'. migration 0020 accepts both, but
    // only this one is leak-proof: a one-word slip from SET LOCAL to plain SET
    // would otherwise bless a pooled connection for every later transaction on
    // it, and Postgres cannot tell the two apart from inside the trigger. With
    // the transaction id in the value, a leaked blessing simply stops matching.
    await tx.query(`select set_config('tjsl.jalur_posting', 'engine:' || txid_current(), true)`);
    sudahDitandai.add(tx);
  }

  return {
    async periodeUntukTanggal(tx, bumnId, tanggal) {
      const r = await tx.query<PeriodeBaris>(
        `select id, tahun, bulan, status,
                tanggal_mulai::text as tanggal_mulai, tanggal_akhir::text as tanggal_akhir
           from periode
          where bumn_id = $1::uuid
            and $2::date between tanggal_mulai and tanggal_akhir
            and deleted_at is null
          limit 1`,
        [bumnId, tanggal],
      );
      return r[0] ?? null;
    },

    async periodeOpenMemuat(tx, bumnId, tanggal) {
      const r = await tx.query<PeriodeBaris>(
        `select id, tahun, bulan, status,
                tanggal_mulai::text as tanggal_mulai, tanggal_akhir::text as tanggal_akhir
           from periode
          where bumn_id = $1::uuid
            and status = 'OPEN'
            and $2::date between tanggal_mulai and tanggal_akhir
            and deleted_at is null
          limit 1`,
        [bumnId, tanggal],
      );
      return r[0] ?? null;
    },

    async periodeOpenTerakhir(tx, bumnId) {
      const r = await tx.query<PeriodeBaris>(
        `select id, tahun, bulan, status,
                tanggal_mulai::text as tanggal_mulai, tanggal_akhir::text as tanggal_akhir
           from periode
          where bumn_id = $1::uuid and status = 'OPEN' and deleted_at is null
          order by tanggal_mulai desc
          limit 1`,
        [bumnId],
      );
      return r[0] ?? null;
    },

    async cabang(tx, cabangId) {
      const r = await tx.query<CabangBaris>(
        `select id, bumn_id, kode from cabang where id = $1::uuid and deleted_at is null`,
        [cabangId],
      );
      return r[0] ?? null;
    },

    async akun(tx, bumnId, ids) {
      if (ids.length === 0) return [];
      const r = await tx.query<AkunBaris>(
        `select id, kode, aktif, is_postable, is_kas
           from akun
          where bumn_id = $1::uuid
            and deleted_at is null
            and id in (${daftarPlaceholder(2, ids.length)})`,
        [bumnId, ...ids],
      );
      return r;
    },

    async mappingEvent(tx, bumnId, eventCode) {
      const r = await tx.query<MappingBaris>(
        `select id, event_code, akun_debit_id, akun_kredit_id,
                debit_dari_payload, kredit_dari_payload, jenis_jurnal
           from event_jurnal_mapping
          where bumn_id = $1::uuid and event_code = $2 and aktif and deleted_at is null
          limit 1`,
        [bumnId, eventCode],
      );
      return r[0] ?? null;
    },

    async konfigurasi(tx, bumnId, grup, kunci) {
      // A bumn-scoped row overrides the shipped default (bumn_id IS NULL),
      // which is exactly how modules/konfigurasi resolves a parameter. Read
      // fresh on every call: spec rule 3 requires a config edit to take effect
      // without a deploy, and the manual-journal tests prove it by editing the
      // row mid-process.
      const r = await tx.query<{ nilai: string | null }>(
        `select nilai
           from konfigurasi
          where grup = $1 and kunci = $2
            and (bumn_id = $3::uuid or bumn_id is null)
            and deleted_at is null
          order by (bumn_id is null)
          limit 1`,
        [grup, kunci, bumnId],
      );
      return r[0]?.nilai ?? null;
    },

    async jurnal(tx, id) {
      const r = await tx.query<JurnalBaris>(
        `select ${KOLOM_JURNAL} from jurnal where id = $1::uuid`,
        [id],
      );
      return r[0] ?? null;
    },

    async jurnalTerkunci(tx, id) {
      // The serialisation point for spec 6.6.9. Row-level, so ten posts of ten
      // different journals do not queue behind each other.
      const r = await tx.query<JurnalBaris>(
        `select ${KOLOM_JURNAL} from jurnal where id = $1::uuid for update`,
        [id],
      );
      return r[0] ?? null;
    },

    async baris(tx, jurnalId) {
      const r = await tx.query<Omit<BarisJurnalBaris, "dimensi"> & { dimensi_json: string }>(
        `select id, urutan, akun_id, debit::text as debit, kredit::text as kredit,
                keterangan, mitra_id, akad_id, dimensi_json::text as dimensi_json
           from jurnal_baris
          where jurnal_id = $1::uuid and deleted_at is null
          order by urutan`,
        [jurnalId],
      );
      return r.map((b) => {
        const { dimensi_json, ...sisa } = b;
        return { ...sisa, dimensi: (JSON.parse(dimensi_json) ?? {}) as DimensiBaris };
      });
    },

    async ringkasanBaris(tx, jurnalId) {
      const r = await tx.query<{ jumlah: number; debit: Uang; kredit: Uang }>(
        `select count(*)::int as jumlah,
                coalesce(sum(debit), 0)::numeric(20,2)::text as debit,
                coalesce(sum(kredit), 0)::numeric(20,2)::text as kredit
           from jurnal_baris
          where jurnal_id = $1::uuid and deleted_at is null`,
        [jurnalId],
      );
      return r[0] ?? { jumlah: 0, debit: "0.00", kredit: "0.00" };
    },

    async sisipkanHeader(tx, h) {
      await tandaiJalurEngine(tx);
      const r = await tx.query<{ id: string }>(
        `insert into jurnal
           (bumn_id, cabang_id, no_jurnal, jenis, tanggal_transaksi, periode_id, keterangan,
            referensi_tipe, referensi_id, status, is_auto_generated, reversal_of_jurnal_id,
            kunci_idempotensi, created_by, updated_by)
         values ($1::uuid, $2::uuid, $3, $4, $5::date, $6::uuid, $7,
                 $8, $9::uuid, 'DRAFT', $10::boolean, $11::uuid,
                 $12, $13::uuid, $13::uuid)
         returning id`,
        [
          h.bumnId,
          h.cabangId,
          h.noJurnal,
          h.jenis,
          h.tanggalTransaksi,
          h.periodeId,
          h.keterangan,
          h.referensiTipe,
          h.referensiId,
          h.isAutoGenerated,
          h.reversalOfJurnalId,
          h.kunciIdempotensi,
          h.userId,
        ],
      );
      return r[0].id;
    },

    async sisipkanBaris(tx, jurnalId, b, userId) {
      await tandaiJalurEngine(tx);
      await tx.query(
        `insert into jurnal_baris
           (jurnal_id, urutan, akun_id, debit, kredit, keterangan, mitra_id, akad_id,
            dimensi_json, created_by, updated_by)
         values ($1::uuid, $2::smallint, $3::uuid, $4::numeric(20,2), $5::numeric(20,2),
                 $6, $7::uuid, $8::uuid, $9::text::jsonb, $10::uuid, $10::uuid)`,
        [
          jurnalId,
          b.urutan,
          b.akunId,
          b.debit,
          b.kredit,
          b.keterangan,
          b.mitraId,
          b.akadId,
          JSON.stringify(b.dimensi ?? {}),
          userId,
        ],
      );
    },

    async hapusBarisDraft(tx, jurnalId) {
      // Physical delete, and only reachable for a DRAFT: the line-immutability
      // trigger refuses this the moment the parent leaves DRAFT.
      await tx.query(`delete from jurnal_baris where jurnal_id = $1::uuid`, [jurnalId]);
    },

    async ubahHeaderDraft(tx, id, u) {
      // `jenis` and `no_jurnal` are deliberately absent from the SET list: the
      // document series carries the type, so changing either would break the
      // number's meaning (spec 4.6).
      await tx.query(
        `update jurnal
            set cabang_id = $2::uuid,
                tanggal_transaksi = $3::date,
                periode_id = $4::uuid,
                keterangan = $5,
                referensi_tipe = $6,
                referensi_id = $7::uuid,
                updated_by = $8::uuid
          where id = $1::uuid and status = 'DRAFT' and deleted_at is null`,
        [
          id,
          u.cabangId,
          u.tanggalTransaksi,
          u.periodeId,
          u.keterangan,
          u.referensiTipe,
          u.referensiId,
          u.userId,
        ],
      );
    },

    async tandaiPosted(tx, id, userId, waktu) {
      const r = await tx.query<{ id: string }>(
        `update jurnal
            set status = 'POSTED', posted_by = $2::uuid, posted_at = $3::timestamptz,
                updated_by = $2::uuid
          where id = $1::uuid and status = 'DRAFT' and deleted_at is null
          returning id`,
        [id, userId, waktu],
      );
      return r.length === 1;
    },

    async tandaiVerified(tx, id, userId, waktu) {
      const r = await tx.query<{ id: string }>(
        `update jurnal
            set verified_by = $2::uuid, verified_at = $3::timestamptz, updated_by = $2::uuid
          where id = $1::uuid and status = 'DRAFT' and deleted_at is null
          returning id`,
        [id, userId, waktu],
      );
      return r.length === 1;
    },

    async tandaiReversed(tx, id, reversalId, userId) {
      const r = await tx.query<{ id: string }>(
        `update jurnal
            set status = 'REVERSED', reversed_by_jurnal_id = $2::uuid, updated_by = $3::uuid
          where id = $1::uuid and status = 'POSTED' and deleted_at is null
          returning id`,
        [id, reversalId, userId],
      );
      return r.length === 1;
    },

    async paksaCekBalance(tx) {
      // Fires the DEFERRED balance/min-2-lines guard NOW instead of at COMMIT.
      // Needed only when the transaction belongs to the caller: the engine can
      // translate a refusal it receives inside its own call, but it cannot
      // translate one that arrives when someone else commits, and raw
      // trigger text reaching that caller is exactly what the contract forbids.
      // Named, not `ALL`: forcing every deferred constraint in a caller's
      // transaction would fire other modules' guards before they are done
      // writing. The guard stays immediate for the rest of that transaction,
      // which is safe because the engine always writes header, then lines,
      // then the POSTED flip, so the row is complete whenever it is checked.
      await tx.query(`set constraints trg_jurnal_90_balance immediate`);
    },

    async softDeleteDraft(tx, id, userId, waktu) {
      const r = await tx.query<{ id: string }>(
        `update jurnal
            set deleted_at = $3::timestamptz, deleted_by = $2::uuid, updated_by = $2::uuid
          where id = $1::uuid and status = 'DRAFT' and deleted_at is null
          returning id`,
        [id, userId, waktu],
      );
      return r.length === 1;
    },
  };
}
