// apps/api/src/modules/rka/test-support.ts
//
// Reusable fixture builder for the RKA engine tests (spec 4.8, spec 9.3, spec
// 10.3 report 24, spec 16 scenarios 18 and 24). NOT a *.test.ts file, so
// `bun test` never executes it on its own.
//
// WHY THESE TESTS HIT REAL POSTGRES
// This module's job is almost entirely a claim about what the database already
// contains, and most of what it must respect lives inside Postgres:
//   - `rka_versi_uq` and `rka_baseline_uq` (migrations/0012) ARE the versioning
//     rules of spec 9.3: one row per version, AT MOST ONE DISETUJUI per scope;
//   - `trg_rka_detail_10_dimensi` ties a budget line's dimension to its budget
//     type, so a PUMK line cannot be filed against an expense account;
//   - `v_ledger_baris` (migrations/0018) IS the definition of realisation for
//     an OPEN period, including the reversal predicate of ADR 0010;
//   - `saldo_akun_periode` (migrations/0011), with its identity CHECK, is the
//     definition for a CLOSED one, and its COLUMN LIST is the reason report 24
//     cannot produce a per-sector figure for a closed period at all.
// A fake or in-memory repository proves nothing about any of that. So every
// fixture below writes to `tjsl_test`, which tools/test-env.ts guarantees is
// where DATABASE_URL points during `bun test`.
//
// WHY THE COLLABORATING ENGINES ARE REAL, WRAPPED, NEVER REPLACED
// modules/angsuran/test-support.ts records what the alternative cost: a pure
// double for the journal port hid two production-breaking defects behind
// sixteen green tests. THE RULE THAT CAME OUT OF IT, and that this file
// follows: a double may stand in for a collaborator's FAILURE, never for its
// VALIDATION.
//
// So the realisation this fixture manufactures is real:
//   - every PUMK schedule is generated by the REAL instalment engine and every
//     disbursement is posted by the REAL ledger engine through `postingEvent`;
//   - every Non PUMK grant runs the REAL Non PUMK engine's whole state machine,
//     proposal to assessment to review to approval to disbursement to LPJ, so
//     the `nonpumk_penyaluran` rows report 12 reads and the ledger lines report
//     24 reads are the same event and not two fixtures that happen to agree;
//   - the refund is posted by the REAL engine's `verifikasiLpj`, which is the
//     only thing in the system that knows a refund credits the bidang's own
//     expense account rather than the pooled one.
// THIS MODULE'S OWN ENGINE IS NEVER STOOD IN FOR. Not once. Every RKA row in
// every test is created by `d.engine`, which means a report test currently
// fails at its arrangement step, in `buatRka`, and says so. That is the correct
// failure for a tests-first suite and it names the missing method.
//
// WHY SO MUCH OF THIS RESEMBLES modules/closing/test-support.ts
// `bun tools/check-boundaries.ts` forbids a deep import into a sibling
// module's internals, and that file is internal to modules/closing. The money
// helpers, the unique-key helper, the DB port and the leak-detecting
// `tolakDengan` are therefore re-declared here with the SAME semantics. Two
// rules follow: the shapes must not drift (a sen-level difference between two
// modules' `keSen` would be a real difference in a real ledger), and when a
// shared test-support package appears, this file collapses into it.
//
// THE COA, THE EVENT MAPPINGS, THE PERMISSIONS AND THE PARAMETER CATALOGUE ARE
// THE SHIPPED ONES. `seedCoaDanEventMapping`, `seedKonfigurasiTambahan` and
// `seedRbac` from apps/api/src/seed are called directly rather than re-typed,
// and every context's permission list comes from `permissionsForRole`, which
// READS the grant matrix out of the database. A fixture that hardcodes
// `permissions: ["admin.rka"]` asserts against its own opinion; that is how
// `jurnal.update` / `jurnal.delete` being grantable to nobody stayed invisible,
// and it is how the three catalogue gaps this folder files would have stayed
// invisible too.
//
// NOTHING GLOBAL IS EVER TOUCHED. A closing test once blanked a GLOBAL
// (`bumn_id IS NULL`) `konfigurasi` row to reach a guard and poisoned every
// world that ran afterwards, in every file, for the rest of the run.
// `hapusKonfigurasi` below therefore BLANKS THIS WORLD'S OWN BUMN-SCOPED ROW,
// which reaches the same guard by the same bumn-then-global resolution order
// and cannot be observed by anybody else. It refuses outright to write a row
// with a NULL `bumn_id`. The same rule governs `sdg`, whose rows are global:
// they are inserted ON CONFLICT DO NOTHING and never updated or deleted.
//
// NO TEST MAY DEPEND ON ANOTHER TEST'S DATA. `bun run db:reset` is not run
// between files and several of these tables refuse a physical DELETE, so every
// fixture key is uniquified per call via `kunci()` and every world gets its own
// bumn, branches, chart of accounts, periods, parameter rows, sectors and
// bidang. TWO CONSECUTIVE RUNS WITHOUT A RESET THEREFORE PRODUCE IDENTICAL
// RESULTS, which ./rka-fixture.test.ts is required to demonstrate rather than
// assume.
import { SQL } from "bun";
import { expect } from "bun:test";
import { createAngsuranModule, type AngsuranContext } from "../angsuran/index";
import { createAuditService } from "../audit/index";
import { createJurnalModule, type Jurnal, type JurnalContext } from "../jurnal/index";
import { createNonPumkModule, type NonPumkContext, type NonPumkEngine } from "../nonpumk/index";
import { KATALOG, tipeDataUntuk } from "../konfigurasi/index";
import { createDbAdapter } from "../../core/adapters/db";
import { seedCoaDanEventMapping } from "../../seed/event-jurnal";
import { seedKonfigurasiTambahan } from "../../seed/konfigurasi";
import { permissionsForRole, seedRbac } from "../../seed/rbac";
import {
  KODE_RKA,
  RkaError,
  createRkaEngine,
  type JenisRka,
  type KodeRka,
  type PencatatAuditRka,
  type Persen,
  type RkaContext,
  type RkaDbPort,
  type RkaEngine,
  type RkaTx,
  type Uang,
} from "./contract";

// ---------------------------------------------------------------------------
// Money. BigInt minor units internally, two-decimal strings at every boundary.
// ---------------------------------------------------------------------------

/** Whole rupiah -> `Uang`. `rp(7_500_000)` === "7500000.00". */
export function rp(rupiahBulat: number): Uang {
  if (!Number.isSafeInteger(rupiahBulat)) {
    throw new Error(`rp() hanya menerima bilangan bulat: ${rupiahBulat}`);
  }
  return sen(BigInt(rupiahBulat) * 100n);
}

/** Minor units -> `Uang`. `sen(-150n)` === "-1.50". */
export function sen(minor: bigint): Uang {
  const negatif = minor < 0n;
  const abs = negatif ? -minor : minor;
  return `${negatif ? "-" : ""}${abs / 100n}.${String(abs % 100n).padStart(2, "0")}`;
}

/** `Uang` -> minor units. Throws on anything that is not exactly two decimals. */
export function keSen(nilai: Uang): bigint {
  const m = /^(-?)(\d+)\.(\d{2})$/.exec(nilai);
  if (!m) throw new Error(`bukan Uang yang valid: ${JSON.stringify(nilai)}`);
  const besar = BigInt(m[2]) * 100n + BigInt(m[3]);
  return m[1] === "-" ? -besar : besar;
}

export function jumlahUang(...nilai: Uang[]): Uang {
  return sen(nilai.reduce((acc, n) => acc + keSen(n), 0n));
}

export function kurangUang(a: Uang, b: Uang): Uang {
  return sen(keSen(a) - keSen(b));
}

export function negasiUang(a: Uang): Uang {
  return sen(-keSen(a));
}

/**
 * `realisasi / anggaran * 100`, two decimals, HALF UP away from zero.
 *
 * DECLARED HERE AND NOT ASSERTED AS A LITERAL ANYWHERE. Report 24's percentage
 * column is arithmetic, not policy, so the tests state the rule once, in this
 * function, and compare the engine against it. A test that wrote `"83.33"` by
 * hand would be asserting a rounding decision it had made in its head.
 */
export function persenCapaian(realisasi: Uang, anggaran: Uang): Persen | null {
  const bawah = keSen(anggaran);
  if (bawah === 0n) return null;
  // Scale by 10_000 = 100 (percent) * 100 (two decimals), then round half up.
  const atas = keSen(realisasi) * 10_000n;
  const negatif = atas < 0n !== bawah < 0n;
  const absAtas = atas < 0n ? -atas : atas;
  const absBawah = bawah < 0n ? -bawah : bawah;
  const dibulatkan = (absAtas + absBawah / 2n) / absBawah;
  const bertanda = negatif ? -dibulatkan : dibulatkan;
  const abs = bertanda < 0n ? -bertanda : bertanda;
  return `${bertanda < 0n ? "-" : ""}${abs / 100n}.${String(abs % 100n).padStart(2, "0")}`;
}

// ---------------------------------------------------------------------------
// Unique keys and dates
// ---------------------------------------------------------------------------

const JEJAK = crypto.randomUUID().replace(/-/g, "").slice(0, 8);
let urut = 0;

/**
 * A key unique across worlds, runs and parallel files. Every business key this
 * fixture writes goes through here, because `bun run db:reset` is NOT run
 * between files and several of these tables refuse a physical DELETE. This is
 * the whole reason two consecutive `bun test` runs without a reset produce the
 * same results instead of colliding on the second.
 */
export function kunci(awalan: string): string {
  urut += 1;
  return `${awalan}-${JEJAK}-${String(urut).padStart(4, "0")}`;
}

/** Adds whole days to an ISO date. UTC throughout, no local-time drift. */
export function tambahHari(iso: string, hari: number): string {
  const [t, b, h] = iso.split("-").map((x) => Number.parseInt(x, 10));
  const d = new Date(Date.UTC(t, b - 1, h));
  d.setUTCDate(d.getUTCDate() + hari);
  return d.toISOString().slice(0, 10);
}

/** Adds whole months to an ISO date, clamping to the end of the target month. */
export function tambahBulan(iso: string, bulan: number): string {
  const [t, b, h] = iso.split("-").map((x) => Number.parseInt(x, 10));
  const totalBulan = b - 1 + bulan;
  const tahunBaru = t + Math.floor(totalBulan / 12);
  const bulanBaru = ((totalBulan % 12) + 12) % 12;
  const hariTerakhir = new Date(Date.UTC(tahunBaru, bulanBaru + 1, 0)).getUTCDate();
  const hariBaru = Math.min(h, hariTerakhir);
  return `${tahunBaru}-${String(bulanBaru + 1).padStart(2, "0")}-${String(hariBaru).padStart(2, "0")}`;
}

// ---------------------------------------------------------------------------
// The DB port
// ---------------------------------------------------------------------------

function urlDb(): string {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error(
      "DATABASE_URL tidak ada. Test RKA butuh Postgres nyata (tjsl_test). " +
        "Jalankan `bun test` dari root repo (lihat docs/DEV.md).",
    );
  }
  if (!url.split("?")[0].endsWith("_test")) {
    throw new Error(`Menolak menjalankan fixture RKA di database non-test: ${url}`);
  }
  return url;
}

interface PortUji extends RkaDbPort {
  tutup(): Promise<void>;
}

function buatPortDb(): PortUji {
  const sql = new SQL({ url: urlDb(), max: 6 });
  const bungkus = (jalankan: (t: string, p: unknown[]) => Promise<unknown>): RkaTx => ({
    async query<T = unknown>(text: string, params: unknown[] = []): Promise<T[]> {
      const hasil = await jalankan(text, params);
      return hasil as unknown as T[];
    },
  });
  return {
    query: bungkus((t, p) => sql.unsafe(t, p as never[])).query,
    async transaction<T>(jalankan: (tx: RkaTx) => Promise<T>): Promise<T> {
      const hasil = await sql.begin(async (tx) =>
        jalankan(bungkus((t, p) => tx.unsafe(t, p as never[]))),
      );
      return hasil as T;
    },
    async tutup(): Promise<void> {
      await sql.close();
    },
  };
}

// ---------------------------------------------------------------------------
// Accounts, by the friendly name the tests use
// ---------------------------------------------------------------------------

/**
 * Codes from apps/api/src/seed/coa-inti.ts, which is also what seeds them.
 * Deliberately a lookup onto the SHIPPED codes rather than a second chart of
 * accounts: a fixture COA that drifts from the seeded one is not a failing
 * test, it is a budget filed against an account that does not exist in
 * production.
 */
const KODE_AKUN = {
  kas: "1.1.01",
  bank: "1.1.02",
  piutangPokok: "1.1.03",
  pendapatanAlokasi: "4.1.01",
  pendapatanJasaAdm: "4.1.02",
  pendapatanJasaGiro: "4.1.03",
  bebanPembinaan: "5.1.02",
  bebanNonPumk: "5.1.03",
  bebanOperasional: "5.1.04",
} as const;

export type KunciAkun = keyof typeof KODE_AKUN;

export interface AkunFixture {
  id: string;
  kode: string;
  /** 'D' or 'K'. Report 24 shows realisation in the account's NORMAL sign. */
  saldoNormal: "D" | "K";
}

// ---------------------------------------------------------------------------
// Configuration rows, scoped to the world's bumn
// ---------------------------------------------------------------------------

/**
 * Seeded per world with `bumn_id` set, so a world's values are its own and no
 * test can be perturbed by another agent editing the global (bumn_id NULL) rows
 * that migrations/0004 ships. Every engine in this repo resolves bumn-scoped
 * over global, which is what makes this work.
 *
 * EVERY VALUE HERE IS A FIXTURE VALUE, NOT A POLICY CLAIM. Nothing in this
 * folder asserts that any of these numbers is correct; the tests assert that
 * changing the row changes the behaviour.
 *
 * `rka.pemisahan_tugas_persetujuan` IS DELIBERATELY ABSENT. It is not in the
 * shipped catalogue, so seeding it here would be this fixture inventing a
 * parameter and would hide the finding ./rka-otorisasi.test.ts files. The
 * loader below refuses any key the catalogue does not carry, which is what
 * makes that impossible rather than merely discouraged.
 */
const KONFIGURASI_AWAL: ReadonlyArray<[string, string, string]> = [
  // spec 5.6. Report 24's cumulative column counts from this month.
  ["akuntansi", "tahun_buku_mulai_bulan", "1"],
  ["akuntansi", "metode_pengakuan_jasa_adm", "ACCRUAL"],
  ["akuntansi", "jasa_grace_period", "TIDAK_DIHITUNG"],
  // angsuran / jasa, needed because the REAL instalment engine builds the
  // schedules behind every PUMK disbursement this fixture makes.
  ["angsuran", "pembulatan_angsuran", "0"],
  ["angsuran", "urutan_alokasi_setoran_preset", "DEFAULT"],
  ["angsuran", "hari_jatuh_tempo_tetap", "0"],
  ["jasa_adm", "jasa_adm_rate_default", "0.030000"],
  ["jasa_adm", "jasa_adm_metode_default", "FLAT"],
  ["jasa_adm", "jasa_adm_basis_hari", "360"],
  ["jasa_adm", "turunkan_flat_dari_efektif", "false"],
  ["jasa_adm", "rate_efektif_acuan", "0.030000"],
  ["batasan", "plafon_min_pumk", "1000000.00"],
  ["batasan", "plafon_max_pumk", "250000000.00"],
  ["batasan", "tenor_min_bulan", "6"],
  ["batasan", "tenor_max_bulan", "36"],
  ["batasan", "grace_period_max_bulan", "6"],
  ["batasan", "wajib_jaminan_di_atas_plafon", "50000000.00"],
  ["batasan", "maks_pinjaman_aktif_per_mitra", "1"],
  ["batasan", "skor_survey_minimum_lolos", "70"],
  // The REAL Non PUMK engine reads these on every step of its state machine.
  ["batasan", "skor_penilaian_minimum_lolos_non_pumk", "70"],
  ["batasan", "nilai_min_non_pumk", "1000000.00"],
  ["batasan", "nilai_max_non_pumk", "500000000.00"],
  ["batasan", "batas_hari_lpj_non_pumk", "60"],
];

// ---------------------------------------------------------------------------
// The world's calendar and its default amounts
// ---------------------------------------------------------------------------

/**
 * 2026-01 .. 2027-12. Wide enough for a budget year plus the following one (a
 * revision approved in the next year still has periods to report against) and
 * deliberately no wider: every world is a fresh bumn with its own periods and
 * `bun run db:reset` is not run between files, so a period range is paid for
 * once per world and kept forever.
 */
export const TAHUN_AWAL = 2026;
export const TAHUN_AKHIR = 2027;
/** The budget year every test uses unless it says otherwise. */
export const TAHUN_RKA = 2026;

/**
 * DISTINCTIVE AMOUNTS, on purpose. No plausible hardcoded constant contains
 * 7.350.000 or 4.260.000, so an implementation that returned a rounded or
 * remembered figure cannot pass by accident, and every assertion that matters
 * reads the number back out of the source rather than restating it.
 */
export const PENCAIRAN_SEKTOR_A: Uang = rp(7_350_000);
export const PENCAIRAN_SEKTOR_B: Uang = rp(4_260_000);
export const PENYALURAN_BIDANG_A: Uang = rp(6_180_000);
export const REALISASI_BIDANG_A: Uang = rp(4_430_000);
export const BEBAN_OPERASIONAL_FEB: Uang = rp(3_370_000);
export const PENDAPATAN_GIRO_FEB: Uang = rp(1_140_000);

// ---------------------------------------------------------------------------
// Fixture shapes
// ---------------------------------------------------------------------------

export interface PeriodeFixture {
  id: string;
  tahun: number;
  bulan: number;
  tanggalMulai: string;
  tanggalAkhir: string;
}

export interface SektorFixture {
  id: string;
  kode: string;
  nama: string;
}

export interface BidangFixture {
  id: string;
  kode: string;
  nama: string;
}

export interface SdgFixture {
  id: string;
  nomor: number;
}

export interface PencairanFixture {
  akadId: string;
  mitraId: string;
  proposalId: string;
  pencairanId: string;
  jurnalId: string;
  sektorId: string;
  cabangId: string;
  tanggal: string;
  jumlah: Uang;
}

export interface PenyaluranNonPumkFixture {
  proposalId: string;
  penyaluranId: string;
  jurnalId: string;
  bidangId: string;
  akunBebanId: string;
  cabangId: string;
  tanggal: string;
  jumlah: Uang;
  /** Set once `verifikasiLpj` has posted the refund. */
  jurnalPengembalianId: string | null;
  pengembalian: Uang;
}

export interface SaldoAkunDb {
  akun_id: string;
  akun_kode: string;
  cabang_id: string;
  saldo_awal: string;
  mutasi_debit: string;
  mutasi_kredit: string;
  saldo_akhir: string;
}

export interface RkaDb {
  id: string;
  cabang_id: string | null;
  tahun: number;
  jenis: string;
  status: string;
  versi: number;
  approved_by: string | null;
  approved_at: string | null;
  keterangan: string | null;
  deleted_at: string | null;
}

export interface BarisRkaDb {
  id: string;
  akun_id: string | null;
  sektor_id: string | null;
  bidang_id: string | null;
  uraian: string;
  bulan: number | null;
  jumlah_anggaran: string;
  jumlah_unit: number | null;
}

export interface PanggilanAudit {
  aksi: string;
  entitas: string;
  entitasId: string | null;
  hasil: "SUKSES" | "DITOLAK";
  keterangan: string | null;
}

export interface PencatatAuditUji extends PencatatAuditRka {
  panggilan: PanggilanAudit[];
  reset(): void;
}

export interface OpsiPencairan {
  sektorId?: string;
  cabangId?: string;
  tanggal: string;
  jumlah?: Uang;
  tenor?: number;
}

export interface OpsiPenyaluranNonPumk {
  bidangId?: string;
  cabangId?: string;
  akunBebanId?: string;
  tanggal: string;
  jumlah?: Uang;
  /** Files and verifies an LPJ for less than was disbursed, so the REAL engine
   *  posts PENGEMBALIAN_SISA_NON_PUMK for the remainder. */
  realisasiLpj?: Uang | null;
  tanggalLpj?: string;
}

export interface DuniaRka {
  db: PortUji;
  bumnId: string;
  cabangId: string;
  cabangLainId: string;
  akun: Record<KunciAkun, AkunFixture>;
  sektor: { a: SektorFixture; b: SektorFixture };
  bidang: { a: BidangFixture; b: BidangFixture };
  sdg: SdgFixture;

  /** The engine under test, wired the way the composition root wires it. */
  engine: RkaEngine;
  /** The recording wrapper around the REAL audit service. */
  audit: PencatatAuditUji;
  /** Builds a SECOND engine, e.g. one with no audit sink wired. */
  buatEngine(opsi?: { audit?: PencatatAuditRka | undefined }): RkaEngine;
  /** The REAL Non PUMK engine, used to manufacture realisation. */
  nonpumk: NonPumkEngine;

  jam(): Date;
  /** Moves the injected clock. Every engine in this world reads it live. */
  setelJam(iso: string): void;

  userId: {
    maker: string;
    checker: string;
    approver: string;
    auditor: string;
    adminPusat: string;
    adminPusatLain: string;
    adminCabang: string;
  };
  /** Contexts whose `permissions` came from `permissionsForRole`, never a literal. */
  ctx: Record<keyof DuniaRka["userId"], RkaContext>;
  /** The role code behind each context, so a test can name the grant it read. */
  roleUntuk: Record<keyof DuniaRka["userId"], string>;

  // --- periods -------------------------------------------------------------
  periode(tahun: number, bulan: number): PeriodeFixture;
  bacaPeriode(periodeId: string): Promise<{ id: string; status: string }>;
  /**
   * Closes a period with raw SQL AND freezes its `saldo_akun_periode` from
   * `v_ledger_baris`.
   *
   * A PRECONDITION, NOT BEHAVIOUR UNDER TEST, and deliberately not the closing
   * engine. Two reasons:
   *   1. modules/closing is a different module's specification. Driving its ten
   *      prerequisite checks, its kolektibilitas run, its allowance and its
   *      accrual to arrange a budget report would make every failure in this
   *      folder ambiguous between the two engines, which is the opposite of
   *      what a tests-first suite is for.
   *   2. The freeze here uses `v_ledger_baris`, i.e. the ADR 0010 predicate,
   *      which is exactly what modules/closing is required to use. If the two
   *      ever disagree, that is a defect in the closing engine and its own
   *      suite says so (closing-saldo-ledger.test.ts), not something this
   *      fixture should paper over.
   * The rows satisfy `saldo_akun_periode_identitas_ck` by construction, and
   * ./rka-fixture.test.ts asserts that they match the ledger, so a broken
   * freeze fails here rather than silently weakening a report assertion.
   */
  tutupDanBekukan(periode: PeriodeFixture): Promise<SaldoAkunDb[]>;
  /** Closes a period without freezing anything, for the "the freeze did not
   *  happen" case the report must refuse rather than guess around. */
  tutupTanpaBekukan(periode: PeriodeFixture): Promise<void>;
  bacaSaldoAkunPeriode(periodeId: string): Promise<SaldoAkunDb[]>;
  /**
   * Moves a FROZEN figure without touching the ledger, preserving the identity
   * CHECK.
   *
   * THE POINT: it makes the frozen table and the live ledger disagree on
   * purpose, so a report test can prove WHICH ONE was read. Without a
   * divergence, an assertion that the figure is right passes identically on an
   * implementation that recomputed from the ledger, and the invariant 14
   * requirement stays untested exactly where it matters.
   *
   * Safe: `saldo_akun_periode` is derived data belonging to THIS world's own
   * period, regenerable from the ledger, and no other world can see it.
   */
  geserSaldoBeku(periodeId: string, akunId: string, delta: Uang): Promise<void>;

  // --- realisation, through the REAL engines --------------------------------
  /** A funded PUMK partner in a sector: real schedule, real PENCAIRAN_PUMK. */
  buatPencairanPumk(opsi: OpsiPencairan): Promise<PencairanFixture>;
  /**
   * A Non PUMK grant driven through the WHOLE real state machine, optionally
   * with an LPJ that returns part of the money.
   */
  buatPenyaluranNonPumk(opsi: OpsiPenyaluranNonPumk): Promise<PenyaluranNonPumkFixture>;
  /**
   * A DRAFT journal on an expense account, through the REAL ledger engine.
   *
   * NOT RAW SQL, and `bun tools/check-boundaries.ts` is what makes that
   * non-negotiable: only modules/jurnal may write `jurnal` or `jurnal_baris`
   * (invariant 11). It also happens to be the stronger fixture, because a
   * draft written by hand would not carry whatever the engine puts on one, and
   * the point of the test is that `v_ledger_baris` excludes what the ENGINE
   * calls a draft.
   */
  buatJurnalDraft(tanggal: string, nilai: Uang): Promise<Jurnal>;
  /** Posts BEBAN_OPERASIONAL: debit the chosen expense account, credit cash. */
  postingBebanOperasional(tanggal: string, nilai: Uang, akunBebanId?: string): Promise<Jurnal>;
  /** Posts PENDAPATAN_JASA_GIRO: debit cash, credit a revenue account. */
  postingPendapatanGiro(tanggal: string, nilai: Uang): Promise<Jurnal>;
  postingAlokasiDana(tanggal: string, nilai: Uang): Promise<Jurnal>;
  reversalJurnal(jurnalId: string, alasan: string): Promise<Jurnal>;

  // --- the readings report 24 must agree with -------------------------------
  /**
   * What Laporan Realisasi Penyaluran berdasarkan Sektor (spec 10.1 report 2)
   * reads: `pumk_pencairan`, joined to the sector through the proposal.
   * Spec 16 scenario 18's comparison target for RKA PUMK.
   */
  totalPencairanPumk(filter: {
    sektorId?: string;
    dari: string;
    sampai: string;
    cabangId?: string;
  }): Promise<Uang>;
  /** Distinct mitra funded in the window: spec 9.3's "jumlah mitra target". */
  jumlahMitraDicairkan(filter: {
    sektorId?: string;
    dari: string;
    sampai: string;
    cabangId?: string;
  }): Promise<number>;
  /**
   * What Rekap Penyaluran Non PUMK per Bidang (spec 10.2 report 13) reads:
   * `nonpumk_penyaluran`, GROSS of any refund. See ./rka-laporan-24.test.ts
   * for why the gross/net difference is a finding rather than an assertion.
   */
  totalPenyaluranNonPumk(filter: {
    bidangId?: string;
    dari: string;
    sampai: string;
    cabangId?: string;
  }): Promise<Uang>;
  /** The refunds `verifikasiLpj` posted in the window, per bidang. */
  totalPengembalianNonPumk(filter: {
    bidangId?: string;
    dari: string;
    sampai: string;
    cabangId?: string;
  }): Promise<Uang>;

  // --- the two ledger readings that must not be confused --------------------
  /**
   * THE CORRECT ONE. Debit-positive movement of an account inside an inclusive
   * date window, from the SHIPPED view `v_ledger_baris`
   * (`status IN ('POSTED','REVERSED')`).
   */
  mutasiLedger(
    akunId: string,
    dari: string,
    sampai: string,
    cabangId?: string,
  ): Promise<Uang>;
  /**
   * THE WRONG ONE, on purpose: the same sum with `status = 'POSTED'` alone.
   * Exists so a test can assert the two DIFFER before asserting which one the
   * report used. Without that, a test on data where both readings agree passes
   * vacuously. See ADR 0010 and migrations/0018.
   */
  mutasiLedgerNaifPostedSaja(
    akunId: string,
    dari: string,
    sampai: string,
    cabangId?: string,
  ): Promise<Uang>;
  /** The same window, expressed in the account's NORMAL sign, which is how a
   *  budget line is written and therefore how report 24 must show it. */
  mutasiNormal(akunId: string, dari: string, sampai: string, cabangId?: string): Promise<Uang>;
  /** Ledger movement restricted to lines carrying a `dimensi_json` key. */
  mutasiLedgerDimensi(
    akunId: string,
    dimensi: string,
    nilaiDimensi: string,
    dari: string,
    sampai: string,
  ): Promise<Uang>;
  /** The raw `dimensi_json` of every line of a journal, for the pin that says
   *  a PUMK disbursement carries no sector. */
  dimensiBarisJurnal(jurnalId: string): Promise<Array<Record<string, unknown>>>;

  // --- rka rows, read straight from the tables ------------------------------
  bacaRkaDb(rkaId: string): Promise<RkaDb>;
  daftarRkaDb(filter: { tahun?: number; jenis?: JenisRka }): Promise<RkaDb[]>;
  bacaBarisRkaDb(rkaId: string): Promise<BarisRkaDb[]>;

  // --- configuration knobs --------------------------------------------------
  /** Writes/updates THIS WORLD'S bumn-scoped row. Refuses a global write. */
  setelKonfigurasi(grup: string, kunciKonfig: string, nilai: string): Promise<void>;
  /** Soft-deletes THIS WORLD'S OWN row, never the global one. See the header. */
  hapusKonfigurasi(grup: string, kunciKonfig: string): Promise<void>;
  bacaKonfigurasi(grup: string, kunciKonfig: string): Promise<string | null>;

  /** Does `tabel.kolom` exist? Used to pin a schema gap as a finding. */
  kolomAda(tabel: string, kolom: string): Promise<boolean>;

  tutup(): Promise<void>;
}

async function satu<T>(db: RkaTx, sql: string, params: unknown[] = []): Promise<T> {
  const baris = await db.query<T>(sql, params);
  if (baris.length === 0) throw new Error(`fixture: query tidak mengembalikan baris: ${sql}`);
  return baris[0];
}

// ---------------------------------------------------------------------------
// The recording wrapper around the REAL audit service
// ---------------------------------------------------------------------------

export function pencatatAuditUji(db: RkaDbPort): PencatatAuditUji {
  const service = createAuditService({ db });
  const panggilan: PanggilanAudit[] = [];
  return {
    panggilan,
    reset() {
      panggilan.length = 0;
    },
    async record(entry, runner) {
      panggilan.push({
        aksi: entry.aksi,
        entitas: entry.entitas,
        entitasId: entry.entitasId ?? null,
        hasil: entry.hasil,
        keterangan: entry.keterangan ?? null,
      });
      return service.record(entry, runner);
    },
  };
}

// ---------------------------------------------------------------------------
// The world
// ---------------------------------------------------------------------------

/**
 * Builds a minimal but complete world: one bumn, two branches, monthly OPEN
 * periods for 2026-01 .. 2027-12, the SHIPPED chart of accounts and every
 * SHIPPED event mapping, the SHIPPED RBAC matrix with one user per role, this
 * module's parameter rows scoped to the world's bumn, two sectors, two bidang
 * and one SDG.
 */
export async function buatDunia(): Promise<DuniaRka> {
  const db = buatPortDb();

  let sekarang = new Date(`${TAHUN_AWAL}-06-15T04:00:00.000Z`);
  const jam = () => sekarang;

  const bumn = await satu<{ id: string }>(
    db,
    `insert into bumn (kode, nama, tahun_buku_mulai_bulan) values ($1, $2, 1) returning id::text as id`,
    [kunci("BUMN"), "PT Krakatau Steel (fixture rka)"],
  );
  const cabang = await satu<{ id: string }>(
    db,
    `insert into cabang (bumn_id, kode, nama, is_pusat) values ($1, $2, $3, true) returning id::text as id`,
    [bumn.id, kunci("CBG"), "Kantor Pusat (fixture rka)"],
  );
  const cabangLain = await satu<{ id: string }>(
    db,
    `insert into cabang (bumn_id, kode, nama) values ($1, $2, $3) returning id::text as id`,
    [bumn.id, kunci("CBG"), "Cabang B (fixture rka)"],
  );

  async function buatUser(nama: string, cabangId: string): Promise<string> {
    const u = await satu<{ id: string }>(
      db,
      `insert into app_user (cabang_id, nama, email, username, password_hash)
       values ($1, $2, $3, $4, 'x-not-a-real-hash') returning id::text as id`,
      [cabangId, nama, `${kunci("mail")}@example.test`, kunci("user")],
    );
    return u.id;
  }

  const userId = {
    maker: await buatUser("Maker (fixture rka)", cabang.id),
    checker: await buatUser("Checker (fixture rka)", cabang.id),
    approver: await buatUser("Approver (fixture rka)", cabang.id),
    auditor: await buatUser("Auditor (fixture rka)", cabang.id),
    adminPusat: await buatUser("Admin Pusat (fixture rka)", cabang.id),
    // A SECOND Admin Pusat, so the segregation mechanic of spec 2 can be
    // exercised at all: with one holder of the approval right there is nobody
    // for a "someone else must approve" rule to hand the document to, and the
    // test would be asserting the absence of a control rather than the control.
    adminPusatLain: await buatUser("Admin Pusat B (fixture rka)", cabang.id),
    adminCabang: await buatUser("Admin Cabang B (fixture rka)", cabangLain.id),
  };

  // The SHIPPED permission catalogue, the six SHIPPED system roles and the
  // SHIPPED grant matrix.
  //
  // THROUGH THE node-postgres ADAPTER ON PURPOSE, not through this world's
  // `bun:sql` port. `seedRbac` reconciles each role's grants with
  // `kode = ANY($2::text[])`, i.e. it binds a JS ARRAY, and driver fact 3 in
  // modules/jurnal/repo.ts applies: `bun:sql` serialises a JS array as a bare
  // comma-joined string, which `text[]` rejects with 22P02 "malformed array
  // literal". node-postgres serialises it correctly. `createDbAdapter` opens no
  // socket on import and shares one lazily-built pool across the whole test
  // process, so this costs no extra connection per world.
  const dbRbac = createDbAdapter();
  await seedRbac(dbRbac);

  const roleUntuk: Record<keyof typeof userId, string> = {
    maker: "MAKER",
    checker: "CHECKER",
    approver: "APPROVER",
    auditor: "AUDITOR",
    adminPusat: "ADMIN_PUSAT",
    adminPusatLain: "ADMIN_PUSAT",
    adminCabang: "ADMIN_CABANG",
  };
  const izinRole = new Map<string, string[]>();
  for (const kodeRole of new Set(Object.values(roleUntuk))) {
    izinRole.set(kodeRole, await permissionsForRole(dbRbac, kodeRole));
  }
  for (const [nama, kodeRole] of Object.entries(roleUntuk)) {
    await db.query(
      `insert into user_role (user_id, role_id)
       select $1, r.id from app_role r where r.kode = $2 and r.deleted_at is null
       on conflict (user_id, role_id) do nothing`,
      [userId[nama as keyof typeof userId], kodeRole],
    );
  }

  // Monthly OPEN periods, in ONE statement. `generate_series` builds the month
  // windows in Postgres, which is the only place that agrees with
  // `periode_window_ck` about what the last day of a month is without a second
  // implementation of the calendar in TypeScript.
  const periodeIndeks = new Map<string, PeriodeFixture>();
  const barisPeriode = await db.query<{
    id: string;
    tahun: number;
    bulan: number;
    mulai: string;
    akhir: string;
  }>(
    `insert into periode (bumn_id, tahun, bulan, tanggal_mulai, tanggal_akhir, status)
     select $1,
            extract(year from m)::smallint,
            extract(month from m)::smallint,
            m::date,
            (m + interval '1 month' - interval '1 day')::date,
            'OPEN'
       from generate_series(
              make_date($2::int, 1, 1),
              make_date($3::int, 12, 1),
              interval '1 month') as m
     returning id::text as id, tahun, bulan,
               tanggal_mulai::text as mulai, tanggal_akhir::text as akhir`,
    [bumn.id, TAHUN_AWAL, TAHUN_AKHIR],
  );
  for (const row of barisPeriode) {
    periodeIndeks.set(`${row.tahun}-${row.bulan}`, {
      id: row.id,
      tahun: row.tahun,
      bulan: row.bulan,
      tanggalMulai: row.mulai,
      tanggalAkhir: row.akhir,
    });
  }

  // The SHIPPED COA and every SHIPPED event mapping, by the same code path
  // `bun run db:seed` uses.
  const { akun: akunIdByKode } = await seedCoaDanEventMapping(db, bumn.id, userId.adminPusat);
  const akun = {} as Record<KunciAkun, AkunFixture>;
  for (const [nama, kode] of Object.entries(KODE_AKUN) as Array<[KunciAkun, string]>) {
    const id = akunIdByKode.get(kode);
    if (!id) {
      throw new Error(
        `fixture rka: akun ${kode} tidak ada setelah seedCoaInti; periksa apps/api/src/seed/coa-inti.ts`,
      );
    }
    const meta = await satu<{ saldo_normal: "D" | "K" }>(
      db,
      `select saldo_normal from akun where id = $1`,
      [id],
    );
    akun[nama] = { id, kode, saldoNormal: meta.saldo_normal };
  }

  // `tipe_data` and `pilihan_json` come from the SHIPPED catalogue, not from a
  // second table typed out here: a fixture row whose shape disagrees with the
  // catalogue is a fixture testing its own opinion, and a key absent from the
  // catalogue is a fixture inventing a parameter, so `entri` throwing is the
  // right answer.
  //
  // `$6::text::jsonb`, NOT `$6::jsonb`: driver fact 1 in modules/jurnal/repo.ts,
  // a jsonb parameter bound from a JS string is stored as a JSON string SCALAR,
  // so `jsonb_typeof` would answer 'string'. `konfigurasi.pilihan_json` is
  // queried elsewhere WITHOUT a bumn filter, so a bumn-scoped row with the
  // wrong shape is not invisible to somebody else's test.
  for (const [grup, kunciKonfig, nilai] of KONFIGURASI_AWAL) {
    const entri = KATALOG[`${grup}.${kunciKonfig}`];
    if (!entri) {
      throw new Error(
        `fixture rka: ${grup}.${kunciKonfig} tidak ada di katalog konfigurasi terkirim; ` +
          "fixture tidak boleh mengarang parameter",
      );
    }
    await db.query(
      `insert into konfigurasi
         (bumn_id, grup, kunci, nilai, tipe_data, pilihan_json, deskripsi, perlu_konfirmasi)
       values ($1, $2, $3, $4, $5, $6::text::jsonb, 'fixture rka (spec 5)', true)`,
      [
        bumn.id,
        grup,
        kunciKonfig,
        nilai,
        tipeDataUntuk(entri.bentuk),
        entri.pilihan ? JSON.stringify(entri.pilihan) : null,
      ],
    );
  }
  // The global (bumn_id NULL) capability defaults, from the REAL seed. ON
  // CONFLICT DO NOTHING on a NULLS NOT DISTINCT index, so worlds cannot fight
  // over them.
  await seedKonfigurasiTambahan(db);

  async function buatSektor(nama: string): Promise<SektorFixture> {
    const kode = kunci("SEK");
    const s = await satu<{ id: string }>(
      db,
      `insert into sektor_pumk (bumn_id, kode, nama) values ($1, $2, $3) returning id::text as id`,
      [bumn.id, kode, nama],
    );
    return { id: s.id, kode, nama };
  }
  async function buatBidang(nama: string): Promise<BidangFixture> {
    const kode = kunci("BDG");
    const b = await satu<{ id: string }>(
      db,
      `insert into bidang_non_pumk (bumn_id, kode, nama, created_by, updated_by)
       values ($1, $2, $3, $4, $4) returning id::text as id`,
      [bumn.id, kode, nama, userId.adminPusat],
    );
    return { id: b.id, kode, nama };
  }

  const sektor = {
    a: await buatSektor("Perdagangan (fixture rka)"),
    b: await buatSektor("Industri (fixture rka)"),
  };
  const bidang = {
    a: await buatBidang("Pendidikan (fixture rka)"),
    b: await buatBidang("Kesehatan (fixture rka)"),
  };

  // `sdg` rows are GLOBAL (unique on nomor, no bumn column). Inserted ON
  // CONFLICT DO NOTHING and never updated or deleted, so no world can perturb
  // another through them. See the file header.
  await db.query(
    `insert into sdg (nomor, nama) values (4, 'Pendidikan Berkualitas')
     on conflict (nomor) where deleted_at is null do nothing`,
  );
  const sdgRow = await satu<{ id: string; nomor: number }>(
    db,
    `select id::text as id, nomor from sdg where nomor = 4 and deleted_at is null`,
  );
  const sdg: SdgFixture = { id: sdgRow.id, nomor: sdgRow.nomor };

  // The real engines. Wired exactly the way the composition root wires them.
  const { engine: jurnalEngine } = createJurnalModule({ db, jam });
  const { engine: angsuranEngine } = createAngsuranModule({ db, jurnal: jurnalEngine, jam });
  const { engine: nonpumkEngine } = createNonPumkModule({ db, jurnal: jurnalEngine, jam });

  const porterAudit = pencatatAuditUji(db);

  function ctxUntuk(nama: keyof typeof userId): RkaContext {
    const kodeRole = roleUntuk[nama];
    const izin = izinRole.get(kodeRole) ?? [];
    const lintasCabang = kodeRole === "ADMIN_PUSAT" || kodeRole === "AUDITOR";
    const rumah = nama === "adminCabang" ? cabangLain.id : cabang.id;
    return {
      userId: userId[nama],
      cabangId: rumah,
      bumnId: bumn.id,
      permissions: izin,
      cabangDalamScope: lintasCabang ? [cabang.id, cabangLain.id] : [rumah],
    };
  }

  const ctx = {
    maker: ctxUntuk("maker"),
    checker: ctxUntuk("checker"),
    approver: ctxUntuk("approver"),
    auditor: ctxUntuk("auditor"),
    adminPusat: ctxUntuk("adminPusat"),
    adminPusatLain: ctxUntuk("adminPusatLain"),
    adminCabang: ctxUntuk("adminCabang"),
  } satisfies Record<keyof typeof userId, RkaContext>;

  const engine = createRkaEngine({ db, jam, audit: porterAudit });

  // --- helpers -------------------------------------------------------------

  function periode(tahun: number, bulan: number): PeriodeFixture {
    const p = periodeIndeks.get(`${tahun}-${bulan}`);
    if (!p) {
      throw new Error(
        `fixture rka: periode ${tahun}-${bulan} di luar rentang dunia (${TAHUN_AWAL}-01 .. ${TAHUN_AKHIR}-12)`,
      );
    }
    return p;
  }

  async function bacaSaldoAkunPeriode(periodeId: string): Promise<SaldoAkunDb[]> {
    return db.query<SaldoAkunDb>(
      `select s.akun_id::text as akun_id, a.kode as akun_kode, s.cabang_id::text as cabang_id,
              s.saldo_awal::numeric(20,2)::text as saldo_awal,
              s.mutasi_debit::numeric(20,2)::text as mutasi_debit,
              s.mutasi_kredit::numeric(20,2)::text as mutasi_kredit,
              s.saldo_akhir::numeric(20,2)::text as saldo_akhir
         from saldo_akun_periode s
         join akun a on a.id = s.akun_id
        where s.periode_id = $1 and s.deleted_at is null
        order by a.kode, s.cabang_id`,
      [periodeId],
    );
  }

  async function tutupTanpaBekukan(p: PeriodeFixture): Promise<void> {
    await db.query(
      `update periode set status = 'CLOSED', closed_by = $2, closed_at = now() where id = $1`,
      [p.id, userId.approver],
    );
  }

  async function tutupDanBekukan(p: PeriodeFixture): Promise<SaldoAkunDb[]> {
    // `coalesce(sum(...), 0)` returns '0', not '0.00'. Cast to numeric(20,2)
    // BEFORE ::text or the value fails POLA_UANG and every equality assertion.
    await db.query(
      `insert into saldo_akun_periode
         (periode_id, cabang_id, akun_id, saldo_awal, mutasi_debit, mutasi_kredit, saldo_akhir,
          created_by, updated_by)
       select $1, l.cabang_id, l.akun_id,
              coalesce(sum(case when l.tanggal_transaksi < $2 then l.debit - l.kredit else 0 end), 0)::numeric(20,2),
              coalesce(sum(case when l.tanggal_transaksi between $2 and $3 then l.debit else 0 end), 0)::numeric(20,2),
              coalesce(sum(case when l.tanggal_transaksi between $2 and $3 then l.kredit else 0 end), 0)::numeric(20,2),
              coalesce(sum(case when l.tanggal_transaksi <= $3 then l.debit - l.kredit else 0 end), 0)::numeric(20,2),
              $5, $5
         from v_ledger_baris l
        where l.bumn_id = $4 and l.tanggal_transaksi <= $3
        group by l.cabang_id, l.akun_id`,
      [p.id, p.tanggalMulai, p.tanggalAkhir, bumn.id, userId.approver],
    );
    await tutupTanpaBekukan(p);
    return bacaSaldoAkunPeriode(p.id);
  }

  async function mutasiDenganPredikat(
    predikat: "LEDGER" | "POSTED_SAJA",
    akunId: string,
    dari: string,
    sampai: string,
    cabangId?: string,
  ): Promise<Uang> {
    const sumber =
      predikat === "LEDGER"
        ? `from v_ledger_baris l
            where l.akun_id = $1 and l.tanggal_transaksi between $2 and $3 and l.bumn_id = $4`
        : `from jurnal_baris b join jurnal j on j.id = b.jurnal_id
            where b.akun_id = $1 and j.tanggal_transaksi between $2 and $3 and j.bumn_id = $4
              and j.status = 'POSTED' and j.deleted_at is null and b.deleted_at is null`;
    const kolom = predikat === "LEDGER" ? "l.debit - l.kredit" : "b.debit - b.kredit";
    const filterCabang =
      cabangId === undefined
        ? ""
        : predikat === "LEDGER"
          ? " and l.cabang_id = $5"
          : " and j.cabang_id = $5";
    const params: unknown[] = [akunId, dari, sampai, bumn.id];
    if (cabangId !== undefined) params.push(cabangId);
    const baris = await satu<{ nilai: string }>(
      db,
      `select coalesce(sum(${kolom}), 0)::numeric(20,2)::text as nilai ${sumber}${filterCabang}`,
      params,
    );
    return baris.nilai;
  }

  async function buatPencairanPumk(opsi: OpsiPencairan): Promise<PencairanFixture> {
    const cabangId = opsi.cabangId ?? cabang.id;
    const sektorId = opsi.sektorId ?? sektor.a.id;
    const jumlah = opsi.jumlah ?? PENCAIRAN_SEKTOR_A;
    const tenor = opsi.tenor ?? 12;
    const tanggalAkad = tambahHari(opsi.tanggal, -5);
    const mulaiAngsuran = tambahBulan(opsi.tanggal, 1);
    const jatuhTempoAkhir = tambahBulan(mulaiAngsuran, tenor - 1);

    // The proposal and the akad are written with raw SQL, on the same
    // reasoning modules/closing/test-support.ts records: they are
    // PRECONDITIONS from another module's state machine, and driving spec
    // 9.1's whole survey / review / approval chain to arrange a budget report
    // would turn one failure here into a cascade through modules/pumk. What
    // MUST be real is the part report 24 reads: the schedule (real instalment
    // engine, so the deferred total-pokok trigger applies) and the
    // disbursement journal (real ledger engine, through `postingEvent`, so
    // invariant 11 holds and the dimensions on the line are the production
    // ones).
    const kodeMitra = kunci("MTR");
    const mitra = await satu<{ id: string }>(
      db,
      `insert into mitra (cabang_id, kode_mitra, nama_lengkap, nik, sektor_id, status, nama_usaha)
       values ($1, $2, $3, $4, $5, 'CALON', $6) returning id::text as id`,
      [
        cabangId,
        kodeMitra,
        `Mitra ${kodeMitra}`,
        kunci("NIK").replace(/\D/g, "").padEnd(16, "0").slice(0, 16),
        sektorId,
        `Usaha ${kodeMitra}`,
      ],
    );
    const proposal = await satu<{ id: string }>(
      db,
      `insert into pumk_proposal
         (cabang_id, no_proposal, tanggal_proposal, tanggal_daftar, mitra_id, sektor_id,
          jumlah_diajukan, tenor_diajukan, tujuan_penggunaan, sumber_pengajuan, status,
          created_by, updated_by)
       values ($1, $2, $3, $3, $4, $5, $6, $7, 'Modal kerja (fixture rka)', 'INTERNAL',
               'DICAIRKAN', $8, $8)
       returning id::text as id`,
      [cabangId, kunci("PRP"), tanggalAkad, mitra.id, sektorId, jumlah, tenor, userId.maker],
    );
    const noAkad = kunci("AKD");
    const akad = await satu<{ id: string }>(
      db,
      `insert into pumk_akad
         (proposal_id, mitra_id, cabang_id, no_akad, tanggal_akad, pokok_pinjaman, jasa_adm_rate,
          metode_perhitungan, tenor_bulan, grace_period_bulan, tanggal_mulai_angsuran,
          tanggal_jatuh_tempo_akhir, status, created_by, updated_by)
       values ($1, $2, $3, $4, $5, $6, '0.030000', 'FLAT', $7, 0, $8, $9, 'BELUM_CAIR', $10, $10)
       returning id::text as id`,
      [
        proposal.id,
        mitra.id,
        cabangId,
        noAkad,
        tanggalAkad,
        jumlah,
        tenor,
        mulaiAngsuran,
        jatuhTempoAkhir,
        userId.maker,
      ],
    );

    await angsuranEngine.generateJadwal({ akadId: akad.id }, ctx.adminPusat as AngsuranContext);

    const pencairan = await satu<{ id: string }>(
      db,
      `insert into pumk_pencairan (akad_id, tanggal_pencairan, jumlah, akun_kas_id, no_bukti,
                                   keterangan, created_by, updated_by)
       values ($1, $2, $3, $4, $5, 'Pencairan (fixture rka)', $6, $6) returning id::text as id`,
      [akad.id, opsi.tanggal, jumlah, akun.kas.id, kunci("BKT"), userId.maker],
    );

    const jurnal = await jurnalEngine.postingEvent(
      "PENCAIRAN_PUMK",
      {
        cabangId,
        tanggalTransaksi: opsi.tanggal,
        nilai: jumlah,
        keterangan: `Pencairan PUMK akad ${noAkad} (fixture rka)`,
        akunKasId: akun.kas.id,
        // EXACTLY what modules/pumk sends: the piutang sub-ledger dimensions
        // and NOTHING ELSE. No `sektorId`. That omission is the subject of a
        // finding, so the fixture must not quietly add it here; doing so would
        // manufacture a ledger this system does not produce and would make a
        // per-sector report look reproducible when it is not.
        mitraId: mitra.id,
        akadId: akad.id,
        referensiTipe: "pumk_pencairan",
        referensiId: pencairan.id,
        kunciIdempotensi: `pumk_pencairan:${pencairan.id}`,
      },
      ctx.adminPusat as JurnalContext,
    );
    await db.query(`update pumk_pencairan set jurnal_id = $2 where id = $1`, [
      pencairan.id,
      jurnal.id,
    ]);
    const jasa = await satu<{ jasa: string }>(
      db,
      `select coalesce(sum(jasa_adm), 0)::numeric(20,2)::text as jasa
         from pumk_jadwal_angsuran
        where akad_id = $1 and is_active_version and deleted_at is null`,
      [akad.id],
    );
    await db.query(
      `update pumk_akad
          set status = 'AKTIF', outstanding_pokok = $2, outstanding_jasa = $3, updated_by = $4
        where id = $1`,
      [akad.id, jumlah, jasa.jasa, userId.maker],
    );

    return {
      akadId: akad.id,
      mitraId: mitra.id,
      proposalId: proposal.id,
      pencairanId: pencairan.id,
      jurnalId: jurnal.id,
      sektorId,
      cabangId,
      tanggal: opsi.tanggal,
      jumlah,
    };
  }

  async function buatPenyaluranNonPumk(
    opsi: OpsiPenyaluranNonPumk,
  ): Promise<PenyaluranNonPumkFixture> {
    const cabangId = opsi.cabangId ?? cabang.id;
    const bidangId = opsi.bidangId ?? bidang.a.id;
    const akunBebanId = opsi.akunBebanId ?? akun.bebanNonPumk.id;
    const jumlah = opsi.jumlah ?? PENYALURAN_BIDANG_A;

    // THE WHOLE REAL STATE MACHINE. Not a shortcut, and not raw SQL: spec 16
    // scenario 18 asks whether report 24 agrees with the disbursement reports,
    // and the only way that question means anything is if the rows both
    // reports read were written by the one engine that owns them. A fixture
    // that inserted `nonpumk_penyaluran` by hand and posted its own journal
    // would be comparing two of its own statements.
    const nCtx = (c: RkaContext): NonPumkContext => c as NonPumkContext;
    const tanggalProposal = tambahHari(opsi.tanggal, -20);

    const proposal = await nonpumkEngine.buatProposal(
      {
        cabangId,
        tanggalProposal,
        namaPemohon: `Yayasan ${kunci("YYS")}`,
        bidangId,
        sdg: [{ sdgId: sdg.id }],
        judulProgram: `Program ${kunci("PRG")}`,
        jumlahDiajukan: jumlah,
        penerimaManfaatEstimasi: 120,
      },
      nCtx(ctx.maker),
    );
    await nonpumkEngine.ajukanPenilaian(proposal.id, "Fixture rka", nCtx(ctx.maker));
    await nonpumkEngine.inputPenilaian(
      {
        proposalId: proposal.id,
        tanggal: tambahHari(tanggalProposal, 2),
        hasil: { kelayakan: 80, urgensi: 80, dampak: 80, kesesuaianBidang: 80, kesesuaianSdg: 80 },
        skorTotal: "80.00",
        nilaiRekomendasi: jumlah,
      },
      nCtx(ctx.maker),
    );
    await nonpumkEngine.review(
      {
        proposalId: proposal.id,
        tanggal: tambahHari(tanggalProposal, 4),
        keputusan: "REKOMENDASI",
      },
      nCtx(ctx.checker),
    );
    await nonpumkEngine.putuskanPersetujuan(
      {
        proposalId: proposal.id,
        tanggal: tambahHari(tanggalProposal, 6),
        keputusan: "SETUJU",
        jumlahDisetujui: jumlah,
      },
      nCtx(ctx.approver),
    );
    const penyaluran = await nonpumkEngine.catatPenyaluran(
      {
        proposalId: proposal.id,
        tanggalPenyaluran: opsi.tanggal,
        jumlah,
        akunKasId: akun.kas.id,
        akunBebanId,
        noBukti: kunci("BKT"),
      },
      nCtx(ctx.maker),
    );

    let jurnalPengembalianId: string | null = null;
    let pengembalian: Uang = "0.00";
    if (opsi.realisasiLpj) {
      const tanggalLpj = opsi.tanggalLpj ?? tambahHari(opsi.tanggal, 20);
      await nonpumkEngine.tutupPenyaluran(proposal.id, "Fixture rka", nCtx(ctx.maker));
      await nonpumkEngine.ajukanLpj(
        {
          proposalId: proposal.id,
          tanggalLpj,
          jumlahRealisasi: opsi.realisasiLpj,
          penerimaManfaatAktual: 105,
        },
        nCtx(ctx.maker),
      );
      await nonpumkEngine.verifikasiLpj(
        { proposalId: proposal.id, tanggalVerifikasi: tanggalLpj, akunKasId: akun.kas.id },
        nCtx(ctx.checker),
      );
      const lpj = await satu<{ jurnal: string | null; sisa: string }>(
        db,
        `select jurnal_id_pengembalian::text as jurnal,
                jumlah_sisa_dikembalikan::numeric(20,2)::text as sisa
           from nonpumk_lpj where proposal_id = $1 and deleted_at is null`,
        [proposal.id],
      );
      jurnalPengembalianId = lpj.jurnal;
      pengembalian = lpj.sisa;
    }

    const row = await satu<{ id: string; jurnal_id: string }>(
      db,
      `select id::text as id, jurnal_id::text as jurnal_id
         from nonpumk_penyaluran where proposal_id = $1 and deleted_at is null order by termin`,
      [proposal.id],
    );

    return {
      proposalId: proposal.id,
      penyaluranId: penyaluran.id ?? row.id,
      jurnalId: row.jurnal_id,
      bidangId,
      akunBebanId,
      cabangId,
      tanggal: opsi.tanggal,
      jumlah,
      jurnalPengembalianId,
      pengembalian,
    };
  }

  return {
    db,
    bumnId: bumn.id,
    cabangId: cabang.id,
    cabangLainId: cabangLain.id,
    akun,
    sektor,
    bidang,
    sdg,

    engine,
    audit: porterAudit,
    buatEngine: (opsi) => createRkaEngine({ db, jam, audit: opsi?.audit }),
    nonpumk: nonpumkEngine,

    jam,
    setelJam(iso) {
      sekarang = new Date(`${iso}T04:00:00.000Z`);
    },

    userId,
    ctx,
    roleUntuk,

    periode,
    bacaPeriode: (periodeId) =>
      satu(db, `select id::text as id, status from periode where id = $1`, [periodeId]),
    tutupDanBekukan,
    tutupTanpaBekukan,
    bacaSaldoAkunPeriode,
    async geserSaldoBeku(periodeId, akunId, delta) {
      // The identity CHECK must survive: move the debit movement and the
      // closing balance by the same amount.
      const n = await db.query(
        `update saldo_akun_periode
            set mutasi_debit = (mutasi_debit + $3::numeric(20,2))::numeric(20,2),
                saldo_akhir  = (saldo_akhir  + $3::numeric(20,2))::numeric(20,2),
                updated_at = now()
          where periode_id = $1 and akun_id = $2 and deleted_at is null
          returning id`,
        [periodeId, akunId, delta],
      );
      if (n.length === 0) {
        throw new Error(
          `fixture rka: tidak ada baris saldo_akun_periode untuk periode ${periodeId} akun ${akunId}; ` +
            "panggil tutupDanBekukan() lebih dulu",
        );
      }
    },

    buatPencairanPumk,
    buatPenyaluranNonPumk,
    async buatJurnalDraft(tanggal, nilai) {
      return jurnalEngine.buatJurnal(
        {
          cabangId: cabang.id,
          jenis: "UMUM",
          tanggalTransaksi: tanggal,
          keterangan: "Jurnal umum DRAFT (fixture rka)",
          baris: [
            { akunId: akun.bebanOperasional.id, debit: nilai },
            { akunId: akun.kas.id, kredit: nilai },
          ],
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    async postingBebanOperasional(tanggal, nilai, akunBebanId) {
      return jurnalEngine.postingEvent(
        "BEBAN_OPERASIONAL",
        {
          cabangId: cabang.id,
          tanggalTransaksi: tanggal,
          nilai,
          keterangan: "Beban operasional (fixture rka)",
          akunDebitId: akunBebanId ?? akun.bebanOperasional.id,
          akunKasId: akun.kas.id,
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    async postingPendapatanGiro(tanggal, nilai) {
      return jurnalEngine.postingEvent(
        "PENDAPATAN_JASA_GIRO",
        {
          cabangId: cabang.id,
          tanggalTransaksi: tanggal,
          nilai,
          keterangan: "Pendapatan jasa giro (fixture rka)",
          akunKasId: akun.kas.id,
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    async postingAlokasiDana(tanggal, nilai) {
      return jurnalEngine.postingEvent(
        "ALOKASI_DANA_BUMN_PEMBINA",
        {
          cabangId: cabang.id,
          tanggalTransaksi: tanggal,
          nilai,
          keterangan: "Alokasi dana BUMN Pembina (fixture rka)",
          akunKasId: akun.kas.id,
        },
        ctx.adminPusat as JurnalContext,
      );
    },
    reversalJurnal: (jurnalId, alasan) =>
      jurnalEngine.reversalJurnal(jurnalId, alasan, ctx.adminPusat as JurnalContext),

    async totalPencairanPumk(filter) {
      const params: unknown[] = [bumn.id, filter.dari, filter.sampai];
      let where = "";
      if (filter.sektorId) {
        params.push(filter.sektorId);
        where += ` and p.sektor_id = $${params.length}`;
      }
      if (filter.cabangId) {
        params.push(filter.cabangId);
        where += ` and a.cabang_id = $${params.length}`;
      }
      const baris = await satu<{ nilai: string }>(
        db,
        `select coalesce(sum(pc.jumlah), 0)::numeric(20,2)::text as nilai
           from pumk_pencairan pc
           join pumk_akad a on a.id = pc.akad_id
           join pumk_proposal p on p.id = a.proposal_id
           join cabang c on c.id = a.cabang_id
          where c.bumn_id = $1 and pc.tanggal_pencairan between $2 and $3
            and pc.deleted_at is null${where}`,
        params,
      );
      return baris.nilai;
    },
    async jumlahMitraDicairkan(filter) {
      const params: unknown[] = [bumn.id, filter.dari, filter.sampai];
      let where = "";
      if (filter.sektorId) {
        params.push(filter.sektorId);
        where += ` and p.sektor_id = $${params.length}`;
      }
      if (filter.cabangId) {
        params.push(filter.cabangId);
        where += ` and a.cabang_id = $${params.length}`;
      }
      const baris = await satu<{ n: string }>(
        db,
        `select count(distinct a.mitra_id)::text as n
           from pumk_pencairan pc
           join pumk_akad a on a.id = pc.akad_id
           join pumk_proposal p on p.id = a.proposal_id
           join cabang c on c.id = a.cabang_id
          where c.bumn_id = $1 and pc.tanggal_pencairan between $2 and $3
            and pc.deleted_at is null${where}`,
        params,
      );
      return Number.parseInt(baris.n, 10);
    },
    async totalPenyaluranNonPumk(filter) {
      const params: unknown[] = [bumn.id, filter.dari, filter.sampai];
      let where = "";
      if (filter.bidangId) {
        params.push(filter.bidangId);
        where += ` and p.bidang_id = $${params.length}`;
      }
      if (filter.cabangId) {
        params.push(filter.cabangId);
        where += ` and p.cabang_id = $${params.length}`;
      }
      const baris = await satu<{ nilai: string }>(
        db,
        `select coalesce(sum(s.jumlah), 0)::numeric(20,2)::text as nilai
           from nonpumk_penyaluran s
           join nonpumk_proposal p on p.id = s.proposal_id
           join cabang c on c.id = p.cabang_id
          where c.bumn_id = $1 and s.tanggal_penyaluran between $2 and $3
            and s.deleted_at is null${where}`,
        params,
      );
      return baris.nilai;
    },
    async totalPengembalianNonPumk(filter) {
      // Read from the LEDGER, through `v_ledger_baris`, because that is where
      // a refund exists: `nonpumk_lpj` records the amount but the movement per
      // bidang is the credit `verifikasiLpj` posted.
      //
      // MATCHED ON `referensi_tipe = 'nonpumk_lpj'`, NOT on `jurnal.jenis`.
      // `jenis` is the ledger's own vocabulary (KAS_BANK / UMUM / OTOMATIS /
      // ...) and every event-driven journal in the system is 'OTOMATIS', so a
      // filter on it would sweep in the disbursement it is supposed to be net
      // of. `referensi_tipe` is the polymorphic back-reference the ledger
      // stores for exactly this purpose (migrations/0010) and it is what
      // modules/nonpumk sets when it posts the refund.
      const params: unknown[] = [bumn.id, filter.dari, filter.sampai, akun.kas.id];
      let where = "";
      if (filter.bidangId) {
        params.push(filter.bidangId);
        where += ` and l.dimensi_json->>'bidangId' = $${params.length}`;
      }
      if (filter.cabangId) {
        params.push(filter.cabangId);
        where += ` and l.cabang_id = $${params.length}`;
      }
      // Two legs: debit cash, credit the bidang's own expense account. Summing
      // `kredit - debit` over the NON-CASH leg is the refund, positive.
      const baris = await satu<{ nilai: string }>(
        db,
        `select coalesce(sum(l.kredit - l.debit), 0)::numeric(20,2)::text as nilai
           from v_ledger_baris l
           join jurnal j on j.id = l.jurnal_id
          where l.bumn_id = $1 and l.tanggal_transaksi between $2 and $3
            and j.referensi_tipe = 'nonpumk_lpj'
            and l.akun_id <> $4${where}`,
        params,
      );
      return baris.nilai;
    },

    mutasiLedger: (akunId, dari, sampai, cabangId) =>
      mutasiDenganPredikat("LEDGER", akunId, dari, sampai, cabangId),
    mutasiLedgerNaifPostedSaja: (akunId, dari, sampai, cabangId) =>
      mutasiDenganPredikat("POSTED_SAJA", akunId, dari, sampai, cabangId),
    async mutasiNormal(akunId, dari, sampai, cabangId) {
      const debitPositif = await mutasiDenganPredikat("LEDGER", akunId, dari, sampai, cabangId);
      const meta = await satu<{ saldo_normal: "D" | "K" }>(
        db,
        `select saldo_normal from akun where id = $1`,
        [akunId],
      );
      return meta.saldo_normal === "D" ? debitPositif : negasiUang(debitPositif);
    },
    async mutasiLedgerDimensi(akunId, dimensi, nilaiDimensi, dari, sampai) {
      const baris = await satu<{ nilai: string }>(
        db,
        `select coalesce(sum(l.debit - l.kredit), 0)::numeric(20,2)::text as nilai
           from v_ledger_baris l
          where l.akun_id = $1 and l.bumn_id = $2
            and l.tanggal_transaksi between $4 and $5
            and l.dimensi_json ->> $3 = $6`,
        [akunId, bumn.id, dimensi, dari, sampai, nilaiDimensi],
      );
      return baris.nilai;
    },
    dimensiBarisJurnal: (jurnalId) =>
      db
        .query<{ dimensi_json: Record<string, unknown> }>(
          `select dimensi_json from jurnal_baris where jurnal_id = $1 and deleted_at is null order by urutan`,
          [jurnalId],
        )
        .then((rows) =>
          rows.map((r) =>
            typeof r.dimensi_json === "string"
              ? (JSON.parse(r.dimensi_json) as Record<string, unknown>)
              : r.dimensi_json,
          ),
        ),

    bacaRkaDb: (rkaId) =>
      satu<RkaDb>(
        db,
        `select id::text as id, cabang_id::text as cabang_id, tahun, jenis, status, versi,
                approved_by::text as approved_by, approved_at::text as approved_at,
                keterangan, deleted_at::text as deleted_at
           from rka where id = $1`,
        [rkaId],
      ),
    async daftarRkaDb(filter) {
      const params: unknown[] = [bumn.id];
      let where = "";
      if (filter.tahun !== undefined) {
        params.push(filter.tahun);
        where += ` and tahun = $${params.length}`;
      }
      if (filter.jenis !== undefined) {
        params.push(filter.jenis);
        where += ` and jenis = $${params.length}`;
      }
      return db.query<RkaDb>(
        `select id::text as id, cabang_id::text as cabang_id, tahun, jenis, status, versi,
                approved_by::text as approved_by, approved_at::text as approved_at,
                keterangan, deleted_at::text as deleted_at
           from rka where bumn_id = $1 and deleted_at is null${where}
          order by tahun, jenis, versi`,
        params,
      );
    },
    bacaBarisRkaDb: (rkaId) =>
      db.query<BarisRkaDb>(
        `select id::text as id, akun_id::text as akun_id, sektor_id::text as sektor_id,
                bidang_id::text as bidang_id, uraian, bulan,
                jumlah_anggaran::numeric(20,2)::text as jumlah_anggaran, jumlah_unit
           from rka_detail where rka_id = $1 and deleted_at is null
          order by bulan nulls first, uraian`,
        [rkaId],
      ),

    async setelKonfigurasi(grup, kunciKonfig, nilai) {
      const entri = KATALOG[`${grup}.${kunciKonfig}`];
      // A fixture that writes an uncatalogued key is a fixture inventing a
      // parameter, which is exactly how a fail-closed finding gets papered
      // over. See KONFIGURASI_AWAL's note about
      // `rka.pemisahan_tugas_persetujuan`.
      if (!entri) {
        throw new Error(
          `fixture rka: ${grup}.${kunciKonfig} tidak ada di katalog konfigurasi terkirim. ` +
            "Kalau modul memang membutuhkannya, itu TEMUAN yang harus difailkan lewat tes fail-closed, " +
            "bukan baris yang ditambahkan di fixture.",
        );
      }
      await db.query(
        `insert into konfigurasi (bumn_id, grup, kunci, nilai, tipe_data, deskripsi, perlu_konfirmasi)
         values ($1, $2, $3, $4, $5, 'fixture rka', true)
         on conflict (bumn_id, grup, kunci) where deleted_at is null
         do update set nilai = excluded.nilai, diubah_at = now()`,
        [bumn.id, grup, kunciKonfig, nilai, tipeDataUntuk(entri.bentuk)],
      );
    },
    async hapusKonfigurasi(grup, kunciKonfig) {
      // ONLY THIS WORLD'S OWN ROW, and the WHERE clause says so explicitly.
      // A closing test once soft-deleted the GLOBAL row to reach the same
      // guard and poisoned every world that ran afterwards. Blanking the
      // bumn-scoped row reaches the identical guard by the identical
      // bumn-then-global resolution order and is invisible to everyone else.
      await db.query(
        `update konfigurasi set deleted_at = now(), deleted_by = $4
          where bumn_id = $1 and grup = $2 and kunci = $3 and deleted_at is null`,
        [bumn.id, grup, kunciKonfig, userId.adminPusat],
      );
    },
    async bacaKonfigurasi(grup, kunciKonfig) {
      const baris = await db.query<{ nilai: string | null }>(
        `select nilai from konfigurasi
          where bumn_id = $1 and grup = $2 and kunci = $3 and deleted_at is null`,
        [bumn.id, grup, kunciKonfig],
      );
      return baris[0]?.nilai ?? null;
    },

    async kolomAda(tabel, kolom) {
      const baris = await db.query<{ n: string }>(
        `select count(*)::text as n from information_schema.columns
          where table_name = $1 and column_name = $2`,
        [tabel, kolom],
      );
      return Number.parseInt(baris[0]?.n ?? "0", 10) > 0;
    },

    tutup: () => db.tutup(),
  };
}

// ---------------------------------------------------------------------------
// Assertions shared by the test files
// ---------------------------------------------------------------------------

/**
 * Fragments that mean a raw driver or trigger string has leaked into a
 * user-facing message. The module must wrap DB failures in `RkaError` with a
 * clean Indonesian message and keep the raw text in `penyebabDb`.
 */
const POLA_KEBOCORAN_DB =
  /TJSL-[A-Z]{3}-\d{3}|PL\/pgSQL|plpgsql|SQLSTATE|violates|duplicate key|null value in column|relation "|_ck\b|_uq\b|ERROR:|syntax error at/i;

/**
 * Asserts a rejection is the expected DOMAIN error, and that its message is
 * free of DB internals. DELIBERATELY STRICT ABOUT THE TYPE AND THE CODE: the
 * stub in ./service.ts throws a plain `Error`, so this cannot be satisfied by
 * an unimplemented engine, which is the one failure mode a tests-first suite
 * exists to prevent.
 *
 * TAKES A PROMISE OR A THUNK. Prefer the thunk. A method that rejects from a
 * guard clause placed before its first `await`, in a function not declared
 * `async`, throws SYNCHRONOUSLY: the argument expression blows up at the call
 * site and this assertion never runs, so the test fails with a raw stack
 * instead of "expected KODE_X, got KODE_Y".
 */
export async function tolakDengan(
  janji: Promise<unknown> | (() => Promise<unknown> | unknown),
  kode: KodeRka,
): Promise<RkaError> {
  let ditangkap: unknown;
  try {
    await (typeof janji === "function" ? janji() : janji);
  } catch (e) {
    ditangkap = e;
  }
  if (ditangkap === undefined) {
    throw new Error(`diharapkan ditolak dengan ${kode}, tapi operasi berhasil`);
  }
  expect(ditangkap).toBeInstanceOf(RkaError);
  const err = ditangkap as RkaError;
  expect(err.kode).toBe(kode);
  expect(err.message.length).toBeGreaterThan(0);
  expect(err.message).not.toMatch(POLA_KEBOCORAN_DB);
  return err;
}

/** Sanity: every code a test names exists in the contract's catalogue. */
export function kodeAda(kode: KodeRka): KodeRka {
  expect(Object.values(KODE_RKA)).toContain(kode);
  return kode;
}

/**
 * Every money value crossing this module's boundary is a two-decimal string.
 *
 * NOT PEDANTRY. `coalesce(sum(x), 0)` comes back as '0', and report 24 is
 * mostly zeroes: a budget line with no realisation yet is the normal case, so
 * the un-cast path is hit on the very first run and every equality assertion
 * downstream fails with an unhelpful "expected 0.00, got 0".
 */
export function uangValid(nilai: unknown, label: string): void {
  expect(`${label}=${typeof nilai}`).toBe(`${label}=string`);
  expect(`${label}=${nilai as string}`).toMatch(
    new RegExp(`^${label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}=-?\\d{1,18}\\.\\d{2}$`),
  );
}

/** The same check for the percentage column, which may legitimately be null. */
export function persenValid(nilai: unknown, label: string): void {
  if (nilai === null) return;
  expect(`${label}=${typeof nilai}`).toBe(`${label}=string`);
  expect(`${label}=${nilai as string}`).toMatch(
    new RegExp(`^${label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}=-?\\d{1,10}\\.\\d{2}$`),
  );
}
