// Typed client for the manual journal surface, spec 6 and spec 9.4's seven
// screens. The routes landed in apps/api/src/modules/jurnal/routes.ts.
//
// TYPES COME FROM THE CONTRACT AND FROM ./baca.ts, TYPE ONLY, exactly as
// ./tools.ts and ./closing.ts do. Nothing is redeclared here, so a change on
// either side is a type error in this file rather than a wrong screen.
//
// THREE THINGS THIS FILE DELIBERATELY DOES NOT DO.
//
//   IT DOES NOT DECIDE WHETHER A JOURNAL IS VALID. Balance, "at least two
//   lines", "exactly one of debit and kredit", "that account is not postable"
//   and "that period is closed" are the ENGINE's rules, stated once, in one
//   place, with their own codes. A second opinion in the browser would be a
//   second answer, and the one on screen would be the one nobody can
//   reconcile. The forms show a running total because an accountant needs to
//   see one; the refusal always comes from the server.
//
//   IT DOES NOT OFFER A DELETE FOR A POSTED JOURNAL, because the API has none
//   and must never have one. `batalkan` cancels a DRAFT (the engine refuses
//   anything else) and `buatPembalik` is the only correction of a POSTED
//   entry. See ADR 0010: two rows are added, none is removed.
//
//   IT DOES NOT SEND `referensiTipe`, `referensiId`, `kunciIdempotensi` OR
//   `isAutoGenerated`. The router answers 400 on each of them rather than
//   ignoring them, and `BuatJurnalInput` here is narrowed to what a form may
//   legitimately fill in, so a screen cannot send one by accident.
import type {
  BarisJurnal,
  BarisJurnalInput,
  DimensiBaris,
  JenisJurnal,
  Jurnal,
  StatusJurnal,
  Uang,
} from "@krakatausteel/api/src/modules/jurnal/contract";
import type {
  BarisJurnalTampil,
  FilterJurnal,
  JurnalTampil,
  RingkasanJurnal,
} from "@krakatausteel/api/src/modules/jurnal/baca";
import { apiGet, apiPost, apiPut, buildQuery } from "./http";

export type {
  BarisJurnal,
  BarisJurnalInput,
  BarisJurnalTampil,
  DimensiBaris,
  JenisJurnal,
  Jurnal,
  JurnalTampil,
  RingkasanJurnal,
  StatusJurnal,
  Uang,
};

interface Daftar<T> {
  data: T[];
}

/**
 * The server's own ceiling on the document list, restated so a page can say
 * "this list is capped" instead of quietly showing a truncated ledger. Kept in
 * step with `BATAS_DAFTAR` in modules/jurnal/baca.ts.
 */
export const BATAS_DAFTAR_JURNAL = 500;

/** Spec 6.5's three manual document types, the only three this door creates. */
export const JENIS_MANUAL = ["UMUM", "KAS_BANK", "PINBUK"] as const;
export type JenisManual = (typeof JENIS_MANUAL)[number];

/** Every `jenis` the ledger holds, for the LIST FILTER only. */
export const JENIS_JURNAL_FILTER = [
  "UMUM",
  "KAS_BANK",
  "PINBUK",
  "OTOMATIS",
  "PENYISIHAN",
  "AKRUAL",
  "REVERSAL",
  "CLOSING",
  "SALDO_AWAL",
] as const;

export const LABEL_JENIS: Record<string, string> = {
  UMUM: "Jurnal Umum",
  KAS_BANK: "Jurnal Kas Bank",
  PINBUK: "Jurnal Pinbuk",
  OTOMATIS: "Jurnal Otomatis",
  PENYISIHAN: "Penyisihan",
  AKRUAL: "Akrual",
  REVERSAL: "Jurnal Pembalik",
  CLOSING: "Closing",
  SALDO_AWAL: "Saldo Awal",
};

/**
 * Where a row in the ledger came from (ADR 0012's `jalur_posting`). A screen
 * that could not see it would present an opening balance import and an
 * operator's own entry as the same kind of document.
 */
export const LABEL_JALUR: Record<string, string> = {
  ENGINE: "Engine aplikasi",
  SEED: "Seed data",
  IMPORT_SALDO_AWAL: "Impor saldo awal",
  LEGACY: "Data lama",
};

/** The reversal reason bounds, checked by the router as well as by this form. */
export const MIN_ALASAN_PEMBALIK = 10;
export const MAKS_ALASAN_PEMBALIK = 500;

/** The batch ceiling on `POST /jurnal/posting-batch`. */
export const MAKS_BATCH_POSTING = 200;

/**
 * What a FORM may fill in. Narrower than the engine's `BuatJurnalInput` on
 * purpose: see this file's header on the four fields the router refuses.
 */
export interface InputJurnalManual {
  cabangId: string;
  jenis: JenisManual;
  tanggalTransaksi: string;
  keterangan: string | null;
  baris: BarisJurnalInput[];
}

export interface FilterJurnalWeb {
  periodeId?: string | null;
  cabangId?: string | null;
  jenis?: string | null;
  status?: StatusJurnal | null;
  cari?: string | null;
  dariTanggal?: string | null;
  sampaiTanggal?: string | null;
  /** True: engine generated only. False: typed by a person only. Null: both. */
  otomatis?: boolean | null;
}

export type { FilterJurnal };

/** The document list, newest transaction first, capped at BATAS_DAFTAR_JURNAL. */
export function daftarJurnal(filter: FilterJurnalWeb = {}): Promise<Daftar<RingkasanJurnal>> {
  return apiGet(
    `/jurnal${buildQuery({
      periodeId: filter.periodeId ?? null,
      cabangId: filter.cabangId ?? null,
      jenis: filter.jenis ?? null,
      status: filter.status ?? null,
      cari: filter.cari ?? null,
      dariTanggal: filter.dariTanggal ?? null,
      sampaiTanggal: filter.sampaiTanggal ?? null,
      otomatis: filter.otomatis === null || filter.otomatis === undefined ? null : String(filter.otomatis),
    })}`,
  );
}

/**
 * One document with its lines, the accounts named, and both ends of its
 * correction pair resolved to document numbers.
 *
 * A journal in another branch answers 404 rather than 403, by design: the id
 * selects the row and the row states its own branch, so a manipulated id
 * cannot confirm that a document exists somewhere the caller may not look.
 */
export function detailJurnal(id: string): Promise<JurnalTampil> {
  return apiGet(`/jurnal/${encodeURIComponent(id)}`);
}

/** Always born DRAFT. There is no flag on this call that could post it. */
export function buatJurnal(input: InputJurnalManual): Promise<Jurnal> {
  return apiPost("/jurnal", input);
}

/**
 * Replaces the WHOLE draft, header and lines. A PUT and not a PATCH because
 * that is what the engine does: every line is deleted and rewritten, and a
 * partial merge here would be this client merging a document the engine never
 * merges.
 */
export function ubahJurnal(id: string, input: InputJurnalManual): Promise<Jurnal> {
  return apiPut(`/jurnal/${encodeURIComponent(id)}`, input);
}

/**
 * Cancels a DRAFT. `deleted_at` plus `deleted_by`: the attempt stays in the
 * database and in the audit log. Anything that is not a DRAFT is refused by
 * the engine, and a POSTED journal is corrected by `buatPembalik` alone.
 */
export function batalkanJurnal(id: string): Promise<{ id: string; dibatalkan: boolean }> {
  return apiPost(`/jurnal/${encodeURIComponent(id)}/batal`);
}

/** Checker's act. The engine refuses the journal's own author (spec 2 rule 1). */
export function verifikasiJurnal(id: string): Promise<Jurnal> {
  return apiPost(`/jurnal/${encodeURIComponent(id)}/verifikasi`);
}

/** DRAFT to POSTED. Nothing here retries: a lost race must not get a second go. */
export function postingJurnal(id: string): Promise<Jurnal> {
  return apiPost(`/jurnal/${encodeURIComponent(id)}/posting`);
}

/** Atomic. One invalid member leaves NOTHING posted (spec 6.6.8). */
export function postingBatch(ids: readonly string[]): Promise<Daftar<Jurnal>> {
  return apiPost("/jurnal/posting-batch", { ids });
}

/**
 * SPEC 9.4's "HAPUS JURNAL TRANSAKSI", AND IT IS A CREATE.
 *
 * The answer is the REVERSING journal: `jenis` REVERSAL, debit and credit
 * swapped line for line, dated in the CURRENT OPEN period because the
 * original's period may already be closed, with the original's number quoted
 * in its `keterangan`. The original is marked REVERSED and STAYS IN THE
 * LEDGER, where `v_ledger_baris` counts both halves so the pair nets to zero.
 *
 * 201 and not 200, deliberately, on the server: answering 200 would read as
 * "the delete succeeded", which is the exact misunderstanding the whole design
 * exists to prevent. The screen says the same thing in words BEFORE the click.
 */
export function buatPembalik(id: string, alasan: string): Promise<Jurnal> {
  return apiPost(`/jurnal/${encodeURIComponent(id)}/pembalik`, { alasan });
}
